src/dialect/onnx/onnx_ops.cpp, test/mlir/onnx/onnx_shape_inference.mlir
Common infrastructure to Conv and Maxpool to handle padding. Handle arbitrary strides, pads, and dilations.
=> Inter common pad

src/pass/onnx_rewrite.td, test/mlir/onnx/onnx_canonicalization.mlir
This patch is to change the padding value from zero to negative infinity.
=> Padding value for MaxPool must be negative infinity instead of zero

doc/gen_doc.py, src/CMakeLists.txt, src/conversion/onnx_to_krnl/convert_onnx_to_krnl.cpp, src/conversion/onnx_to_krnl/onnx_to_krnl_common.hpp, src/conversion/onnx_to_krnl/tensor/constant.cpp, src/dialect/onnx/onnx_ops.cpp, src/dialect/onnx/onnxop.inc, src/pass/shape_inference_pass.cpp, test/mlir/onnx/onnx_lowering.mlir, test/mlir/onnx/onnx_shape_inference.mlir
This lowering only supports dense array though its shape inference supports both dense and sparse array.
=> Lower ConstantOp

doc/gen_doc.py, src/Dialect/ONNX/ONNXOps.cpp, src/Dialect/ONNX/ONNXOps.td.inc, src/Transform/ONNX/ShapeInferencePass.cpp, test/mlir/onnx/onnx_shape_inference.mlir
=> implement shape inference for concat

src/Runtime/DynMemRef.h
This looks useful to support from C, I made it so that it could be included from a C program.
=> Makes the DynMemRef.h usable from C

.buildbot/z13.sh
=> Detect llvm-project commit change in utils/clone-mlir.sh and rebuild llvm-project for zLinux Jenkins build bot

src/CMakeLists.txt, src/Runtime/CMakeLists.txt
Resolves #147 . Thanks @tjingrant for suggesting the solution.
=> Fix cruntime not existed

.travis.yml
Was tagging the image with "latest", should be the CPU type
=> fix wrong tag on docker image

src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp, src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
This PR enables us to set `alignment` attribute in `AllocOp` which is created in `insertAllocAndDealloc()` by adding new argument.
=> Set alignment attribute to AllocOp of insertAllocAndDealloc()

.travis.yml
I fixed the github action that builds the prereq, but I forgot to fix this one
=> use secret instead of token

src/Builder/FrontendDialectHelper.cpp
Adding a select case in the helper to pick up int8 tensors
=> Added builder case for int8 tensors in the dialect

src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
=> Fix wrong type for llvm::loadop

src/Conversion/ONNXToKrnl/NN/Conv.cpp, src/Dialect/ONNX/ONNXOps.td.inc, src/Transform/ONNX/Combine.cpp, src/Transform/ONNX/Combine.td, test/backend/test.py, test/mlir/onnx/onnx_lowering.mlir, utils/gen_onnx_mlir.py
Enabled VGG & Shufflenet tests.
=> Dropout elimination & Conv Bugfix

README.md
=> Add x86-macOS CI status badge to README

src/MainUtils.cpp
=> Add a modification that was missing when updating to the new llvm commit id

.travis.yml
Stopping nightly build at least for now to try speeding up the build.
=> stop nightly build

src/Builder/FrontendDialectTransformer.cpp
Signed-off-by: Kevin O'Brien <caomhin@us.ibm.com>
=> custom op was always gen'd

include/onnx-mlir/Runtime/OMTensor.h, src/Runtime/OMTensor.inc, src/Runtime/PyExecutionSession.cpp
=> Create a seperate function omTensorSetStridesWithPyArrayStrides to avoid confusion

.buildbot/z13.sh, test/backend/CMakeLists.txt, test/backend/test.py
Enable backend tests with dynamic shape on s390x Jenkins CI
=> Dynamic backend test s390x

.buildbot/Jenkinsfile, .buildbot/jenkins-build-llvm-project.py, .buildbot/jenkins-build-onnx-mlir.py, docker/Dockerfile.onnx-mlir, src/main.cpp, test/unit/Runtime/DocExampleTest/CMakeLists.txt
- remove PR # from GitHub status line to save space
- correct typo LLMV in main.cpp
- make DocExampleTest installation of onnx on x86 less verbose
=> A few small fixes

docker/Dockerfile.onnx-mlir, docker/Dockerfile.onnx-mlir-dev
=> Keep build artifacts in the onnx-mlir-dev image

.buildbot/Jenkinsfile, .buildbot/ONNX-MLIR-Pipeline-Docker-Build.xml, test/backend/test.py
- Save Jenkins build job xml for easy restore and migration
- Remove call_build_script in Jenkinsfile
- Allow TEST_CASE_BY_USER to specify multiple tests (separated by
spaces) in test/backend/test.py
=> Save Jenkins build job xml

src/Builder/FrontendDialectTransformer.cpp, src/Runtime/InputSignature.cpp, src/Runtime/InputSignature.h, src/Runtime/OutputSignature.cpp, src/Runtime/OutputSignature.h
Added functions in Runtime to retrieve the signatures. Also added a comment for Alex about the JSON string format.
=> Signature functions

.circleci/config.yml, README.md, docs/README.md, utils/clone-mlir.sh
Signed-off-by: Kevin O'Brien <caomhin@us.ibm.com>
=> Update llvm to Release 12.0 rc5

src/Transform/BundleMemoryPools.cpp, test/mlir/krnl/krnl_bundle_aligned_memory_pool.mlir
Move aligned dynamic memory pool to the correct position.
=> Move aligned dynamic memory pool to the correct position.

src/Dialect/Krnl/KrnlOps.cpp
Same as PR #664 for llvm-12-release-branch
=> fix for release mode (llvm-12-release-branch)

test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
Signed-off-by: Kevin O'Brien <caomhin@us.ibm.com>
=> change name of suplicate function

.buildbot/jenkins-build-llvm-project.py, .buildbot/jenkins-build-project.py, .buildbot/jenkins-cleanup-build-states.py, docker/Dockerfile.onnx-mlir
- Tag dangling image when build fails for easier debugging
- Build user image with Release type
=> Tag dangling image when build fails (master)

README.md, docs/README.md, utils/install-onnx-mlir.sh
Some other small cleanup in the readme as well
=> Add a couple of CMake variables and their usage to the readme

src/Conversion/KrnlToAffine/KrnlToAffine.cpp
Unroll the innermost simonized loop of GEMM by I and K loops, resulting in a kernel with 32 load, 16 load splat, 64 FMAs and 0 store. Unroll K by a factor of 4 turned out almost as good as unrolling of 64, prefer to keep the smaller unroll factor to increase applicability.
=> Gemm k unrolled

README.md
=> Try again fixing the build badge

src/Runtime/OMInstrument.inc
Signed-off-by: Steven Royer <seroyer@us.ibm.com>
=> Fix OMInstrument.inc include on z/OS

utils/RunONNXLib.cpp
Added support to run a given .so where the user can provide the runtime dimensions of a model by a line argument. For example a model with the following signature
```
builtin.func @main_graph(%arg0: tensor<?x?x204xf32>) -> tensor<?x?x1xf32> { ... }
```
can be run with after being compiled with the first 2 "?" being replaced by 7 and 2018, respectively.
```
run-onnx-lib model.so -d "[7, 2048]" -m 8
```
=> Run-onnnx-lib for models with dynamic/runtime dimensions

docs/doc_example/main.c
Signed-off-by: david.cheng <david.cheng@enflame-tech.com>
=> fix the mistake of shape in doc-example

src/Conversion/ONNXToKrnl/CMakeLists.txt, src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp, src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp, src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp, src/Conversion/ONNXToKrnl/Tensor/Reshape.cpp, src/Conversion/ONNXToKrnl/Tensor/SpaceToDepth.cpp, src/Dialect/ONNX/ONNXOpsHelper.cpp, src/Dialect/ONNX/ONNXOpsHelper.hpp, test/mlir/onnx/onnx_lowering_space_to_depth.mlir
This PR adds the ONNX to Krnl lowering transformation for the `SpaceToDepth `operator. The operator is lowered by virtue of a reshape operation followed by a transpose and a final reshape.
=> SpaceToDepth lowering to krnl.

src/Dialect/ONNX/ONNXOps.cpp, src/Dialect/ONNX/ONNXOps.td.inc, test/mlir/onnx/onnx_shape_inference.mlir, utils/gen_onnx_mlir.py
Signed-off-by: david.cheng <david.cheng@enflame-tech.com>
=> add the implementation of inferShapes for ONNXScatterNDOp

src/Builder/FrontendDialectTransformer.cpp
There are two issues caused by LoopOp:
1. The tensors in output list of graph may appear in the input list. Add the code to allow that.
2. The none constant was added to a wrong place. Previous code tried to generate one `none` for the whole function. But the `none` is generated at Op when it is first used. There are two LoopOps in sequential.onnx. The op in the second loop can not access `none` generated in the first loop body. Even though the `none` could be generated at the beginning of the function, I'd like to keep the code simple by generating none for each usage. The optimization will anyway optimize them out.
=> fixes frontend errors found in sequential.onnx

.azure-pipelines/Windows-CI.yml, .buildbot/Jenkinsfile, .buildbot/ONNX-MLIR-Pipeline-Docker-Build.xml, .buildbot/jenkins-build-llvm-project.py, .buildbot/jenkins-build-project.py, .buildbot/jenkins-cleanup-build-states.py, .buildbot/jenkins-publish-docker-images.py, .buildbot/jenkins-stop-previous-build.py, .github/workflows/doxygen-docs-publish.yml
=> switch to main

CMakeLists.txt, docs/Testing.md, src/Runtime/jni/CMakeLists.txt, src/Runtime/jni/Jsoniter.cmake, src/Runtime/jni/jniwrapper.c
=> Use cmake ExternalProject to download or build jsoniter

src/Runtime/CMakeLists.txt
=> Add onnx definitions and includes to PyRuntime

src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp, src/Dialect/ONNX/MLIRDialectBuilder.cpp, src/Transform/ONNX/ONNXOpTransformPass.cpp
=> Fix compiler warnings

src/Dialect/ONNX/IndexExprDetail.cpp, src/Runtime/OMInstrument.inc, src/Transform/ONNX/ONNXOpTransformPass.cpp
Fix a few more warnings I found on the continuos integration build bots logs 
=> Fix Warnings

README.md
Adding info listed in issue #1016 as solution to a make error on MacOS
=> Adding suggested workaround that some experience on MacOS

README.md
=> Fix MacOS build badge

src/Dialect/ONNX/ONNXOps.cpp
Small fix: previous code forgot to check hasRank().
=> fix shape inference for SequenceInsert

docs/BuildOnLinuxOSX.md, docs/BuildOnWindows.md, src/Builder/OpBuildTable.inc.dc, src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp, src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp, src/Conversion/ONNXToKrnl/Math/Elementwise.cpp, src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp, src/Dialect/Krnl/KrnlOps.cpp, test/mlir/krnl/krnl_to_llvm_omtensor_ownership.mlir, utils/clone-mlir.sh
Update LLVM to commit 676bfb2a226.
=> Update LLVM to commit 676bfb2a226.

.buildbot/jenkins-build-llvm-project.py, .buildbot/jenkins-build-project.py, docker/Dockerfile.llvm-project, docker/Dockerfile.onnx-mlir, docker/Dockerfile.onnx-mlir-dev
=> Avoid reusing broken image tagged for debugging

.buildbot/Jenkinsfile, .buildbot/ONNX-MLIR-Pipeline-Docker-Build.xml
=> Remove '\r' in commit message when constructing build description

docs/Workflow.md
Text in angle braces are not shown if they are not in quotes.
=> Add quotes for angle braces

docker/Dockerfile.onnx-mlir
This is extracted from PR #1219.
=> Enable NNPA build on Jenkins Linux s390x

src/Dialect/ONNX/MLIRDialectBuilder.cpp, test/perf/PerfConv.cpp, test/perf/PerfGemm.cpp, test/unit/TestInstrumentation.cpp
Fix warnings for gcc and clang. Closes #1245 and closes #1230.
=> Fix instrument and posinf warnings

src/Conversion/ONNXToKrnl/Tensor/Gather.cpp, src/Dialect/ONNX/IndexExpr.hpp, test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
=> [Gather] Use builder based interface to generate Krnl loops

src/Conversion/ONNXToKrnl/Tensor/ReverseSequence.cpp, test/mlir/onnx/onnx_lowering.mlir
=> [ReverseSequence] Use builder based interface to generate Krnl loops

src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp, src/Conversion/KrnlToAffine/KrnlCopyFromBuffer.cpp, src/Conversion/KrnlToAffine/KrnlCopyToBuffer.cpp, src/Conversion/KrnlToAffine/KrnlMatmul.cpp, src/Conversion/ONNXToKrnl/Math/CumSum.cpp, src/Conversion/ONNXToKrnl/Math/Gemm.cpp, src/Conversion/ONNXToKrnl/Math/Softmax.cpp, src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp, src/Conversion/ONNXToKrnl/ObjectDetection/NonMaxSuppression.cpp, src/Conversion/ONNXToKrnl/Tensor/Compress.cpp, src/Conversion/ONNXToKrnl/Tensor/Expand.cpp, src/Conversion/ONNXToKrnl/Tensor/Gather.cpp, src/Conversion/ONNXToKrnl/Tensor/OneHot.cpp, src/Conversion/ONNXToKrnl/Tensor/Pad.cpp, src/Conversion/ONNXToKrnl/Tensor/Range.cpp, src/Conversion/ONNXToKrnl/Tensor/ReverseSequence.cpp, src/Dialect/ONNX/ShapeInference/MatMul.cpp, src/Dialect/ONNX/ShapeInference/ONNXShapeHelper.cpp, test/mlir/onnx/onnx_lowering.mlir, test/mlir/onnx/onnx_lowering_range_op.mlir
=> Hoist invariant literal outside of loop

src/Conversion/ONNXToKrnl/Tensor/ConstantOfShape.cpp, test/mlir/onnx/onnx_lowering.mlir
=> [ConstantOfShape] Use builder based interface to generate Krnl loops

src/Conversion/ONNXToKrnl/Tensor/Range.cpp, test/mlir/onnx/onnx_lowering_range_op.mlir
=> [Range] Use builder based interface to generate Krnl loops

src/Conversion/ONNXToKrnl/ControlFlow/Loop.cpp, test/mlir/onnx/onnx_lowering.mlir
Fixed assertion failure reported in https://github.com/onnx/onnx-mlir/issues/1344.
=> [Loop] Fix "expected same rank" assertion

docker/Dockerfile.onnx-mlir, docker/Dockerfile.onnx-mlir-dev, src/Accelerators/NNPA/CMakeLists.txt, src/Accelerators/NNPA/zdnn.cmake, test/mlir/accelerators/nnpa/module_op_be/lit.local.cfg
=> Fix NNPA lit tests on non-z archs

src/Conversion/ONNXToKrnl/Math/Elementwise.cpp, src/Conversion/ONNXToKrnl/Math/Gemm.cpp, src/Conversion/ONNXToKrnl/Math/LRN.cpp, src/Conversion/ONNXToKrnl/Math/MatMul.cpp, src/Conversion/ONNXToKrnl/Math/RandomNormal.cpp, src/Conversion/ONNXToKrnl/Math/RandomNormalLike.cpp, src/Conversion/ONNXToKrnl/Math/Reduction.cpp, src/Conversion/ONNXToKrnl/Math/Softmax.cpp, src/Conversion/ONNXToKrnl/NN/Conv.cpp, src/Conversion/ONNXToKrnl/NN/Pooling.cpp, src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp, src/Conversion/ONNXToKrnl/RNN/RNNBase.cpp, src/Conversion/ONNXToKrnl/RNN/RNNBase.hpp, src/Conversion/ONNXToKrnl/Tensor/ArgMax.cpp, src/Conversion/ONNXToKrnl/Tensor/ConstantOfShape.cpp, src/Conversion/ONNXToKrnl/Tensor/Pad.cpp, src/Conversion/ONNXToKrnl/Tensor/Range.cpp, src/Conversion/ONNXToKrnl/Tensor/Size.cpp, src/Conversion/ONNXToKrnl/Tensor/Tile.cpp, src/Support/KrnlSupport.cpp, src/Support/KrnlSupport.hpp, src/Transform/BundleMemoryPools.cpp, src/Transform/LowerKrnlShape.cpp
Replace emitConstantOp by MathBuilder.constant
=> Replace emitConstantOp by MathBuilder.constant

src/Dialect/ONNX/Rewrite.td
See https://github.com/llvm/llvm-project/blob/64186e9b351a000123f253557f4f607c33405413/mlir/include/mlir/IR/BuiltinTypeInterfaces.td#L137
=> Avoid assertion failure of some rewriter pattern constraints

.buildbot/jenkins-check-model-zoo.py
=> Pre-create model zoo work dir and repoort dir

docs/Workflow.md
=> changed CLA to DCO

src/Dialect/ONNX/ShapeInference/MatMul.cpp, test/mlir/onnx/onnx_lowering_with_canonicalize.mlir, test/mlir/onnx/onnx_shape_inference.mlir
=> MatMul 1-D x 1-D results in scalar

.github/workflows/macos-amd64-build.yml, utils/check-onnx-backend-numerical.sh, utils/check-onnx-backend.sh, utils/check-onnx-numerical.sh
=> Run backend and numerical tests in parallel on MacOS build

.github/workflows/macos-amd64-build.yml
On MacOS, replace "pip3 install -e" with "python3 setup install" when installing onnx
=> Try fixing onnx installation on MacOS

.buildbot/jenkins-watch-llvm-project.py
=> Fixes for LLVM watch Jenkins job when starting a new search cycle

docs/BuildOnLinuxOSX.md, docs/BuildOnWindows.md, utils/clone-mlir.sh
=> Try llvm commit 59548fe873d8d98e359fb21fbb2a0852fed17ff5 to see if it works for macos

README.md, docs/Prerequisite.md
=> Update prereq docs

src/Dialect/Mlir/DialectBuilder.hpp
Signed-off-by: Philip Lassen <philiplassen+git@gmail.com>
=> Fix namespace leak

src/Dialect/ONNX/ShapeInference/ONNXShapeHelper.cpp
=> Do not updateType in shape inference if it's scalar tensor

src/Dialect/Krnl/DialectBuilder.cpp, src/Dialect/Krnl/DialectBuilder.hpp, src/Dialect/Mlir/DialectBuilder.cpp, src/Dialect/Mlir/IndexExpr.cpp, src/Dialect/Mlir/IndexExprDetail.cpp, src/Dialect/Mlir/IndexExprDetail.hpp, src/Dialect/ONNX/DialectBuilder.cpp, src/Dialect/ONNX/DialectBuilder.hpp
=> [non functional] fix typos in IndexExpr and builders

README.md
Added open invitation to our weekly Tu evening (8-9pm  EST) meetings.
Everyone is welcome to attend.
=> [Doc only] Added public meeting invite to README

src/Dialect/ONNX/ONNXOps.cpp, test/mlir/onnx/invalid.mlir, test/mlir/onnx/onnx_shape_inference.mlir
also added more checks to ONNXSplitToSequenceOp::verify()
added lit tests for ONNXSplitToSequenceOp::verify() 
added SplitToSequence shape inference lit tests
=> implemented shape inference for SplitToSequence 

src/Conversion/ONNXToKrnl/Math/Gemm.cpp, src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp, src/Dialect/Mlir/IndexExpr.cpp, test/mlir/conversion/onnx_to_mhlo/Tensor/Concat.mlir, utils/gen_onnx_mlir.py
Fixed a few spelling errors, mostly in gen_onnx_plir.py, changed a few variable names to use the python convention.
=> Spelling and variable names

src/Conversion/ONNXToKrnl/ControlFlow/If.cpp, test/mlir/onnx/onnx_lowering.mlir
borrowed ideas from ConvertTrivialIfToSelect from
https://github.com/llvm/llvm-project/blob/main/mlir/lib/Dialect/SCF/IR/SCF.cpp
solves the Windows Debug issue with PR #1693 reported by @sstamenova 
=> simplified if lowering

src/Builder/FrontendDialectTransformer.cpp, test/mlir/onnx/parse/test_strnormalizer_export_monday_casesensintive_nochangecase.json
added a parse lit test that passes with this fix
=> parse string type from getTypeMap()

src/Builder/FrontendDialectHelper.cpp, src/Builder/FrontendDialectHelper.hpp, src/Builder/FrontendDialectTransformer.cpp, src/Builder/FrontendDialectTransformer.hpp, src/Compiler/CompilerUtils.cpp, src/onnx-mlir.cpp, test/modellib/ScanModel.cpp, test/onnx2mlir/CustomFnTest.cpp
=> cleanup some include files

src/Builder/FrontendDialectTransformer.cpp
This PR introduces a fix to remove the use of the types and local pointer variables causing errors in cppcheck. That was still a great implementation, but [experimentation got us to a workable solution](https://github.com/onnx/onnx-mlir/pull/1744) without the local pointer trouble. @sorenlassen @chentong319 if you could review, that'd be appreciated.
Signed-off-by: Brad Messer <messerb5467@gmail.com>
=> Streamline InferTypes in FrontendDialectTransformer.cpp

.azure-pipelines/Windows-CI.yml, .github/workflows/macos-amd64-build.yml, docker/Dockerfile.llvm-project, docker/Dockerfile.onnx-mlir, docker/Dockerfile.onnx-mlir-dev, src/Builder/FrontendDialectTransformer.cpp, src/Compiler/CompilerOptions.cpp, src/Compiler/CompilerPasses.cpp, src/onnx-mlir.cpp, utils/install-protobuf.sh
=> setup.py install is deprecated, use pip install instead

src/Dialect/ONNX/DialectBuilder.cpp
=> Fix OnnxBuilder::concat where axis was not used

src/Dialect/ONNX/ONNXOps.cpp
Signed-off-by: Philip Lassen <philiplassen+git@gmail.com>
=> normalize axis in ScatterElements verify

docs/TestingHighLevel.md
=> Update TestingHighLevel.md with common causes for protobuf related errors

src/Dialect/ONNX/CMakeLists.txt, src/Dialect/ONNX/ONNXOps.cpp, src/Dialect/ONNX/ShapeInference/GenericMatMul.cpp, src/Dialect/ONNX/ShapeInference/MatMul.cpp, src/Dialect/ONNX/ShapeInference/ONNXShapeHelper.cpp, src/Dialect/ONNX/ShapeInference/ONNXShapeHelper.hpp, test/mlir/onnx/onnx_shape_inference.mlir
Signed-off-by: Philip Lassen <philiplassen+git@gmail.com>
=> add MatMulInt shape inference

docs/Dialects/onnx.md
ran:
```
cmake --build . --target onnx-mlir-docs
```
=> updated onnx.md and krnl.md docs

src/Dialect/ONNX/ONNXOps.cpp, test/mlir/onnx/invalid.mlir, test/mlir/onnx/onnx_shape_inference.mlir
and simplified its inferShapes implementation
added lit tests
closes #1784
=> finished DequantizeLinear verify

.github/workflows/macos-amd64-build.yml, docker/Dockerfile.onnx-mlir, utils/install-protobuf.sh
- Use python 3.10 for MacOS build
- Add a docker build arg KEEPSRC for user image for debugging purpose
=> Try python 3.10 for MacOS build

src/Dialect/ONNX/ONNXOps/Quantize/QuantizeLinear.cpp, test/mlir/onnx/onnx_shape_inference.mlir
Fix QuantizeLinear shape inference in cases where type needs to be read from zero point attribute
=> Fix QuantizeLinear shape inference

src/Dialect/ONNX/ONNXOps/NN/Conv.cpp, test/mlir/onnx/onnx_shape_inference.mlir
Signed-off-by: Philip Lassen <plassen@groq.com>
=> Add more functionality to conv transpose shape inference

src/Conversion/ONNXToKrnl/Tensor/ConcatShapeTranspose.cpp, src/Transform/ONNX/Decompose.cpp, test/mlir/onnx/onnx_decompose.mlir
This PR performs special Op fusion: Concat+(Shape, Transpose) into ConcatShapeTranspose at the decompose-onnx step. This may not be perfect place for the fusion. But it works for the target model and I just do not want to write another pass just for this. The PR is a followup of PR#1817.
=> Fuse Concat Ops

src/Dialect/ONNX/ONNXOps/Math/Einsum.cpp, src/Dialect/ONNX/ONNXOps/Math/EinsumHelper.hpp, src/Transform/ONNX/DecomposeEinsum.cpp
added comment warning about this
=> fix reference-to-temporary einsum bug

.github/workflows/macos-amd64-build.yml
=> Fix MacOS build again

src/Dialect/ONNX/ONNXOps.hpp
Signed-off-by: Philip Lassen <plassen@groq.com>
=> Update supported opset to 16

src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.cpp, src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.hpp
=> remove unused ElementsAttrBuilder methods and functions

src/Conversion/ONNXToMhlo/CMakeLists.txt, src/Conversion/ONNXToMhlo/ConvertONNXToMhlo.cpp, src/Conversion/ONNXToMhlo/Math/Clip.cpp, src/Conversion/ONNXToMhlo/Math/Elementwise.cpp, src/Conversion/ONNXToMhlo/NN/ConvTranspose.cpp, src/Conversion/ONNXToMhlo/NN/Pooling.cpp, src/Conversion/ONNXToMhlo/ONNXToMhloCommon.hpp, src/Dialect/Mlir/DialectBuilder.cpp, src/Dialect/Mlir/DialectBuilder.hpp, src/Dialect/ONNX/ONNXOps.td.inc, src/Dialect/ONNX/ONNXOps/NN/Conv.cpp, src/Dialect/ONNX/ONNXOps/NN/NNHelper.cpp.inc, src/Dialect/ONNX/ONNXOps/ShapeHelper.hpp, src/Transform/ONNX/ConstProp.td, test/mlir/conversion/onnx_to_mhlo/Math/Clip.mlir, test/mlir/conversion/onnx_to_mhlo/Math/Elementwise.mlir, test/mlir/conversion/onnx_to_mhlo/NN/ConvTranspose.mlir, test/mlir/conversion/onnx_to_mhlo/NN/Pooling.mlir, test/mlir/onnx/onnx_shape_inference.mlir, utils/gen_onnx_mlir.py
This pull request:
Adds Mhlo lowering for `Clip`, `Log`, `Tanh`, `Max`, `LeakyRelu`, `ConvTranspose`, `AveragePool`
=> [Mhlo] More ops

src/Conversion/ONNXToKrnl/Tensor/NonZero.cpp, utils/RunONNXModel.py
=> Change -1 to ShapedType::kDynamic in NonZero

src/Conversion/ONNXToTOSA/DialectBuilder.cpp, src/Conversion/ONNXToTOSA/DialectBuilder.hpp, src/Conversion/ONNXToTOSA/NN/MaxPoolSingleOut.cpp, src/Conversion/ONNXToTOSA/ONNXToTOSALegalizeUtils.cpp, src/Conversion/ONNXToTOSA/ONNXToTOSALegalizeUtils.hpp, test/mlir/conversion/onnx_to_tosa/NN/MaxPoolSingleOut.mlir
As discussed in https://github.com/onnx/onnx-mlir/pull/1949#discussion_r1081693837 I wanted to bring in a `DialectBuilder` for the TOSA Dialect. We will gradually add more functionality.
Signed-off-by: Maximilian Bartel <maximilian.bartel@amd.com>
=> Add tosa builder

src/Compiler/CompilerUtils.cpp
No functions like to_chars and from_chars are used in code.
=> Remove charconv include

src/Dialect/Krnl/Krnl.td, src/Dialect/Krnl/KrnlOps.cpp
Similar to https://github.com/onnx/onnx-mlir/pull/1991. We need to update to the new signature to avoid warnings and deprecation.
=> [NFC] Switch krnl dialect the new fold method signature

docs/mnist_example/requirements.txt
Sweep was unhappy about unqualified requirement. Updated the docs/mnist_example requirement file to suggestion by @gongsu832
=> added min versions for torch as suggested by Gong

src/Dialect/ONNX/ONNXOps/ShapeHelper.cpp
Update terms to avoid use of "sanity" based on https://www.ibm.com/blogs/think/2020/08/words-matter-driving-thoughtful-change-toward-inclusive-language-in-technology/.
=> Terminology update

src/Conversion/ONNXToKrnl/Tensor/Pad.cpp, test/mlir/onnx/onnx_lowering_with_canonicalize.mlir, test/mlir/onnx/onnx_lowering_with_canonicalize_O3.mlir
This update fixes issue https://github.com/onnx/onnx-mlir/issues/1844 which is a compile error with ResNet50 model from Keras.
=> Fix issue compiling ResNet50 model from Keras

src/Conversion/ONNXToKrnl/Math/Elementwise.cpp, test/mlir/onnx/onnx_lowering_O3.mlir
Fix bug for SIMD found in #2070
=> fix for bug with SIMD

utils/analyze-simd.py
Created a python file that can analyze the asm for the presence of SIMD instructions. Can support multiple architecture, currently added the SIMD op patterns only for Z.
Usage:
```
analyze-simd [-a <arch>] (-c|-m|-o)+ [-n num] [-f pattern] [-dhlp] file
Utility to analyze and print SIMD code located in functions
Pattern:
-a | --arch <arch>: set op names to the given <arch>.
-c | --compute:  search for vector compute (add/mul) pattern.
-m | --mem:      search for vector vector memory pattern.
-o | --overhead: search for vector overhead pattern.
-f | --function pattern: investigate only functions whose name match
the pattern (default ".*main_graph").
-n | --num num:          investigate only that one occurrence num(default all)
(default all: -1).
-d | --details: print detailed op stats.
-p | …
```
=> Added support to analyze a binary/asm file for the presence of SIMD ops

src/Conversion/ONNXToKrnl/Math/Elementwise.cpp, test/modellib/ElementwiseModel.cpp, test/modellib/ModelLib.hpp, test/numerical/CMakeLists.txt, test/numerical/TestElementwise.cpp, test/perf/PerfElementwise.cpp, utils/analyze-simd.py
Adding numerical tests 
plus fix suggested by @sorenlassen about an unsafe debug printf.
=> Elementwise simd: adding numerical tests

.buildbot/jenkins-check-model-zoo.py, utils/RunONNXModelZoo.py
for more easily identifying the commit
=> Add commit message (first line only) to model zoo check history

src/Dialect/ONNX/ElementsAttr/BType.hpp, src/Dialect/ONNX/ElementsAttr/CMakeLists.txt, src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.cpp, src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.hpp, src/Dialect/ONNX/ElementsAttr/Strides.hpp, src/Dialect/ONNX/ElementsAttr/WideNum.hpp, src/Support/FloatingPoint16.hpp, src/Transform/ONNX/ConstProp.cpp, src/Transform/ONNX/ConstProp.td, test/mlir/onnx/onnx_constprop.mlir, test/unit/DisposableElementsAttr/TestDisposableElementsAttr.cpp, test/unit/FloatingPoint16/TestFloatingPoint16.cpp
Also added ElementsAttr equality comparison with a unit test. It is not used anywhere yet.
=> constant propagate add/sub zeros, mul/div ones

src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp, src/Dialect/ONNX/ONNX.td, src/Dialect/ONNX/ONNXOps/OpHelper.cpp, src/Dialect/ONNX/ONNXOps/OpHelper.hpp, src/Transform/ONNX/ConstProp.cpp, test/unit/Einsum/TestONNXEinsumOp.cpp
Addresses code review feedback from PR #2132.
Also changed createReplacingConstantOp() to use OnnxBuilder and return Value.
=> replace createONNXConstantOpWithDenseAttr with OnnxBuilder

src/Dialect/ONNX/Rewrite.cpp, src/Dialect/ONNX/Rewrite.td
=> Comment out unsound FuseCastCastPattern

src/Transform/ONNX/Decompose.cpp, src/Transform/ONNX/Decompose.td, test/mlir/onnx/onnx_decompose.mlir
Add decompose rule for ResizeV13
=> Resizev13 fix

docs/Docker.md, docs/docker-example/Dockerfile
I updated the docker instructions for those of us who are using the newer Macs with the M1 chip. Thank you @mikeessen for your help with this one and providing me with some commands to try :)
I just did this yesterday to set-up my new laptop....so I verified the steps too!
=> Update Docker instructions

docs/BuildOnLinuxOSX.md, docs/BuildOnWindows.md, src/Conversion/ONNXToTOSA/ONNXToTOSALegalizeUtils.hpp, src/Dialect/ONNX/AdditionalONNXOps.td, test/mlir/conversion/onnx_to_tosa/Math/Conv.mlir, test/mlir/conversion/onnx_to_tosa/Math/Elementwise.mlir, test/mlir/conversion/onnx_to_tosa/Math/Gemm_to_linear.mlir, test/mlir/conversion/onnx_to_tosa/Math/Gemm_to_matmul.mlir, test/mlir/conversion/onnx_to_tosa/Math/ReduceMean.mlir, test/mlir/conversion/onnx_to_tosa/Math/Softmax.mlir, test/mlir/conversion/onnx_to_tosa/NN/MaxPoolSingleOut.mlir, test/mlir/conversion/onnx_to_tosa/Tensor/Constant.mlir, test/mlir/conversion/onnx_to_tosa/Tensor/Reshape.mlir, test/mlir/onnx/onnx_seq_dealloc.mlir, utils/clone-mlir.sh
Bumps onnx-mlir to the latest green commit of 15 May 2023
Green LLVM commit: `095e6ac9fd92d03dcb1e19b60cb06a8140aae69d` (newer than commit `d421f5226048e4a5d88aab157d0f4d434c43f208`)
Green MHLO commit: `79a66f9d3169db39cf66d1be045280e02c3951f1`
=> Bump to LLVM green commit from 2023-05-15

docs/Dialects/krnl.md, docs/Dialects/onnx.md, docs/Dialects/zhigh.md, docs/Dialects/zlow.md
with the command `cmake --build . --target onnx-mlir-docs`
=> regenerated docs

src/Dialect/ONNX/ONNXOps.td.inc, src/Transform/ONNX/ConstProp.td, utils/gen_onnx_mlir.py
Add builders for `LessOrEqual` and `GreaterOrEqual`
=> Add builders for greaterOrEqual and LessOrEqual

docs/BuildOnLinuxOSX.md, docs/BuildOnWindows.md, utils/clone-mlir.sh
Also updates MHLO submodule to commit cd47c8c4.
=> build: update LLVM tag to ec89cb9a

src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp, src/Compiler/CompilerOptions.cpp, src/Compiler/CompilerOptions.hpp, src/Compiler/CompilerPasses.cpp, src/Pass/Passes.hpp, src/Transform/ONNX/ConstProp.cpp, src/Transform/ONNX/SimplifyShapeRelatedOps.cpp
They were tedious to maintain and we didn't use them
=> remove --onnx-const-prop-report and ConstPropCounters

src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.cpp, src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.hpp, src/Transform/ONNX/ConstProp.cpp, src/Transform/ONNX/ConstProp.td, test/mlir/onnx/onnx_constprop.mlir
only covers mode "constant" and when "axes" input is none
=> Pad const prop

src/Dialect/ONNX/ONNXOps/Tensor/Constant.cpp
I encountered 
```
loc("n0"): error: Require exactly one of the two attributes, either value or sparse_value
loc("n0"): error: 'onnx.Constant' op shape inference failed
loc("Constant_16"): error: Require exactly one of the two attributes, either value or sparse_value
loc("Constant_16"): error: 'onnx.Constant' op shape inference failed
```
when I compiled the model from issue #2298 with `onnx-mlir ~/onnx/maf_gpt2_tiny_display_name.onnx  -useOnnxModelTypes -EmitONNXIR`
with the change in this PR it compiles without errors
=> don't fail shape inference of unnormalized ONNXConstantOp

src/Transform/ONNX/InstrumentPass.cpp
fixes #2439 
Somehow `onnx.NoValue` causes a messy profiling output. Since `onnx.NoValue` returns a None value and does not affect performance, disable it when profiling.
=> Do not profile onnx.NoValue

src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
This patch is a complement to PR #2446 but for NNPA.
=> [NNPA] Call HybridTransformPass one more time to update shape if possible

src/Builder/FrontendDialectTransformer.cpp, test/mlir/onnx/parse/layer_normalization_function_decomposition.onnxtext
=> support optional outputs in function decomposition

utils/RunONNXModel.py, utils/analyze-simd.py
Added mesurement only on middle 2 quartile, default for simd analysis… with tags
=> Updates to RunONNXModel.py for quartile analysis, analyze-simd.py for default name with tags

src/Transform/ONNX/ConstProp.cpp, test/mlir/onnx/onnx_constprop.mlir
When the condition for IfOp is a constant, the IfOp can be replaced with either Then or Else branch.
=> constant fold for IfOp

src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
Cherry pick of https://github.com/onnx/onnx-mlir/pull/2583 to previous release
=> [NNPA] Call ScrubDisposablePass before ZHighConstPropagation (#2583)

docs/mnist_example/requirements.txt
This upgrade is required to fix DoS security vulnerability.
=> Upgrade Pillow to 10.2.0

docs/DevicePlacement-NNPA.md, src/Accelerators/NNPA/Compiler/NNPACompilerOptions.cpp
This PR corrects device placement option names in doc and help.
=> Correct device placement option names in doc and help

.gitignore, src/Conversion/ONNXToKrnl/Math/Reduction.cpp
1. Initialize estimatedSimdLoopTripCount in ONNXReductionOpLowering::matchAndRewrite.
2. Add .vs to .gitignore
=> Fix issues when develop with visual studio on windows

docs/AddCustomAccelerators.md
Fix incorrect documentation page for multiple accelerators.
See #2798
=> Fix docs for multiple accelerators

src/Dialect/ONNX/ONNXOps/OpHelper.cpp
I got the following error when compiling the gpt2 kv-cache model from HuggingFace:
```
loc("/transformer/Reshape_3"): error: failed to materialize conversion for result #0 of operation 'onnx.Reshape' that remained live after conversion
```
It's related to a canonicalization rule to replace the following Reshape:
```
%1410 = "onnx.Reshape"(%Y_69, %2) {allowzero = 0 : si64, device = "nnpa", onnx_node_name = "/transformer/Reshape_3"} : (tensor<?x?x768xf32>, tensor<3xi64>) -> tensor<?x1x768xf32>
```
`tensor<?x1x768xf32>` is replaced by `tensor<?x?x768xf32>` (because the 1st unknown dims are the same by using DimAnalysis, so the second dims are "we don't care") which caused the output type mismatched and then failed to materialize the output.
To fix that issue, this patch adds a condition to …
=> Mismatched output type when rewriting Reshape

src/Accelerators/NNPA/Runtime/OMRuntimeNNPA.c
This PR is a solution to the issue opened up here: https://github.com/onnx/onnx-mlir/issues/2808
=> Update error message for hardware compatibility

docs/BuildOnLinuxOSX.md, docs/BuildOnWindows.md, src/Dialect/Mlir/IndexExpr.cpp, src/Dialect/Mlir/IndexExprDetail.cpp, test/mlir/conversion/krnl_to_llvm/constants_to_file/big_endian/symbol-postfix.mlir, test/mlir/conversion/krnl_to_llvm/constants_to_file/litte_endian/symbol-postfix.mlir, test/mlir/conversion/krnl_to_llvm/entry_point.mlir, test/mlir/conversion/krnl_to_llvm/input_verification.mlir, test/mlir/conversion/krnl_to_llvm/krnl_random_normal_lowering.mlir, utils/clone-mlir.sh
Update LLVM and StableHLO commits.
LLVM commit: c012e487b7246239c31bd378ab074fb110631186
StableHLO commit:  dd48ec58d3bb8d674adf56715d4394102538fa84
=> Update LLVM to c012e487b724

docs/BuildOnLinuxOSX.md, docs/BuildOnWindows.md, src/Accelerators/NNPA/Dialect/ZLow/ZLowOps.cpp, src/Conversion/KrnlToLLVM/ConvertKrnlToLLVM.cpp, src/Dialect/Krnl/KrnlOps.cpp, src/Tools/onnx-mlir-opt/RegisterPasses.cpp, test/mlir/accelerators/nnpa/analysis/dyn-dim-analysis.mlir, test/mlir/conversion/krnl_to_llvm/constants_to_file/big_endian/symbol-postfix.mlir, test/mlir/conversion/krnl_to_llvm/constants_to_file/litte_endian/symbol-postfix.mlir, test/mlir/conversion/krnl_to_llvm/entry_point.mlir, test/mlir/conversion/krnl_to_llvm/input_verification.mlir, test/mlir/conversion/onnx_to_stablehlo/Tensor/Reshape.mlir, test/mlir/onnx/onnx_dim_analysis.mlir, utils/clone-mlir.sh
Update LLVM and StableHLO commits.
LLVM commit: c07be08df5731dac0b36e029a0dd03ccb099deea
StableHLO commit: 61826746d640f6342856af5ac71dabe6fbf37ff5
=> Update llvm to c07be08df573

src/Dialect/ONNX/Transforms/ConstProp.cpp, src/Dialect/ONNX/Transforms/ConstProp.td, test/mlir/onnx/onnx_constprop.mlir
Constant propagation for Reciprocal
=> Constant propagation for Reciprocal

docs/BuildOnLinuxOSX.md, docs/BuildOnWindows.md, utils/clone-mlir.sh
Upgrading `LLVM` commit to `6461b921fd06b1c812f1172685b8b7edc0608af7` and `StableHLO` commit to `1b08c4c0e8c893d202bd33c2735562fa0ccc849f`
=> Upgrade LLVM/StableHLO

src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp, src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.hpp, src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.cpp
This PR adds the input NNPA level to the onnxToZHighInCompatibilityReport method.
=> Update --opt-report=NNPAUnsupportedOps for NNPA

docs/BuildOnLinuxOSX.md, docs/BuildOnWindows.md, test/mlir/conversion/onnx_to_stablehlo/Math/Elementwise.mlir, test/mlir/conversion/onnx_to_stablehlo/RNN/LSTM-loop.mlir, test/mlir/conversion/onnx_to_stablehlo/Tensor/ArgMax.mlir, test/mlir/conversion/onnx_to_stablehlo/Tensor/Gather.mlir, test/mlir/conversion/onnx_to_stablehlo/Tensor/GatherElements.mlir, test/mlir/conversion/onnx_to_stablehlo/Tensor/OneHot.mlir, test/mlir/conversion/onnx_to_stablehlo/Tensor/Slice.mlir, utils/clone-mlir.sh
This PR bumps LLVM to 0913547d0e3 and stablehlo to c28d55e91b4a
=> Bump LLVM to 0913547d0e3939cc420e88ecd037240f33736820

src/Accelerators/NNPA/Conversion/ZHighToZLow/ZHighToZLow.cpp, src/Runtime/OMResize.inc
This PR updates code to check the result of memory allocation for stickified data.
=> Check result of memory allocation for stickified data

src/Runtime/OMIndexLookup.inc, src/Runtime/OMInstrument.inc, src/Runtime/jni/jnilog.c, src/Runtime/jni/jnilog.h, src/Runtime/jni/jniwrapper.c
Update code to add assert statements for  snprintf, sprintf, and vsnprintf
=> Add asserts for snprintf, sprintf, and vsnprintf

docs/BuildOnLinuxOSX.md, docs/BuildOnWindows.md, src/Conversion/ONNXToStablehlo/Math/MatMul.cpp, test/mlir/conversion/krnl_to_llvm/constants_to_file/big_endian/constants.mlir, test/mlir/conversion/krnl_to_llvm/constants_to_file/big_endian/symbol-postfix.mlir, test/mlir/conversion/krnl_to_llvm/constants_to_file/litte_endian/constants.mlir, test/mlir/conversion/krnl_to_llvm/constants_to_file/litte_endian/symbol-postfix.mlir, test/mlir/conversion/onnx_to_krnl/ControlFlow/lit.local.cfg, test/mlir/conversion/onnx_to_krnl/Tensor/onnx_lowering_depth_to_space_op.mlir, test/mlir/conversion/onnx_to_krnl/Tensor/onnx_lowering_space_to_depth.mlir, test/mlir/lit.cfg.py, utils/clone-mlir.sh
Upstream update
LLVM : f142f8afe21bceb00fb495468aa0b5043e98c419
StableHLO: 54aa1a57178251981da616b877dda1a88d840d11
=> Update llvm-project to llvm/llvm-project@f142f8afe21b

docs/doc_example/main.c
This PR updates the code to check the result of memory allocation for input data tensors in doc example.
=> Add check for malloc to prevent NULL pointer dereference in docs example.

docs/BuildOnLinuxOSX.md, docs/BuildOnWindows.md, utils/clone-mlir.sh
LLVM: `eaa95a1c2bd38332c1a4e634595f29d22b28ffea`
StableHLO: `e51fd95e5b2c28861f22dc9d609fb2a7f002124e`
=>  Update llvm-project to llvm/llvm-project@eaa95a1c2bd3 

test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/gru.mlir
Simple PR: a lit test case for GRU with length input.
=> Add a test case for GRU

docs/BuildOnLinuxOSX.md, docs/BuildOnWindows.md, test/mlir/accelerators/nnpa/transform/zlow-stick-unstick-expansion.mlir, test/mlir/conversion/onnx_to_krnl/ControlFlow/Loop.mlir, test/mlir/conversion/onnx_to_krnl/NN/Normalization_O3_SIMD_canonicalize.mlir, test/mlir/conversion/onnx_to_krnl/Tensor/onnx_lowering_depth_to_space_op.mlir, test/mlir/conversion/onnx_to_krnl/Tensor/onnx_lowering_space_to_depth.mlir, utils/clone-mlir.sh
Bump llvm to 29b92d07746fac26cd64c914bc9c5c3833974f6d and Stablehlo to 9d9290dc2308c1850cea69ea05f8c94017e484ee
=> Bump llvm to 29b92d07746fac26cd64c914bc9c5c3833974f6d

src/Dialect/Mlir/VectorMachineSupport.cpp, src/Runtime/OMSort.inc
This PR changes a c style cast to c++ style, and also removes not needed parens.
=> Add c++ style cast and remove not needed parens

docs/BuildOnLinuxOSX.md, docs/BuildOnWindows.md, src/Conversion/ONNXToTOSA/ONNXToTOSACommon.hpp, src/Conversion/ONNXToTOSA/ONNXToTOSALegalizeUtils.hpp, utils/clone-mlir.sh
This PR updates the LLVM commit and StableHLO submodule.
LLVM = 00128a20eec27246719d73ba427bf821883b00b4
MHLO = 8dd667a74ea1a7330390a0ba343d7c4c6f2d834d
=> Update LLVM to 00128a20eec27246719d73ba427bf821883b00b4

docs/mnist_example/requirements.txt
Fix security vulnerabilities in requirements.txt for mnist example 
- https://github.com/advisories/GHSA-44wm-f244-xhp3 for pillow
- https://github.com/advisories/GHSA-9v5x-r4g7-gqw3 torch package
- https://github.com/advisories/GHSA-vmg3-jxcp-7rqw  for torch package
- https://github.com/advisories/GHSA-pg7h-5qx3-wjr3  for torch package
- https://github.com/advisories/GHSA-5pcm-hx3q-hm94 for torch package
- Update torchvision package to match torch version.
=> Fix security vulenrabilities

docs/Dialects/onnx.md, src/Dialect/ONNX/ONNXOps.td.inc, src/Dialect/ONNX/ONNXOps/Math/RandomNormal.cpp, src/Dialect/ONNX/ONNXOps/Math/RandomNormalLike.cpp, test/mlir/conversion/onnx_to_krnl/Math/RamdomNormal.mlir, test/mlir/conversion/onnx_to_krnl/Math/RamdomNormalLike.mlir, test/mlir/onnx/onnx_shape_inference.mlir, test/mlir/onnx/parse/random_normal_like_dtype_bf16.onnxtext, test/mlir/onnx/parse/random_normal_like_dtype_f32.onnxtext, test/mlir/onnx/parse/random_normal_like_no_dtype.onnxtext, utils/gen_onnx_mlir.py
=> Add result type inference to RandomNormalLike and fix wrong hardcodings for dtypes

docs/Quantization-NNPA.md, docs/SupportedONNXOps-NNPA-supplement.md, docs/SupportedONNXOps-NNPA.md, docs/SupportedOps-NNPA-supplement.md, src/Accelerators/NNPA/CMakeLists.txt, src/Accelerators/NNPA/Runtime/zDNNExtension/Elementwise.c, src/Accelerators/NNPA/Support/NNPALimit.cpp, src/Accelerators/NNPA/Transform/ZHigh/ZHighConstPropagation.cpp, src/Compiler/CompilerOptions.cpp, test/accelerators/NNPA/backend/CMakeLists.txt, utils/documentOps.py
Pull in the below fix and updates for z17/NNPA in 0.5.0.0 release branch
1. https://github.com/onnx/onnx-mlir/pull/3112 
2. https://github.com/onnx/onnx-mlir/pull/3113 
3. https://github.com/onnx/onnx-mlir/pull/3130 
4. https://github.com/onnx/onnx-mlir/pull/3120
=> Cherry pick updates from main for z17 and fix for ZHighConstantPropagation in QunarizedStick

docs/mnist_example/requirements.txt
https://github.com/onnx/onnx-mlir/pull/3135
=> [cherry-pick]fix CVE-2025-32434 (#3135)

test/mlir/conversion/onnx_to_krnl/Math/RamdomNormal.mlir, test/mlir/conversion/onnx_to_krnl/Math/RamdomNormalLike.mlir
I missed this in https://github.com/onnx/onnx-mlir/pull/3091
=> Fix types in RandomNormal(Like) test inputs to match the dtype

src/Dialect/ONNX/ONNXOps/Canonicalize.cpp, test/mlir/onnx/onnx_canonicalization_locations.mlir
Having accurate locations is helpful for tracing and debugging the compilation flow
Downstream we make extensive use of them
@Arkar-Hema  FYI
=> Fuse locations when merging concats

src/Dialect/Krnl/Krnl.td, src/Dialect/Krnl/KrnlOps.cpp
Fix issue #3171 .
The InstrumentOp has side effects on writing to external device, the I/O stream.
With this PR, `Debug/bin/onnx-mlir --profile-ir=Onnx test_add.onnx` passed.
=> Add MemoryEffortsOpInterface to krnl.InstrumentOp

src/Conversion/ONNXToKrnl/Tensor/Concat.cpp
Currently the krnl code for Concat only supports parallelism over the outermost dimension, which is not good for Concat of KV cache in decoder models whose the 1st dimension is 1 (batchsize = 1). A good thing is that these KV cache Concat has the 2nd dimension of value of 8 or more. So, this patch explores the 2nd dimension for parallelism also.
=> Explore the first two outermost dimensions for parallelism for Concat

utils/RunONNXModel.py
When we want to profile a model, we compile the model with option `--profile-ir` and then use the environment variable `ONNX_MLIR_INSTRUMENT_FILE` to store runtime profiling info to a file. However, it's quite difficult to remember the env name.
This patch adds an option `--write-runtime-log` into `RunONNXModel.py` that internally sets a value for `ONNX_MLIR_INSTRUMENT_FILE`.
To make the options complete, this patch also changes the old option `--log-to-file` to `--write-compile-log` that is used to output compilation info to a file.
=> [RunONNXModel.py] Add an option to store profiling info to a file

src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp, src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp, src/Conversion/ONNXToKrnl/Tensor/Slice.cpp, test/mlir/conversion/onnx_to_krnl/Tensor/Slice_with_parallel_canonicalize_O3.mlir
This patch generates parallel code for onnx.Slice.
=> Generate parallel code for onnx.Slice

utils/RunONNXModel.py
The error is caused the missing `import onnx`. I tested RunONNXModelZoo.py.
=> Fix the bug in new RunONNXModel.py

docs/mnist_example/requirements.txt
=> fix pytorch CVE
