- doc/gen_doc.py
- src/CMakeLists.txt
- src/dialect/onnx/onnxop.inc
- src/main.cpp
- src/pass/onnx_decompose.cpp
- src/pass/onnx_decompose.td
- src/pass/onnx_rewrite.cpp
- src/pass/onnx_rewrite.td
- src/pass/passes.hpp
- test/mlir/onnx/onnx_canonicalization.mlir
- test/mlir/onnx/onnx_decompose.mlir
This patch is to:
- Add a new pass which is to decompose ONNX operations into smaller ONNX operations, and
- Move rewriting rules in canonicalization for Reduction ops into the new pass.
The new pass is called before shape inference, so it is used to decompose ops without the need of implementing shape inference for these ops.
> Add a pass to decompose ONNX operations into smaller ONNX operations

- src/conversion/onnx_to_krnl/math/elementwise.cpp
- src/conversion/onnx_to_krnl/math/gemm.cpp
- src/conversion/onnx_to_krnl/math/matmul.cpp
- src/conversion/onnx_to_krnl/math/reduction.cpp
- src/conversion/onnx_to_krnl/math/softmax.cpp
- src/conversion/onnx_to_krnl/nn/conv.cpp
- src/conversion/onnx_to_krnl/nn/pooling.cpp
- src/conversion/onnx_to_krnl/onnx_to_krnl_common.cpp
- src/conversion/onnx_to_krnl/onnx_to_krnl_common.hpp
- src/conversion/onnx_to_krnl/tensor/reshape.cpp
- src/conversion/onnx_to_krnl/tensor/unsqueeze.cpp
In the current source code, when creating constants we see hard wiring for float. This patch is to create some helper functions, which allows creating constants with a given type.
> Create some helper functions to emit constant op for a specific type

- .gitmodules
Git protocol does not work as good as https when used with http/https proxy.
> Change variant repo from git to https.

- src/pass/shape_inference_pass.cpp
Inferring shapes of operations within a function can be performed in one pass. Switch to a data structure that does not limit the number of operations that we can shape inference on.
> Enable inference for arbitrary number of instructions

- src/CMakeLists.txt
- src/conversion/onnx_to_krnl/convert_onnx_to_krnl.cpp
- src/conversion/onnx_to_krnl/onnx_to_krnl_common.hpp
- src/conversion/onnx_to_krnl/tensor/padconstantvaluepad.cpp
- test/mlir/onnx/onnx_lowering.mlir
Reimplementation of PR#3.
Fixed the last two comments in PR#3 by @tungld:
1. output type can be tensor and memref
2. the interpretation of constants in pad
> Lower constant padding operation to KRNL dialect

- doc/gen_doc.py
- src/dialect/onnx/onnx_ops.cpp
- src/dialect/onnx/onnxop.inc
- src/pass/shape_inference_pass.cpp
- test/mlir/onnx/onnx_shape_inference.mlir
This patch 
- implements shape inference for ONNXAveragePool. 
- creates common functions for Conv, MaxPool, and AveragePool. 
Common functions `processConvDilationParam`, `processConvStrideParam` and `processConvPadParam` are extracted from `processConvPadParam` without code changes. Hence, `processConvPadParam` now calls these common functions. The reason for extracting new common functions is that AveragePool does not have dilations, so we can not use `processConvPadParam` directly.
Common function `insertConvSpatialDim` is newly added to compute output spatial dimensions given strides, pads, dilations (optional) and ceilmode (optional), which works for Conv, MaxPool and AveragePool.
> Shape inference for ONNXAveragePool

- src/dialect/onnx/onnx_ops.cpp
- test/mlir/onnx/onnx_canonicalization.mlir
- test/mlir/onnx/onnx_shape_inference.mlir
fix
1. unknown dimension
2. semantics of pad for shape inference
Updated test case for canonical form. I assume the rewriter generates the correct pad value and changed the expected output dimension. Please verify.
> Fix issues #15 and #16

- src/dialect/onnx/onnx_ops.cpp
- test/mlir/onnx/onnx_shape_inference.mlir
This patch fixes the case where exactly one of the entries in the second argument of the Reshape operation is dynamic.
> Fix reshape output shape inference when a single dynamic shape is given

- src/builder/frontend_dialect_helper.cpp
- src/builder/frontend_dialect_transformer.cpp
- src/dialect/onnx/onnx_ops.cpp
- test/backend/test.py
- test/mlir/onnx/onnx_shape_inference.mlir
This patch is to:
- Fix value attribute format for ConstantOp by using dense tensor,
- Import all initialized tensors as dense constants
By this patch, I successfully ran MNIST model (which was obtained from: https://github.com/onnx/models/tree/master/vision/classification/mnist)
Python script (Implementation of DummyBackend is not shown here):
```python
import onnx
from onnx import numpy_helper
import numpy as np
test_data_dir = '/home/tungld/dl/dlc-misc/mnist/'
model = onnx.load(test_data_dir + 'model.onnx')
inputs = []
input_file = test_data_dir + 'test_data_set_0/input_0.pb'
tensor = onnx.TensorProto()
with open(input_file, 'rb') as f:
tensor.ParseFromString(f.read())
inputs.append(numpy_helper.to_array(tensor))
outputs = DummyBackend.run_model(model, inputs)
print("Predicted output: …
```
> Import all initialized tensors as dense constants

- src/Builder/FrontendDialectHelper.cpp
When importing [Resnet50]( https://github.com/onnx/models/tree/master/vision/classification/resnet/resnet50), I got segmentation fault at the point where a conv's weight of around 2M elements was imported. All weights before that point have size of < 1M, and they were imported successfully. 
It seems that `createArrayAttribute` function returns a pointer to a local vector that is not available outside of the function. This patch is to fix such an issue.
> Fix a bug in createArrayAttribute

- .buildbot/p9.sh
- .circleci/config.yml
- README.md
- test/backend/CMakeLists.txt
- test/mlir/CMakeLists.txt
- utils/install-onnx-mlir.sh
Minor updates, but I got tiered to use 
check-mlir-lit  or run-onnx-backend-test
with very different names. Normalized both to be
check-onnx-lit or check-onnx-backend
> name change for tests, to be check-onnx-(lit | backend)

- utils/CMakeLists.txt
After the PR #58 , I ran into an error in make if I run "make clean" first. The reason is that the .inc files in src are removed because they are intermediate result to Cmake now. 
Simple change is not to expose them as intermediate result.
> Keep the .inc files generated with script (gen_doc.py)

- docs/_layouts/default.html
Links on documentation are broken (see onnx.ai/onnx-mlir).
This is because our documentation is published to a subdirectory under onnx.ai.
> Fix documentation path issue.

- test/mlir/krnl/constant.mlir
- test/mlir/krnl/ops.mlir
- test/mlir/krnl/reshape.mlir
- test/mlir/onnx/onnx_canonicalization.mlir
- test/mlir/onnx/onnx_decompose.mlir
- test/mlir/onnx/onnx_lowering.mlir
- test/mlir/onnx/onnx_lowering_with_dealloc.mlir
- test/mlir/onnx/onnx_shape_inference.mlir
- test/mlir/onnx/onnx_shape_inference_maxpool.mlir
`-split-input-file` flag in `mlir-opt` uses `// -----`  to split a MLIR test file into independent tests: https://github.com/llvm/llvm-project/blob/master/mlir/docs/Tutorials/QuickstartRewrites.md#testing
This patch inserts `// -----` into test files to make them work with the `-split-input-file` flag.
> Add the split marker to test files

- MLIR.cmake
- src/Conversion/ONNXToKrnl/NN/Pooling.cpp
- src/Dialect/Krnl/KrnlHelper.cpp
- src/Dialect/Krnl/KrnlHelper.hpp
- src/Dialect/ONNX/ONNXOps.td
- src/Runtime/CMakeLists.txt
- src/Transform/ONNX/ONNXRewrite.cpp
- src/Transform/ONNX/ONNXRewrite.td
- test/backend/CMakeLists.txt
- test/backend/test.py
- test/mlir/krnl/constant.mlir
- test/mlir/krnl/ops.mlir
- test/mlir/krnl/reshape.mlir
- test/mlir/onnx/onnx_canonicalization.mlir
- test/mlir/onnx/onnx_decompose.mlir
- test/mlir/onnx/onnx_lowering.mlir
- test/mlir/onnx/onnx_lowering_with_dealloc.mlir
- test/mlir/onnx/onnx_shape_inference.mlir
- test/mlir/onnx/onnx_shape_inference_maxpool.mlir
This patch is to implement common functions for lowering pooling ops where:
- It supports padding directly in the lowering, thus there is no need to pad the input separately.
- Remove this rewriting rule: `MaxPoolSingleOut(X, pads) = MaxPoolSinglePut(onnx.PadConstantValuePadOp(X,pads), pads = [0, 0, 0, 0])`
- It uses AffineMap to compute a pooling window for border edges instead of using a fixed pooling window of kernel size.
- Helper function `pushAffineBound(AffineMap map, ArrayRef<Value> operands)` is newly added to help add an AffineMap as a bound for KrnlIterateOp.
TODO:
> Lower MaxPooling and AveragePool to Krnl dialect using AffineMap

- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- test/mlir/onnx/onnx_lowering.mlir
Resolves #65.
With this patch, we are able to lower the following code:
```mlir
func @main() -> tensor<*xf32> {
%0 = "onnx.Constant"() {value =  dense<[[1.000000e+00, 2.000000e+00, 3.000000e+00], [4.000000e+00, 5.000000e+00, 6.000000e+00]]> : tensor<2x3xf32>} : () -> tensor<*xf32>
"std.return"(%0) : (tensor<*xf32>) -> ()
}
````
`onnx-mlir-opt --shape-inference  --lower-frontend test-constant.mlir ` yields:
```mlir
module {
func @main() -> memref<2x3xf32> {
%0 = "krnl.global"() {name = "constant_0", shape = [2, 3], value = dense<[[1.000000e+00, 2.000000e+00, 3.000000e+00], [4.000000e+00, 5.000000e+00, 6.000000e+00]]> : tensor<2x3xf32>} : () -> memref<2x3xf32>
return %0 : memref<2x3xf32>
}
}
````
> Fix converting type for functions with no argument

- src/MainUtils.cpp
Refer to issue: https://github.com/onnx/onnx-mlir/issues/112
Saving the concatenation to a local variable should prevent `.c_str()` from getting invalid memory.
> Fix garbled filename output

- README.md
- docs/README.md
- src/Conversion/ONNXToKrnl/NN/Pooling.cpp
- src/MainUtils.cpp
- utils/install-onnx-mlir.cmd
- utils/setup-onnx-mlir-windows.cmd
- Use "&&" instead of "and" for Windows C++ Compiler
- Update Windows-CI badge from my account to onnx account
- Simulate fork() on Windows: redirect the stderr to files and then redirect back
My implementation makes stderr as: 
(before) A
temp.onnx.mlir -> B
temp.mlir -> C
(after) D
Final stderr -> A, D
Not sure whether this implementation breaks the original logic. Please carefully review it. Thank you.
> Enable Build on Windows again and Update CI badge 

- .circleci/config.yml
- MLIR.cmake
- README.md
- docs/README.md
- src/Builder/FrontendDialectHelper.hpp
- src/Dialect/Krnl/KrnlOps.cpp
- src/Dialect/Krnl/KrnlOps.td
- src/Dialect/MLONNX/MLONNXOps.td
- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXOps.td
- src/Dialect/ONNX/ONNXOps.td.inc
- src/MainUtils.cpp
- src/MainUtils.hpp
- src/Tool/ONNXMLIROpt/ONNXMLIROpt.cpp
- src/Transform/LowerToLLVM.cpp
- utils/clone-mlir.sh
- utils/gen_doc.py
The new LLVM commit ID contains some important changes:
- The use of `Builder` is changed to `OpBuilder` in op build methods.
- AffineScope trait which is to define a new scope for polyhedral optimization purposes. I will enable this feature in onnx-mlir for loop-fusion once this patch is landed.
> Move to more recent LLVM commit ID

- docs/ImportONNXDefs.md
- src/Builder/OpBuildTable.inc.dc
- src/Dialect/ONNX/ONNXOps.td.inc.dc
- utils/CMakeLists.txt
- utils/gen_doc.py
- utils/gen_onnx_mlir.py
This patch is intended to handle the change of ONNX specification. The current latest version of operations are saved as a dictionary in the script. The generation for onnx-mlir Tablegen will choose that version even if ONNX package is upgraded. 
To move forward to the latest version of onnx installed in your system, run the script with --generate-for-latest-version.  In addition to using the latest version for Tablegen, the change in version, compared to the saved version, is reported and the new version dictionary is generated on standard output.
> save and check the version of ONNX operation

- .gitmodules
- docs/DebuggingNumericalError.md
- docs/_data/navigation.yml
- src/MainUtils.cpp
- src/Transform/LowerToLLVM.cpp
- utils/debug.py
Use `util/debug.py` python script to debug numerical errors, when onnx-mlir-compiled inference executable produces 
numerical results that are inconsistent with those produced by the training framework.
This python script will run the model through onnx-mlir and a reference backend, and compare
the intermediate results produced by these two backends layer by layer.
- Set `ONNX_MLIR_HOME` environment variable to be the path to
the HOME directory for onnx-mlir. The HOME directory for onnx-mlir refers to 
the parent folder containing the `bin`, `lib`, etc sub-folders in which ONNX-MLIR 
executables and libraries can be found.
- Install an ONNX backend, by default onnx-runtime is used as testing backend. Install by 
running `pip install onnxruntime`. To use a different testing backend, simply …
> Support model debugging

- .travis.yml
- docker/Dockerfile
- docker/compile-onnx-mlir.sh
Previously the build always built the latest commit on the master branch, even for a PR. Now it builds the merge for a PR. Also, for pushes to the master branch it now saves the resulting docker image in docker hub, so we can grab that image and use it when developing new tests etc.
> Fix travis build

- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Conversion/ONNXToKrnl/Math/MatMul.cpp
- src/Dialect/Krnl/KrnlOps.hpp
- src/Dialect/ONNX/ONNXOps.cpp
- src/Interface/ShapeInferenceInterface.td
- src/Transform/ONNX/ShapeInferencePass.cpp
fixed warnings in our onnx-mlir code; there are still some from deprecated calls in protobuf
also added proper "return false" when any errors are detected in shape inference, which was not systematically done, and made sure also that we emit an error whenever we return false.
> Error fix3

- src/Builder/FrontendDialectTransformer.cpp
While working on SplitOp, I found that it failed to import variadic output. This patch is to fix such an issue.
> Fix importing variadic output

- src/Conversion/ONNXToKrnl/NN/Conv.cpp
- test/mlir/onnx/onnx_lowering.mlir
thanks Tian for narrowing it down to the bias, which was multiplied instead of added. This really speaks favorably for your more extensive testing, as the backend tests worked
> conv bug fix

- src/Builder/FrontendDialectTransformer.cpp
- src/CMakeLists.txt
- src/Conversion/ONNXToKrnl/CMakeLists.txt
- src/Dialect/ONNX/CMakeLists.txt
- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXOps.hpp
- src/Dialect/ONNX/ONNXOps.td.inc
- src/Dialect/ONNX/ONNXOpsHelper.cpp
- src/Dialect/ONNX/ONNXOpsHelper.hpp
- src/Transform/CMakeLists.txt
- src/Transform/ONNX/CMakeLists.txt
- utils/gen_onnx_mlir.py
This patch is to add a custom type inference for CastOp since the result type of CastOp is specified by one of its attributes, not its inputs.
> Add type inference for CastOp

- src/Conversion/ONNXToKrnl/Tensor/Transpose.cpp
- src/Dialect/ONNX/ONNXOps.cpp
- src/Transform/ONNX/ConstProp.cpp
- src/Transform/ONNX/ConstProp.td
- test/mlir/onnx/onnx_constprop.mlir
- test/mlir/onnx/onnx_shape_inference.mlir
Added constant folding for for transpose of constant tensors.
Also made the optional transpose attribute (which is the normal math transpose) explicit, that is, the permute attribute (a vector of int) is now defined in all cases, so that we don't have to check "if defined, use explicit, otherwise use default" in the rest of the code. Changed lowering to Kernel accordingly
> constant folding for transpose of constant tensors

- MLIR.cmake
- src/CMakeLists.txt
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/InitOMPasses.hpp
- src/Tool/ONNXMLIROpt/CMakeLists.txt
- src/Tool/ONNXMLIROpt/ONNXMLIROpt.cpp
- src/Transform/ElideKrnlGlobalConstants.cpp
- src/Transform/EnableMemoryPool.cpp
- src/Transform/LowerKrnl.cpp
- src/Transform/LowerToLLVM.cpp
- src/Transform/ONNX/AttributePromotion.cpp
- src/Transform/ONNX/ConstProp.cpp
- src/Transform/ONNX/Decompose.cpp
- src/Transform/ONNX/ElideConstants.cpp
- src/Transform/ONNX/ShapeInferencePass.cpp
- test/mlir/lit.site.cfg.py.in
- test/numerical/CMakeLists.txt
Change all implicit self-registering transformation passes to use explicit registration. This follows from changes in the upstream mlir. It allows us to remove all whole-archive linking related build scripts.
> Remove whole archive linkage

- src/Builder/FrontendDialectTransformer.cpp
`constant unit` is used for optional inputs.
This patch is to create `constant unit` ops for optional inputs only when we are importing ops with optional inputs. Hence, it avoids creating dangling `constant unit` ops in the other cases.
> Remove dangling constant ops when importing non-optional-input ops.

- src/Builder/FrontendDialectTransformer.cpp
This patch is to import optional inputs sandwiched between two others inputs. These optional inputs are represented as empty strings in ONNX models.
e.g. This patch is to import the 5-th input in this LSTM op correctly:
```mlir
%Y, %Y_h, %Y_c = "onnx.LSTM"(%0, %1, %2, %3, %cst, %4, %5, %cst) {hidden_size = 200 : i64} : (tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, none, tensor<*xf32>, tensor<*xf32>, none) -> (tensor<*xf32>, tensor<*xf32>, tensor<*xf32>)
```
Without this fix, the 5-th input will be bypassed, and output will be wrong like this:
```mlir
%Y, %Y_h, %Y_c = "onnx.LSTM"(%0, %1, %2, %3, %4, %5, %cst,  %cst) {hidden_size = 200 : i64} : (tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, tensor<*xf32>, none, none) -> (tensor<*xf32>, …
```
> Fix importing optional inputs

- docs/Dialects/onnx.md
- src/Dialect/ONNX/ONNXOps.td.inc
- utils/gen_onnx_mlir.py
One previous change accidentally removed AnyMemRef from ONNXOps.td.inc. This patch just added it back.
> add AnyMemRef

- src/Runtime/jni/jniwrapper.c
On macOS, `<stdlib.h>` contains malloc. So `<stdlib.h>` should be included instead of `<malloc.h>`.
In this PR, I added `#ifdef` to switch include header.
> include stdlib.h when compiling on macOS

- README.md
- docs/docker-example/Dockerfile
tag of build image was changed by PR #268 from amd64 to x86 --- fix here to pick up latest build
> change tag to x86

- README.md
This is to make mlir code in README easy to read.
> Syntax highlighting for mlir code in README

- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXOps.td.inc
- src/Transform/ONNX/Rewrite.cpp
- src/Transform/ONNX/Rewrite.td
- test/mlir/onnx/onnx_canonicalization.mlir
- utils/gen_onnx_mlir.py
When the input tensor of Shape and Size Op is ShapedTensor,  rewrite them with its constant output.
> Rewrite shape and size OP 

- .travis.yml
There is some problem with the Travis server for ppc64le, so until it gets fixed, we should allow ppc64le builds to fail
> temporarily allow ppc64le build to fail

- src/Conversion/ONNXToKrnl/CMakeLists.txt
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Conversion/ONNXToKrnl/Tensor/Size.cpp
- test/backend/test.py
- test/mlir/onnx/onnx_lowering.mlir
Added ONNXSizeOp conversion from ONNX dialect to Krnl dialect. This op is added as a part of --convert-onnx-to-krnl pass.
Signed-off-by: Prashant Kumar <pk5561@gmail.com>
> [MLIR] Add SizeOp conversion from ONNX dialect to Krnl dialect

- .travis.yml
- docker/prereq.ppc64le.Dockerfile
ppc64le non-nightly build restored.
> Use ubuntu focal as ppc64le base image.

- src/Builder/FrontendDialectTransformer.cpp
- src/Transform/ONNX/ShapeInferencePass.cpp
- test/mlir/onnx/onnx_lowering.mlir
The graph output shape/elem_type is discarded when translating from protobuf to mlir. It is harmful to round-trip.
I renamed and polished the function `ImportInputTensorType` and applied it to graph outputs.
> Import graph output type from protobuf

- src/Dialect/Krnl/KrnlOps.td
- test/mlir/krnl/krnl_normalization.mlir
This PR enable us to normalize memrefs with affine_map in a function containing `krnl.getref` .
Without this PR, memrefs in this test case are not normalized because krnl.memcpy is not normalizable operation.
To have krnl.getref normalizable, this PR adds a trait of MemRefsNormalizable.
This PR should have been included in https://github.com/onnx/onnx-mlir/pull/322
Reference: https://reviews.llvm.org/D86236
> Normalize memrefs with affine_map in a function containing krnl.getref

- .circleci/config.yml
- MLIR.cmake
- README.md
- docs/README.md
- src/Transform/ONNX/ConstProp.cpp
- src/Transform/ONNX/Decompose.cpp
- utils/clone-mlir.sh
Updated llvm commit to b3b4cda (This PR replace #343.  Newer commit is used.)
This PR includes fix to reflect following update in MLIR.
- Remove Ops suffix from dialect library names: llvm/llvm-project@d4e889f
- API change of  `OwningRewritePatternList`. (`OwningRewritePatternList * -> OwningRewritePatternList &`): llvm/llvm-project@422aaf3
(I created this PR to use latest --normalize-memrefs.)
> Updated llvm commit to b3b4cda (Replacement of #343)

- .travis.yml
- docs/_config.yml
- docs/_data/navigation.yml
Generate doxygen documentation html pages and deploy the content to gh-pages branch. The onnx-mlir documentation web page will point to content/files in the gh-pages branch.
To see the effect of this patch, view:
http://onnx.ai/onnx-mlir/
> Gen doc using travis.

- test/mlir/krnl/krnl_shape_lowering.mlir
> Add a lit test for krnl shape lowering when its input is a MemRef with affine_map

- README.md
- src/main.cpp
The PR has couple of fixes for documentation
1. Add a space between without and inferred so it read correctly
2. Update instructions in README to reflect the latest options
Signed-off-by: Chin Huang <chhuang@us.ibm.com>
> Minor documentation fix for frontend options

- src/Builder/FrontendDialectTransformer.cpp
Pass ONNX model via const-reference to avoid unnecessary copy of model when importing the model.
> Avoid model copy during import

- docs/Testing.md
- src/Builder/FrontendDialectTransformer.cpp
- test/backend/test.py
Signed-off-by: chentong <chentong@us.ibm.com>
Our importer can change static shaped tensor for input parameters into dynamic shaped tensor when the env variable IMPORTER_FORCE_DYNAMIC is defined. Currently, not all the test cases in check-onnx-backend can pass for dynamic shape. This patch adds a list (`test_not_for_dynamic`) of test cases that failed and skip them for dynamic shape. As a result, when we run `IMPORTER_FORCE_DYNAMCE=1 make check-onnx-backend`, the test should succeed. 
We will gradually reduce the list when more support for dynamic shape is added.
> test dynamic shape with check-onnx-backend

- src/Conversion/ONNXToKrnl/Tensor/Split.cpp
- src/Dialect/ONNX/ONNXOps.cpp
- test/backend/test.py
- test/mlir/onnx/onnx_lowering.mlir
- test/mlir/onnx/onnx_shape_inference.mlir
SplitOp lowering has already supported dynamic dimensions but missed the case of equally splitting where its split attribute is default.
This patch is to add support for that situation, making dynamic tests passed.
> Support equally spliting on unknown dimensions in the SplitOp lowering

- src/Conversion/ONNXToKrnl/Tensor/Tile.cpp
- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXShapeHelper.cpp
- src/Dialect/ONNX/ONNXShapeHelper.hpp
- test/mlir/onnx/onnx_lowering.mlir
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
The shape inference and ONNX to Krnl is implemented with IndexExpr. Different from the previous example of Slice, I put all the lowering code in lowering. The ShapeHelper for TileOp only shares the computation of outputDims. I think that this approach divides the code closer to their semantics:  all the loops for lowering are in the lowering code. In the Shape, there is no need for loops. Consequently, in the lowering, there is no need to inherit IndexExpr context from the ShapeHelper. 
The patch failed some test with dynamic shape because the llvm patch for % is not ready yet. I removed that test case.
> TileOp implementation with  IndexExpr

- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- test/mlir/onnx/onnx_lowering.mlir
- test/mlir/onnx/onnx_lowering_with_dealloc.mlir
TanhOp is in the std dialect, so we lower ONNXTanhOp to TanhOp instead of manually compute tanh using exp.
> Replace the tanh lowering by using std.tanh

- test/backend/test.py
- test/numerical/TestGRU.cpp
- test/numerical/TestLSTM.cpp
- test/numerical/TestRNN.cpp
ONNX does not have backend tests for LSTM/GRU/RNN ops with bidirectional mode. In this patch, we add numerical tests for LSTM/GRU/RNN ops in cases of unknown dimension and bidirectional mode.
> #5 Add numerical tests for lstm/gru/rnn ops with unknown dimensions

- src/Conversion/ONNXToKrnl/ControlFlow/Loop.cpp
- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Dialect/ONNX/ONNXShapeHelper.cpp
- src/Dialect/ONNX/ONNXShapeHelper.hpp
- test/mlir/onnx/onnx_enable_memory_pool.mlir
- test/mlir/onnx/onnx_lowering.mlir
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
This patch uses IndexExpr for broadcasting operations such as binary ops, variadic ops that support multi-directional broadcasting.
> ShapeHelper for broadcasting operations using IndexExpr

- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- test/mlir/onnx/onnx_lowering.mlir
Add support for casting from integer to integer. No backend test is added because there is no backend test for this type of casting in ONNX.
> Support casting from integer to integer

- src/Runtime/OMTensor.inc
- test/backend/CMakeLists.txt
- test/backend/test.py
Resolve #449 and enable testing all dynamic dims in all inputs (by default). Thus, by default, `check-onnx-backend-dynamic" will import all dimensions in all inputs as unknown dims.
Enable tests for Constant and Size. It seems these tests work with master branch. Not sure which PRs solved issues about these tests. So just enable them here.
> Fix wrong setting for datatype size and enable dynamic dims for all inputs and all dimensions

- src/Builder/FrontendDialectTransformer.cpp
- src/Builder/FrontendDialectTransformer.hpp
- src/MainUtils.cpp
- test/onnx2mlir/CustomFnTest.cpp
(1) Introduce options to allow callers to customize translation of ONNX model to ONNX-MLIR
(2) Add option to use type/shape information from input ONNX model for import
An ONNX model allows type-annotations to be stored for all variables in a model (including intermediate temporaries). ONNX type/shape inference can produced a fully annotated ONNX model. The translation of such a fully-annotated model can use the type/shape information contained in the input ONNX model. This is useful in cases where ONNX-MLIR does not have a corresponding type/shape inference method (eg. for custom-ops) or for cases where there is a mismatch between the type/shape inference methods.
The test-case in this PR shows how this can be used with custom-ops.
> Use type/shape information from input ONNX model for import

- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXShapeHelper.cpp
- src/Dialect/ONNX/ONNXShapeHelper.hpp
- test/backend/test.py
- test/mlir/onnx/onnx_lowering.mlir
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
- test/mlir/onnx/onnx_shape_inference.mlir
This patch revises shape inference for ONNXPRelu and lowers ONNXPRelu to krnl dialect. 
> Lower ONNXPRelu to krnl dialect

- docs/Dialects/onnx.md
- docs/Testing.md
- src/Builder/FrontendDialectTransformer.cpp
- src/Builder/OpBuildTable.inc
- src/Dialect/ONNX/ONNXOps.td.inc
- src/Transform/ONNX/Combine.td
- test/backend/test.py
- test/mlir/onnx/onnx_shape_inference.mlir
- utils/gen_onnx_mlir.py
Changes include:
1.  update the version of dropout in gen_onnx_mlir.py
2. add the default valid for optional inputs
3.  Update the document
4. change of test case for check-onnx-lit and check-onnx-backend
Future work: onnx-mlir failed other dropout tests in onnx unit test. Some are due to the data format and the rest may be related to our rewrite rule. We need new lowering function for the more complicated case in the new version. I will take a look into it.
> update dropout Op to the new version

- src/MainUtils.cpp
- src/Transform/ONNX/ConstProp.cpp
- test/mlir/onnx/onnx_constprop.mlir
- test/mlir/onnx/onnx_constprop_with_memref.mlir
This patch does constant propagation for SplitOp.
It also removes the call to constant propagation that happens before shape inference. This solves the issue #471. Because constant propagation now supports both tensor and memref (by PR #462), it always expects a ranked data and is able to return ranked data.
> Constant propagation for SplitOp

- MLIR.cmake
- src/Support/CMakeLists.txt
* make mlir-tblgen import conditional to avoid potential conflict with other MLIR-based repos
* remove unnecessary link to onnx in OMSupport
> Fix folder structure difference between installed LLVM and built-from-source LLVM

- README.md
- src/Builder/FrontendDialectTransformer.cpp
- test/onnx2mlir/CustomFnTest.cpp
ONNX functions permit optional parameters (just like ONNX ops). Extend the translation of ONNX function to MLIR function to handle missing optional parameters. Add a test-case to test it.
> Extend ONNX function translation to handle optional parameters

- test/numerical/TestConv.cpp
- test/numerical/TestGRU.cpp
- test/numerical/TestLSTM.cpp
Allow to change tolerance in numerical tests by the "TEST_RTOL" and "TEST_ATOL" environments.
If they are not set, default values 1e-5 for rtol, and 1e-5 for atol, those are default values of omTensorAreTwoOmtsClose, are used.
> Allow to change tolerance in numerical tests

- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Conversion/ONNXToKrnl/Tensor/Reshape.cpp
- test/mlir/onnx/onnx_lowering.mlir
- test/mlir/onnx/onnx_lowering_attribute_promotion_ops.mlir
This patch is to fix #490.
When the shape input of Reshape is constant, it is promoted to attribute. Thus, the lowering should read shape information from the attribute instead of the shape input (which became None after promotion).
For ops that have attribute promotion, we should handle two cases: an input is 1) promoted and 2) not promoted.
> Support lowering reshape when its input is promoted to attribute

- .buildbot/Jenkinsfile
- docker/Dockerfile.onnx-mlir
- docker/Dockerfile.onnx-mlir-dev
'A quoted commit message that is longer than MAXLEN (24) characters'
When posting github status or comment, we take the first MAXLEN characters
to construct a one-liner, which might end in the middle of a quoted phrase
and cause JSON error in the REST call. This patch should fix that.
> Remove quotes when posting github status and comment

- src/Dialect/ONNX/ONNXOps.td.inc
- src/Transform/ONNX/Combine.cpp
- src/Transform/ONNX/Combine.td
- test/mlir/onnx/onnx_canonicalization.mlir
- utils/gen_onnx_mlir.py
This patch adds DDR rules for removing squeeze/unsqueeze pairs.
> Remove squeeze/unsqueeze pairs

- src/Conversion/ONNXToKrnl/ControlFlow/Loop.cpp
- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Conversion/ONNXToKrnl/Math/MatMul.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Conversion/ONNXToKrnl/Tensor/Constant.cpp
- test/mlir/onnx/onnx_location.mlir
This change maps the ONNX operator names (e.g. onnx.Add) to their corresponding MLIR instructions as  named location information.
Downstream, the operator names can be used to more accurately trace the kernel operations that were responsible for generating different MLIR instructions. To avoid extra code churn I only modified a subset of the common operators.
> Map ONNX operator names to instructions

- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Conversion/ONNXToKrnl/Math/Gemm.cpp
- src/Conversion/ONNXToKrnl/Math/LRN.cpp
- src/Conversion/ONNXToKrnl/Math/MatMul.cpp
- src/Conversion/ONNXToKrnl/Math/Reduction.cpp
- src/Conversion/ONNXToKrnl/NN/Conv.cpp
- src/Conversion/ONNXToKrnl/NN/Pooling.cpp
- src/Conversion/ONNXToKrnl/Tensor/Concat.cpp
- src/Conversion/ONNXToKrnl/Tensor/Gather.cpp
- src/Conversion/ONNXToKrnl/Tensor/Shape.cpp
- src/Conversion/ONNXToKrnl/Tensor/Slice.cpp
- src/Conversion/ONNXToKrnl/Tensor/Split.cpp
- src/Conversion/ONNXToKrnl/Tensor/Tile.cpp
- src/Conversion/ONNXToKrnl/Tensor/Transpose.cpp
- src/Dialect/Krnl/KrnlHelper.cpp
- src/Dialect/ONNX/IndexExpr.cpp
- src/Dialect/ONNX/IndexExpr.hpp
- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXOpsHelper.cpp
- src/Dialect/ONNX/ONNXOpsHelper.hpp
- src/Dialect/ONNX/ONNXShapeHelper.cpp
- src/Dialect/ONNX/ONNXShapeHelper.hpp
- src/Transform/ONNX/ElideConstants.cpp
- test/mlir/onnx/onnx_lowering.mlir
- test/mlir/onnx/onnx_shape_inference.mlir
Updated the IndexExpr interface to be more like EDSC like. At the big picture level, I created two new data structure to capture memref bounds and array values as index expressions:
```mlir
// Scan dimensions of A with/without transpose.
MemRefBoundIndexCapture ABounds(A);
if (op->transA() == 0) {
aDims = {ABounds.getDim(0), ABounds.getDim(1)};
} else {
aDims = {ABounds.getDim(1), ABounds.getDim(0)};
}
```
or 
```mlir
ArrayValueIndexCapture startsCapture(genericOp, operandAdaptor.starts());
for (uint64_t i = 0; i < sliceRank; i++) {
int ii = axesIntLit[i];
// Get start, end, step, and dim index expressions.
// Get start.
SymbolIndexExpr startInput(startsCapture.getSymbol(i));
// ...
}
```
To create IndexExpr, we have now 5 subclasses of IndexExpr that are use solely to create Index …
> Index Expression interface update

- test/backend/CMakeLists.txt
Signed-off-by: chentong <chentong@us.ibm.com>
Add dependence for target check-onnx-backend-dynamic, same as check-onnx-backend.
> Add dependence for check-onnx-backend-dynamic

- src/Runtime/OMTensor.inc
The equation for validating calculation results in numerical tests is different from onnx backend test. This PR changes the equation to use the same one with onnx backend test. I think this equation is generally used, but is there any specific reason to use current one?
Onnx backend test uses `absolute(a - b) <= (atol + rtol * absolute(b))` by using [`testing.assert_allclose`](https://numpy.org/doc/stable/reference/generated/numpy.testing.assert_allclose.html) . Source code is [here.](https://github.com/onnx/onnx/blob/v1.7.0/onnx/backend/test/runner/__init__.py#L174) Equation is written [here]( https://numpy.org/doc/stable/reference/generated/numpy.allclose.html)
When I changed ATOL and RTOL both in onnx backend test and numerical test to meet my requirement, I got errors only in …
> Change the equation for validating calculation results in numerical tests

- src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
- src/Runtime/OMTensorList.inc
Memory leak issue was originally reported by @seroyer. Thanks, Steven!
Test program (for MNIST inference): 
```mlir
OMTensor *tensor = omTensorCreate(input, shape.data(), shape.size(), ONNX_TYPE_FLOAT);
OMTensor *tensorList[] = {tensor};
OMTensorList *tensorListIn = omTensorListCreate(tensorList, 1);
OMTensorList *tensorListOut = run_main_graph(tensorListIn);
omTensorListDestroy(tensorListOut);
omTensorListDestroy(tensorListIn);
```
Using valgrind to check memory leak: `valgrind --leak-check=full ./memcheck`
- run one inference:
```
==372468== LEAK SUMMARY:
==372468==    definitely lost: 8 bytes in 1 blocks
==372468==    indirectly lost: 0 bytes in 0 blocks
==372468==      possibly lost: 0 bytes in 0 blocks
==372468==    still reachable: 0 bytes …
```
> Fix memory leak with C/C++ interface

- CMakeLists.txt
The onnx build on windows requires the provision of either static or shared libs for protobuf and to achieve that there are several different flags that need to be set in protobuf, onnx as well as cmake (for find_package). At the very minimum ONNX_USE_PROTOBUF_SHARED_LIBS and Protobuf_USE_STATIC_LIBS need to be opposites of each other, but onnx does not currently set them up that way (onnx doesn't set Protobuf_USE_STATIC_LIBS at all and cmake interprets that as setting Protobuf_USE_STATIC_LIBS to OFF). If/when onnx is updated to correctly set up both variables, this can be removed (see https://github.com/onnx/onnx/issues/3345).
> Set ONNX_USE_PROTOBUF_SHARED_LIBS and Protobuf_USE_STATIC_LIBS 

- MLIR.cmake
When integrating as an external project, this becomes awkward.
It's generally preferable to use cmake variables to configure
things like this.  This patch extends the existing mechanism to
allow the use of cmake variables.
> [cmake] Allow pointing to LLVM without using environment variables

- src/Conversion/KrnlToAffine/KrnlToAffine.cpp
- src/Conversion/ONNXToKrnl/Math/MatMul.cpp
- src/Dialect/Krnl/KrnlHelper.cpp
- src/Dialect/Krnl/KrnlHelper.hpp
- src/Dialect/Krnl/KrnlOps.cpp
- src/Dialect/Krnl/KrnlOps.td
Added support for Variadic parameter passing in MatMul, CopyFromBuffer, CopyToBuffer, in order to facilitate the use of broadcast in matrix multiplication. Before this, memrefs were restricted to 2D data structures.
EDSC and MLIR seems to use predominantly `ValueRange` instead of `ArrayRef<Value>` and having the Krnl EDSC rely on ArrayRefs was making the integration more difficult. This PR changes them to facilitate integration. 
Finally, moved asserts that were checking the validity of parameter for MatMul from the builder (which was limited to one specific builder) to a verify() function for more broad use.
> Krnl operations support for broadcast

- src/MainUtils.cpp
Using -O3 for opt causes unexpected behavior on BE machines. One issue was reported here: #600.
This patch changes to use -O2 for safety.
> Use -O2 in bitcode opt

- MLIR.cmake
- src/Dialect/Krnl/CMakeLists.txt
- src/Dialect/ONNX/CMakeLists.txt
- src/Dialect/ONNX/ONNXOps.hpp
- src/Dialect/ONNX/ONNXOps.td
- src/Interface/CMakeLists.txt
- src/Interface/ShapeInferenceOpInterface.cpp
- src/Interface/ShapeInferenceOpInterface.hpp
- src/Interface/ShapeInferenceOpInterface.td
- src/Transform/ONNX/CMakeLists.txt
- src/Transform/ONNX/ShapeInferencePass.cpp
mlir (and llvm for that matter) use helper tablegen functions to simplify logic that is repetitive.
This is using the existing onnx_mlir_tablegen function to add a couple of helper functions similar to mlir and then use them.
As part of this change, a couple of inconsistencies in the naming of the generated targets and files were found and addressed as well.
Eventually, onnx_mlir_tablegen will replaced with mlir_tablegen (eventually = when using find_package(mlir)).
> Add cmake tablegen functions

- src/MainUtils.cpp
- test/backend/test.py
…option in MainUtils.cpp
Options to set the cpu and triple were added on onnx-mlir, but not to the python test.py. In addition, onnx-mlir was not able to handle 2 options... this is now fixed. New options (last 2)
```
Options for test.py
usage: test.py [-h] [--dynamic] [-i INPUT] [-d DIM] [-v] [--mtriple MTRIPLE] [--mcpu MCPU] [unittest_args [unittest_args ...]]
with dynamic shape or not.
positional arguments:
unittest_args
optional arguments:
-h, --help            show this help message and exit
--dynamic             enable dynamic shape tests (default: false if TEST_DYNAMIC env var not set)
-i INPUT, --input INPUT
inputs whose dimensions to be changed to unknown (default: all inputs if TEST_INPUT env var not set)
-d DIM, --dim DIM     dimensions to be changed to unknown (default: all …
```
> enable compiler options for test.py (necessary for SIMD on z)

- .buildbot/Jenkinsfile
- .buildbot/ONNX-MLIR-Pipeline-Docker-Build.xml
- .buildbot/jenkins-build-llvm-project.py
- .buildbot/jenkins-build-project.py
- .buildbot/jenkins-cleanup-build-states.py
- .buildbot/jenkins-publish-docker-images.py
- .buildbot/jenkins-stop-previous-build.py
- src/Runtime/jni/jnilog.c
- src/Runtime/jni/jnilog.h
- src/Runtime/jni/jniwrapper.c
- move jniapi into stack to avoid J9 crash, which apparently cannot share pointer returned by FindClass across threads
- make jnilog thread safe also
> Fix J9 crash (llvm-12-release-branch)

- src/Builder/FrontendDialectHelper.cpp
- src/Builder/FrontendDialectHelper.hpp
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/Conversion/ONNXToKrnl/Math/Gemm.cpp
- src/Conversion/ONNXToKrnl/Math/LRN.cpp
- src/Conversion/ONNXToKrnl/Math/MatMul.cpp
- src/Conversion/ONNXToKrnl/Tensor/ArgMax.cpp
- src/Conversion/ONNXToKrnl/Tensor/Concat.cpp
- src/Conversion/ONNXToKrnl/Tensor/Gather.cpp
- src/Conversion/ONNXToKrnl/Tensor/Slice.cpp
- src/Conversion/ONNXToKrnl/Tensor/Split.cpp
- src/Conversion/ONNXToKrnl/Tensor/Tile.cpp
- src/Conversion/ONNXToKrnl/Tensor/Transpose.cpp
- src/Dialect/Krnl/KrnlHelper.cpp
- src/Dialect/Krnl/KrnlHelper.hpp
- src/Dialect/ONNX/IndexExpr.cpp
- src/Dialect/ONNX/IndexExpr.hpp
- src/Dialect/ONNX/IndexExprDetail.cpp
- src/Dialect/ONNX/IndexExprDetail.hpp
- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXOps.hpp
- src/Dialect/ONNX/ONNXOpsHelper.cpp
- src/Dialect/ONNX/ONNXOpsHelper.hpp
- src/Dialect/ONNX/ONNXShapeHelper.cpp
- src/Dialect/ONNX/ONNXShapeHelper.hpp
- src/Transform/ONNX/Decompose.cpp
- src/Transform/ONNX/Rewrite.cpp
As the title say. The most "difficult" was that ONNX Shape Helper need to generate some code, which for us is KRNL ops. So I added two lambda functions that are passed as parameters to the ONNX shape helper to retrieve and generate KRNL ops, so that ONNX may be deployed (for shape inference) totally free of KRNL, and when we want to use it with KRNL, we just passed the appropriate functions. Similar functions are trivial to generate using affine dialect, if need be.
Lots of tedious small changes
> Removing in IndexExpr any references to ONNX and KRNL, Removing in ONNX any references to KRNL

- src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
- src/Transform/BundleMemoryPools.cpp
- src/Transform/DisconnectKrnlDimFromAlloc.cpp
- src/Transform/ElideKrnlGlobalConstants.cpp
- src/Transform/EnableMemoryPool.cpp
- src/Transform/LowerKrnlShape.cpp
- src/Transform/ONNX/ConstProp.cpp
- src/Transform/ONNX/ShapeInferencePass.cpp
- src/Transform/OptimizeMemoryPools.cpp
- test/numerical/TestConv.cpp
- test/onnx2mlir/CustomFnTest.cpp
MLIR requires the return value of passes to be tested. Most are now, with some where its ok to succeed or fail.
> added use for the return value of passes

- src/Builder/FrontendDialectTransformer.cpp
When converting Slice op attrs to constant inputs, we need to use the size of the attribute as the shape of the constant.
Signed-off-by: aman <alachapelle@apple.com>
> Fix for Issue #619

- .gitmodules
- CMakeLists.txt
- src/Builder/CMakeLists.txt
- src/Builder/FrontendDialectTransformer.cpp
This submodule is currently unused, so it can be removed. The header and lib are referenced (as in the header is included and the lib is linked against), however, they are never actually used in code.
> Remove variant

- src/Transform/ONNX/CMakeLists.txt
A compile order dependency issue was introduced with commit
09259975200307925971b4cd51061d942f794868
```
In file included from /build/third_party/onnx-mlir/src/Dialect/ONNX/ONNXOps.hpp:27,
from /build/third_party/onnx-mlir/src/Transform/ONNX/ShapeInferencePass.cpp:23:
/build/third_party/onnx-mlir/src/Interface/HasOnnxSubgraphOpInterface.hpp:26:10: fatal error: src/Interface/HasOnnxSubgraphOpInterface.hpp.inc: No such file or directory
#include "src/Interface/HasOnnxSubgraphOpInterface.hpp.inc"
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```
Signed-off-by: Steven Royer <seroyer@us.ibm.com>
> Fix dependency error with ShapeInferencePass

- src/Conversion/KrnlToAffine/KrnlToAffine.cpp
- src/Dialect/Krnl/KrnlOps.cpp
- src/Dialect/Krnl/KrnlOps.hpp
- src/Dialect/Krnl/KrnlOps.td
- test/mlir/krnl/get_induction_var_value.mlir
- test/mlir/krnl/hoisting.mlir
- test/mlir/krnl/imperfectly_nested_stmts.mlir
Before lowering krnl op, move invariant instructions outside of the loops as many as possible. This helps make loops perfectly nested, which facilitates transformations.
resolves #697 
> Hoist invariant instructions from krnl.iterate before lowering

- src/Dialect/Krnl/KrnlOps.td
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
KrnlGlobalOp is to define constants. Constants become dangling once there is not use, but they are not removed.
This patch marks KrnlGlobalOp with NoSideEffect so that dangling constants will be removed automatically when canonicalization is called.
> Add NoSideEffect trait to KrnlGlobalOp

- test/numerical/TestConv.cpp
- test/numerical/TestGRU.cpp
- test/numerical/TestGemm.cpp
- test/numerical/TestLSTM.cpp
- test/numerical/TestMatMul2D.cpp
- test/numerical/TestRNN.cpp
Current numerical may assert in the `rc::check` silently using the `make test` check. The fix here enforce a return of a non-zero values on `rc::check` error.
It will be enabled also for TestGemm, which currently fails.
> Added return of nonzero value when errors occur

- docs/Testing.md
- src/MainUtils.cpp
Enable the saving of the input and output mlir files when using the compileModule function (either called in drivers such as in numerical, or onnx-mlir). 
It can also be enabled by setting the KEEP_TEMP_FILES define in src/MainUtils.cpp. This enables to more easily look at the input ONNX mlir files generated by numerical or any other models using onnx-mlir, as it does not requires printout to stderr and/or adding a flag (for which the functionality does not appear to be here in the direct interfaces (only present via the onnx-mlir program)
> Preserve mlir files when using  onnx-mlir or compileModule 

- docs/Testing.md
- src/Conversion/ONNXToKrnl/Math/Gemm.cpp
- src/MainUtils.cpp
- src/Runtime/OMTensor.inc
- test/numerical/TestGemm.cpp
Turns out that there was a mixup between allocated ptr and aligned in the runtime, and for some reason, small dimensions were triggering a tensor where the two pointers where not the same.
Fixed also a memory leak in `omTensorAreTwoOmtsClose`
> Investigate gemm small dim error, fixed now

- src/Conversion/ONNXToKrnl/CMakeLists.txt
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Conversion/ONNXToKrnl/Tensor/Resize.cpp
- src/Dialect/ONNX/ONNXOps.cpp
- test/mlir/onnx/onnx_lowering.mlir
- test/mlir/onnx/onnx_shape_inference.mlir
This PR support shape inference and lowering for Resize Op with static shape and constant scales.  Only the nearest mode is supported. 
1. Shape inference. Use `output_dimension = floor(input_dimension * (roi_end - roi_start) * scale) if input "sizes" is not specified.` to compute the output_dimension. The standard says `It (roi) only takes effect when coordinate_transformation_mode is "tf_crop_and_resize"`. Current implementation is for "asymmetric" and rio_end and rio_start are ignored.
2. In lowering, the index is computed as 
```
if coordinate_transformation_mode is "asymmetric", 
x_original = x_resized / scale, 
```
3. examples from standard:
resize_downsample_scales_nearest and resize_upsample_scales_nearest
Please note that in resize_downsample_scales_nearest, for the last …
> Resize Op with static shape and constant scales

- src/Conversion/ONNXToKrnl/Tensor/Resize.cpp
- src/Dialect/ONNX/IndexExpr.hpp
- src/Dialect/ONNX/ONNXOps.cpp
- test/backend/test.py
- test/mlir/onnx/onnx_lowering.mlir
This PR handles non-constant scales() and unknown size of input data X().
Extend the implementation to handle nearest_mode() == "round_prefer_floor" and coordinate_transformation_mode() == "half_pixel", the default value for the optional attributes. With these support, some backend test for resize in onnx can be passed. 
IndexExpr utilities are used and mixed with std ops due to the type conversions. The IndexExpr code is directly added in lowering currently.
> Handle dynamic input of Resize Op

- src/Builder/FrontendDialectTransformer.cpp
- src/Pass/Passes.hpp
- src/Transform/ONNX/ShapeInferencePass.cpp
- test/onnx2mlir/CustomFnTest.cpp
(Closing PR #723 and recreating it due to signoff/DCO issues.)
A couple of fixes to enable the translation of ONNX functions using MLIR functions:
(a) The existing shape-inference pass has a hack that checks if the module contains any function with a name matching the pattern "[a-zA-Z0-9_]*main_graph" and, if so, restricts inference to those functions. Adding an option analyzeAllFunctions to skip this filter, since when translating ONNX functions into MLIR functions it is useful to apply shape-inference to all functions (even though it has a main_graph). Also, allow function-calls in code being checked.
(b) Refine the translation process when using the option useOnnxModelTypes (which enables the translator to use type-information contained in the input model during translation) to use the …
> Add shape inference pass option to analyze all functions

- src/Transform/ONNX/ConstPropHelper.cpp
- test/mlir/onnx/onnx_constprop.mlir
This patch fixes an issue in constant propagation when creating a DenseElementsAttr whose type is scalar tensor using a raw buffer. For scalar tensor, we should mark the attribute with splat.
Resolves #733 
> Handle scalar attributes in constprop

- src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
- test/mlir/krnl/krnl_global_with_alignment_lowering.mlir
This patch is to put aligned constants on the heap to avoid stack overflow.
> Put aligned constants on the heap instead of the stack

- src/Builder/FrontendDialectTransformer.cpp
- test/onnx2mlir/CMakeLists.txt
- test/onnx2mlir/CustomFnTest.cpp
A small fix to the recent addition of op_dialect_version_map to name ops with multiple versions. Custom ops may not have an entry in this map, and can be handled as before (without any renaming).
> Handle custom ops without op_dialect_version_map entry

- src/Builder/FrontendDialectTransformer.cpp
- src/Builder/FrontendDialectTransformer.hpp
- src/MainUtils.cpp
This patch introduces an option, `shapeInformation`, to command `onnx-mlir`, which is to set static dimensions for the inputs of a model.
The motivation is that compiling a model with dynamic dimensions may introduce performance overhead. If we know the exact shapes of the inputs to run the model inference, we should give the compiler such static shapes so that more optimizations can be done.
> Add an option shapeInformation to set static shapes for the inputs

- src/Runtime/OMTensor.inc
PR #549 updated the equation for validating calculation results, but, the equation used for printing out wrong results was not updated. This PR updates it.
> Update the equation used for printing out wrong results.

- src/Builder/FrontendDialectTransformer.cpp
- src/Runtime/jni/jnilog.c
- src/Transform/ONNX/ConstProp.cpp
Removing spurious compiler warnings that have accumulated during recent PRs.
> removing compiler warnings

- src/Runtime/OMInstrument.inc
The OM runtime library used libraries not available on windows. This temporary fix added `#ifdef _WIN32' with `TO BE FIXED` comment.
When instrumentation part becomes mature, we will add the corresponding part for windows.
> Fix instrument error on windows

- src/MainUtils.cpp
1. Rather than directly using memorybuffer to open input files, use the mlir openInputFile function
2. Instead of writing the output to std::err after redirecting std::err to the output file, use the mlir openOutputFile function to open the file and then write directly to it
3. Cleanup the includes in MainUtils.cpp
> Use the mlir file utilities for opening input and output files

- README.md
Change build badge for Jenkins CI to display master branch build status only
> Change build badge for Jenkins CI

- README.md
- docker/onnx-mlir.py
- src/MainUtils.cpp
- src/main.cpp
- Convenient python script to run onnx-mlir from docker container
- Check freopen failure in MainUtils.cpp:outputCode
- Ignore invalid -o option values in main.cpp
- Update README.md about the convenient python script
> Script to run onnx-mlir from docker container

- README.md
- docs/README.md
looks like on window, the softlink is transformed in something else. So now have 2 distinct files, with a big warning to keep them in sync.
If someone tell me how to do the following, happy to add it.
`diff README.md docs/README.md` result in an empty line in the makefile... that would be great. I don't know how to do that in a cmake, sorry. 
Ideally that command would be added to the `make check-doc` command.
> readme to be kept in sync

- src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
- test/mlir/krnl/krnl_global_with_alignment_lowering.mlir
MLIR now supports LLVM GlobalOp with alignment.  We can use it for our aligned constants so that there is no need of creating a separate buffer for aligned data.
This patch updates our lowering code to use the LLVM GlobalOp with alignment. 
> Set alignment for LLVM GlobalOp

- src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
- test/backend/test.py
- test/mlir/module_op_be/lit.local.cfg
- test/mlir/module_op_be/module_op.mlir
- test/mlir/module_op_le/lit.local.cfg
- test/mlir/module_op_le/module_op.mlir
Resolves #816
Since LLVM optimizations use module's DataLayout to know whether constant data is in little or big endian. We should annotate ModuleOp with correct endianness so that LLVM optimizations correctly read constant data.
This patch adds `llvm.data_layout` to ModuleOp whose value is `e` or `E` for little or big endian, respectively.
By this patch, all constant-related end-to-end tests, except ones our builder does not support, are passed.
> Add the data_layout attribute to ModuleOp to denote endianness

- .azure-pipelines/Windows-CI.yml
- README.md
- docs/README.md
- utils/build-mlir.cmd
- utils/build-onnx-mlir.cmd
- utils/check-numerical.cmd
- utils/check-onnx-mlir.cmd
- utils/install-protobuf.cmd
This updates the Windows CI to use ninja as the cmake generator (though the build tools are still Visual Studio). The scripts and readme are updated accordingly as well
> Use ninja to build on Windows

- src/MainUtils.cpp
- src/Support/OMOptions.cpp
- src/Support/OMOptions.hpp
Change the option `memory-bundling-enabled` to `disable-memory-bundling` to make it easier to understand.
By default, memory bundling is enabled, passing `--disable-memory-bundling` to `onnx-mlir` to disable.
Help is now better to understand:
```
--disable-memory-bundling                 - disable memory bundling related optimizations
where several passes work together to bundle buffers.
Buffer management by MLIR is used instead.
Try this if you experience a significant compile time.
```
> Change the option memory-bundling-enabled to disable-memory-bundling

- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXShapeHelper.cpp
- test/numerical/TestConv.cpp
change the erroneous floor into a ceil according to ONNX standard fo… r CONV, as seen in MaxPool
From MaxPool doc for VALID:
VALID: output_spatial_shape[i] = ceil((input_spatial_shape[i] - ((kernel_spatial_shape[i] - 1) * dilations[i] + 1) + 1) / strides_spatial_shape[i])
floor was used before, switched to ceil.
> Fix for CONV with VALID auto_pad

- src/Dialect/ONNX/ONNXOps.td
Add the following argument part in the onnx.EntryPoint op definition to enable operation generation by tablegen.
let arguments = (ins SymbolRefAttr:$func,
I32Attr:$numInputs,
I32Attr:$numOutputs,
StrAttr:$signature);
Otherwise, tablegen causes an error with the "error: op 'onnx.EntryPoint' argument number mismatch: 4 in pattern vs. 0 in definition ..." message.
> Update onnx.EntryPoint op definition to allow operation generation by tablegen.

- src/Conversion/ONNXToKrnl/Tensor/Resize.cpp
- src/Dialect/ONNX/ONNXOps.cpp
- test/backend/test.py
- test/mlir/onnx/onnx_shape_inference_error.mlir
In the new version of yolo model, yolov4, the resize is specified by input sizes, instead of scales. This PR added the support of using sizes input.
Accordingly, test cases for resize using sizes are enabled in our backend test.
> New support for resize op

- src/Conversion/ONNXToKrnl/RNN/RNNBase.cpp
- test/mlir/onnx/onnx_lowering_gru_op.mlir
- test/mlir/onnx/onnx_lowering_lstm_op.mlir
- test/mlir/onnx/onnx_lowering_rnn_op.mlir
There are some remaining code in LSTM/RNN/GRU still using the old coding style. Replace them with IndexExpr.
Since we use IndexExpr, lit tests are modified to use canonicalization.
> Replacing the remaining old code in LSTM/RNN/GRU by IndexExpr

- docker/Dockerfile.onnx-mlir
- docker/Dockerfile.onnx-mlir-dev
- docs/Testing.md
- test/backend/CMakeLists.txt
- test/numerical/TestConv.cpp
- test/numerical/TestGRU.cpp
- test/numerical/TestGemm.cpp
- test/numerical/TestLSTM.cpp
- test/numerical/TestLoop.cpp
- test/numerical/TestMatMul2D.cpp
- test/numerical/TestRNN.cpp
Enable SIMD in backend and numerical tests for user docker image,
dev docker image is built without SIMD so we cover both cases.
> Enable SIMD in backend and numerical tests for user docker image

- docs/Testing.md
- src/MainUtils.cpp
The onnx model comes without user friendly source file and our importer assign `UnknownLoc` to all the operations. As a result, we do not have Location info in our transformation and binary. 
This PR will use the output of preserveMLIR as source file and get Location info by rebuilding operations from this file.
I just reused the option `--preserveMLIR`.
Document is added in `docs/Testing.md`.
> create source code for binary

- src/Conversion/ONNXToKrnl/CMakeLists.txt
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Conversion/ONNXToKrnl/Tensor/NonZero.cpp
- src/Dialect/ONNX/MLIRDialectBuilder.cpp
- src/Dialect/ONNX/MLIRDialectBuilder.hpp
- src/Dialect/ONNX/ONNXOps.cpp
- test/backend/test.py
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
This patch implements NonZeroOp. 
This op's output shape is quite interesting, it depends on the values of the input, not the input shape. In particular, the second dim of the output shape is the number of nonzero values in the input.
So, the output shape would be dynamic and we should emit code traversing the input before allocating the output memref.
Fix a bug related to endian in `test.py`. When input is of boolean (`i1`), endianness is not relevant but `test.py` wrongly checks that it is in big endian and set output type to big endian, so tests failed on little endian machines x86, ppcle but not Z.
> Implement ONNX NonZeroOp

- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXOps.td.inc
- test/backend/test.py
- test/mlir/onnx/invalid.mlir
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
- utils/gen_onnx_mlir.py
This patch implements ONNX ModOp and MeanOp.
For ModOp, since MLIR integers are signless, so it looks impossible to support signed and unsigned integer remainders as required by ONNX.
> Support ONNX ModOp and MeanOp

- src/Builder/OpBuildTable.inc
- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXOps.td.inc
- src/Transform/ONNX/Decompose.cpp
- src/Transform/ONNX/Decompose.td
- test/backend/test.py
- test/mlir/onnx/onnx_decompose.mlir
- utils/gen_onnx_mlir.py
ONNX Upsample is deprecated and can be replaced by ONNX Resize, so we rewrite Upsample into Resize. 
This patch supports all Upsample versions 10, 9, 7.
> Rewrite ONNX Upsample into ONNX Resize

- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Dialect/ONNX/ONNXOps.cpp
- test/backend/test.py
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
This patch implements ONNX WhereOp.
It also fixed an endianness issue in `test.py` happened with WhereOp where there was a mix of boolean and non-boolean types in inputs.
> Support WhereOp

- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXOps.td.inc
- test/mlir/onnx/invalid.mlir
- utils/gen_onnx_mlir.py
This PR adds custom `verify` methods for the DepthToSpace and SpaceToDepth operators to check that:
- input tensor has 4 dims
- blocksize is strictly positive and divides the appropriate input tensor dimension(s) without remainder
> Add custom verification for DepthToSpace and SpaceToDepth operators.

- CMakeLists.txt
- src/Runtime/jni/jnilog.c
- test/onnx2mlir/CustomFnTest.cpp
- third_party/CMakeLists.txt
This PR adds clang & gcc options to suppress warnings when C/C++ code is compiled in the `third_party` subprojects. 
In addition it fixes an issues in the Runtime onnx-mlir code.  Warnings continue to be emitted for C/C++ code in the onnx-mlir project proper.
> [NFC] Suppress warnings in third_party subprojects.

- .azure-pipelines/Windows-CI.yml
- README.md
- docker/Dockerfile.onnx-mlir
- docker/Dockerfile.onnx-mlir-dev
- test/backend/CMakeLists.txt
- test/backend/conftest.py
- test/backend/test.py
- test/numerical/CMakeLists.txt
- utils/check-numerical.cmd
- utils/check-onnx-numerical.cmd
We currenly run a few test sets, e.g., check-onnx-backend, check-onnx-backend-dynamic,
etc., in serial. While we do parallelize within each test set, we don't get much
benefit from it. Because within each test set, most of the time was spent on one
or two long running tests. While waiting for these long running tests, we could have
started the next test sets.
This patch parallelizes across tests sets by starting them all at once so the long
running tests from different test sets can run in parallel.
CompilerLib tests are disabled because a bug has been uncovered that it was actually
still using onnx-mlir instead of CompilerLibTest to compile the models. Fix the bug
to use CompilerLibTest and it fails to compile the models.
> Parallelize test sets

- docs/Testing.md
- src/Dialect/ONNX/IndexExpr.cpp
Copied relevant info from issue #930 so that this info will perdure the issue.
> Added documentation on using DEBUG according to LLVM

- src/Dialect/ONNX/CMakeLists.txt
- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXOps.td.inc
- src/Dialect/ONNX/ShapeInference/CategoryMapper.cpp
- src/Dialect/ONNX/ShapeInference/ONNXShapeHelper.cpp
- src/Dialect/ONNX/ShapeInference/ONNXShapeHelper.hpp
- test/mlir/onnx/onnx_shape_inference.mlir
- test/mlir/onnx/onnx_shape_inference_error.mlir
- utils/gen_onnx_mlir.py
This PR adds support for shape inference for the `CategoryMapper` operator. It also adds a custom verification method for that operator.
> CategoryMapper: shape inference and verification support.

- .circleci/config.yml
- CONTRIBUTING.md
- MLIR.cmake
- docs/Dialects/krnl.md
- docs/Dialects/onnx.md
- docs/ImportONNXDefs.md
- src/Dialect/Krnl/KrnlOps.td
Just like `make OMONNXOpsIncTranslation` moves the updated ONNX spec files into the source files, now the  `make onnx-mlir-docs` also move the updated description of the ONNX and Krnl dialect into the `docs/Dialects` subdirectory.
Added reference to this command in the documentation files.
> Updating docs to move into the right place

- src/Transform/EnableMemoryPool.cpp
- test/mlir/krnl/krnl_enable_memory_pool.mlir
In this PR we are fixing the problem described in work item #953.
> Fix EnableMemoryPool to account for 'memref.cast' operation.

- src/Compiler/CMakeLists.txt
When the code was separated into its own library, the generator expression for the file configuration was dropped. This is needed because file generation happens at cmake config time and for multiconfig generators such as VS or Xcode the build configuration is not known.
This change brings back the generator expression for file generation.
> Fix the compiler lib builds for multiconfig generators

- src/Builder/FrontendDialectTransformer.cpp
This patch prints out opset of ONNX operations in a given ONNX model. It also prints out the opset version onnx-mlir will use to import an ONNX op.
E.g.
```
$ ./Debug/bin/onnx-mlir --EmitONNXBasic ssd_mobilenet_v1_10.onnx --debug 2>&1 | grep frontend
...
frontend_dialect_transformer: Importing ONNX Cast, opset: 10
frontend_dialect_transformer: Importing ONNX Greater, opset: 10
frontend_dialect_transformer: Importing ONNX If, opset: 10
frontend_dialect_transformer: Importing ONNX Gather, opset: 10
frontend_dialect_transformer: Importing ONNX Shape, opset: 10
frontend_dialect_transformer: Importing ONNX Cast, opset: 10
frontend_dialect_transformer: Importing ONNX Slice, opset: 10
frontend_dialect_transformer: Importing ONNX Squeeze, opset: 10
frontend_dialect_transformer:   - use opset 11 …
```
> Print out debug info about opset of importing onnx ops

- src/Conversion/KrnlToAffine/KrnlToAffine.cpp
- test/mlir/krnl/unroll.mlir
`krnl-to-affine` pass failed when lowering a krnl code in which `krnl.unroll` was used together with `krnl.get_induction_var_value`. This issue was reported in #984.
The issue happened because `krnl.get_induction_var_value` was lowered after `krnl.unroll`. When it's the turn of `krnl.get_induction_var_value`, loop induction variables were disappeared because they were already unrolled.
This patch fixes the issue by interpreting `krnl.get_induction_var_value` together with `krnl_unroll`, so the lowering can correctly interpret induction variable values.
Resolves #984
> Fix an issue that knrl_unroll does not work with krnl.get_induction_var_value

- docs/LoweringCode.md
- src/Conversion/ONNXToKrnl/Math/CumSum.cpp
- src/Conversion/ONNXToKrnl/Math/Gemm.cpp
- src/Conversion/ONNXToKrnl/Math/Hardmax.cpp
- src/Conversion/ONNXToKrnl/Math/MatMul.cpp
- src/Conversion/ONNXToKrnl/Math/Softmax.cpp
- src/Conversion/ONNXToKrnl/NN/Normalization.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp
- src/Conversion/ONNXToKrnl/ObjectDetection/NonMaxSuppression.cpp
- src/Conversion/ONNXToKrnl/RNN/GRU.cpp
- src/Conversion/ONNXToKrnl/RNN/LSTM.cpp
- src/Conversion/ONNXToKrnl/RNN/RNN.cpp
- src/Conversion/ONNXToKrnl/RNN/RNNBase.cpp
- src/Conversion/ONNXToKrnl/Tensor/Compress.cpp
- src/Conversion/ONNXToKrnl/Tensor/Flatten.cpp
- src/Conversion/ONNXToKrnl/Tensor/NonZero.cpp
- src/Conversion/ONNXToKrnl/Tensor/Shape.cpp
- src/Dialect/Krnl/KrnlHelper.hpp
- src/Dialect/ONNX/MLIRDialectBuilder.cpp
- src/Dialect/ONNX/MLIRDialectBuilder.hpp
- src/Dialect/ONNX/ONNXOpsHelper.hpp
Instead of creating multiple builders, e.g.
```C++
KrnlBuilder createKrnl(rewriter, loc);
MathBuilder createMath(createKrnl);
MemRefBuilder createMemRef(createKrnl);
```
and then using them like this
```C++
createKrnl.defineLoop(1);
createMath.add(i1, i2);
createMemRef.alloca(type);
```
we can create a single builder composed of multiple types and then as follows.
```C++
MultiDialectBuilder<KrnlBuilder, MathBuilder, MemRefBuilder>
create(rewriter, loc);
create.krnl.defineLoop(1);
create.math.add(i1, i2);
create.mem.alloca(type);
```
Changed usage where it made sense in the code, and added doc to describe new feature.
> support for multiple dialect builder object

- src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
`LLVM::LoadOp` takes the element type of provided pointer.
> Fix types of dimSize and dimStride generated in KrnlToLLVM.

- MLIR.cmake
Right now, the onnx-mlir docs (generating the dialect md files for onnx and krnl) is generated by default. But this may fail for users that did not install onnx third party tools. In any case, this target `onnx-mlir-docs` should only be called when changes were made to either Krnl or ONNX dialect. This is generally a rare event. So definitely does not belong to the default build process.
This will address issue #1001
> Removed default building of onnx-mlir docs

- docs/Dialects/krnl.md
- docs/Dialects/onnx.md
- src/Conversion/ONNXToKrnl/CMakeLists.txt
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/Conversion/ONNXToKrnl/ML/CategoryMapper.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Conversion/ONNXToKrnl/PerfectHash.cpp
- src/Conversion/ONNXToKrnl/PerfectHash.hpp
- src/Conversion/ONNXToKrnl/Tensor/Constant.cpp
- src/Dialect/Krnl/KrnlHelper.cpp
- src/Dialect/Krnl/KrnlHelper.hpp
- src/Dialect/Krnl/KrnlOps.cpp
- src/Dialect/Krnl/KrnlOps.hpp
- src/Dialect/Krnl/KrnlOps.td
- src/Dialect/Krnl/KrnlTypes.hpp
- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXOps.hpp
- src/Dialect/ONNX/ONNXOpsHelper.cpp
- src/Dialect/ONNX/ONNXOpsHelper.hpp
- test/mlir/onnx/onnx_lowering.mlir
- test/mlir/onnx/onnx_lowering_category_mapper.mlir
- test/mlir/onnx/onnx_lowering_range_op.mlir
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
In this PR I have implemented the lowering code from the Onnx dialect to the Krnl dialect for the `CategoryMapper` operation.  The codegen supports `CategoryMapper` operators that have either a tensor of strings or a tensor of int64_t as their input. I have introduced a `krnl.string` custom type which is used to lower the existing `onnx.String` type. 
> CategoryMapper Onnx to Krnl lowering.

- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp
- src/Dialect/Krnl/KrnlHelper.cpp
- src/Dialect/Krnl/KrnlHelper.hpp
- src/Dialect/Krnl/KrnlTypes.hpp
- src/Runtime/CMakeLists.txt
- src/Runtime/OMIndexLookup.c
- src/Runtime/OMIndexLookup.cpp
- src/Runtime/OMIndexLookup.inc
- src/Support/KrnlSupport.cpp
Lowering CategoryMapper from Krnl to LLVM. This PR contains part 1 of the necessary code.
> Infrastructure for lowering to LLVM CategoryMapper.

- src/Conversion/KrnlToLLVM/CMakeLists.txt
- src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
- src/Conversion/ONNXToKrnl/CMakeLists.txt
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- test/mlir/onnx/onnx_lowering.mlir
Before this patch, `math.tanh` is expanded into `math.exp`, `math.sub`, `math.add`, and `math.div` by calling `populateExpandTanhPattern`, which is not efficient.
This patch calls `populateMathPolynomialApproximationPatterns` that does polynomial approximation, which leads to better inference performance.
Another difference is that `populateMathPolynomialApproximationPatterns` works with vector type while `populateExpandTanhPattern` does not.
LSTM and GRU use `math.tanh` as an activation, so they would become a little faster.
`populateMathPolynomialApproximationPatterns` also supports sin, cos, log, and exp.
> Use polynomial approximation for tanh, sin, cos, log and exp

- src/Builder/FrontendDialectTransformer.cpp
This PR added the support to import seq type from onnx model.
1. Extend importTensorType to importType, which calls importTensorType and importSeqType according to the type.
2. Change function signature to allow seq type. The consumer of the signature need to be updated, too.
> import seq

- docs/_data/navigation.yml
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
This patch makes onnx-to-krnl patterns re-usable by grouping all patterns into a single function. Hence, the patterns can be called from a lowering pass in another project.
This patch also fixes a typo in a link in the onnxai webpage.
> Make onnx-to-krnl patterns re-usable

- src/Dialect/ONNX/IndexExpr.cpp
- test/mlir/onnx/onnx_shape_inference.mlir
Case is needed as sometimes instead of a 1D array, we just get a single value. Now the index capture of such 0D array is enabled.
> Index value capture for arrays of 0D

- src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
- test/mlir/krnl/krnl_C_library_function_lowering.mlir
- test/mlir/krnl/krnl_category_mapper.mlir
- test/mlir/onnx/onnx_lowering_category_mapper.mlir
This PR implements the support to lower the `CategoryMapper` operator from the Krnl dialect to the LLVM dialect. 
It also add LIT tests to verify that the operator is lowered to LLVM as expected.
> Category mapper lower to llvm part2

- MLIR.cmake
- src/Compiler/CMakeLists.txt
- src/Compiler/CompilerUtils.cpp
- src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
- test/mlir/module_op_be/module_op.mlir
- test/mlir/module_op_le/module_op.mlir
- test/mlir/onnx/onnx_location.mlir
This PR sets the datalayout for the generate LLVM IR module. The datalayout is set according to the effective value of the `triple`. used to compile the input MLIR file. With this PR:
```
% ./Debug/bin/onnx-mlir ~/tmp/test.mlir  --preserveBitcode
Shared library /Users/etiotto@ca.ibm.com/tmp/test.so has been compiled.
% ~/Source/onnx/llvm-project/build/bin/llvm-dis  ~/tmp/test.bc
% head  ~/tmp/test.ll 
; ModuleID = '/Users/etiotto@ca.ibm.com/tmp/test.bc'
source_filename = "LLVMDialectModule"
target datalayout = "e-m:o-p270:32:32-p271:32:32-p272:64:64-i64:64-f80:128-n8:16:32:64-S128"
target triple = "x86_64-apple-darwin20.6.0"
@c = internal constant [6 x i32] [i32 1, i32 2, i32 3, i32 4, i32 5, i32 6]
declare i8* @malloc(i64)
declare void @free(i8*)
```
> Generate datalayout in module.

- src/Builder/FrontendDialectTransformer.cpp
Fix missleading error message when bad path to onnx model is given.
Currently, if the given .onnx file can't be found the emitted error could be improved. For example: (note model should be resnet50-v1-7.onnx but I'm intentionally making a typo)
"onnx-mlir resnet50-v1.onnx"
Gives
"Onnx Model Parsing Failed on resnet50-v1.onnx"
This current error message is misleading, because it implies the model file was found but is bad or incompatible.
This PR changes the error message to "unable to open or access resnet50-v1.onnx".
Signed-off-by: Yasushi Negishi <negishi@jp.ibm.com>
> Fix missleading error message when bad path to onnx model is given

- CONTRIBUTING.md
- README.md
- docs/ConstPropagationPass.md
- docs/Workflow.md
- docs/docker-example/Dockerfile
- src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
Added a temporary warning on how to transition to using `main` branch (thanks Gong) and removed spurious reference to `master` branch, mostly in http addresses.
> removed reference to master where possible

- src/Compiler/CompilerUtils.cpp
Add optional wdir to exec() to allow running a command
in a specified work directory. This is used to get around
the problem that old ar command does not support the
--output option.
> Add optional wdir to exec()

- src/Dialect/Krnl/KrnlOps.td
I want to add `MemRefsNormalizable` trait in `krnl.matmul` to normalize memrefs in my use case. We usually add the trait every time we encounter a situation where it is needed.  I did this before in these PRs,  krnl.memcpy: https://github.com/onnx/onnx-mlir/pull/322,  krnl.getref: https://github.com/onnx/onnx-mlir/pull/327 .
However, this approach is ad-hoc and may introduce potential bugs (I created this PR because I have a use case where normalization didn't work). To avoid this, this PR creates base class for krnl ops and set `MemRefsNormalizable` trait by default in krnl ops.
Is this acceptable? If not, I will add the trait only in `krnl.matmul`.
> Added MemRefsNormalizable trants to krnl ops whose input or output has memref type

- src/Dialect/ONNX/CMakeLists.txt
- src/Dialect/ONNX/ShapeInference/LRN.cpp
The file for shape inference for LRN was wrongly named `RNN.cpp`. This patch changed it to `LRN.cpp`.
> Fix a wrong file name for LRN shape inference

- src/Compiler/CMakeLists.txt
- src/Runtime/CMakeLists.txt
- src/Runtime/PyExecutionSession.cpp
When running on ubi8 image, shared lib backend tests fail with the following error:
[libprotobuf ERROR google/protobuf/descriptor_database.cc:641] File already exists in database: onnx/onnx-ml.proto
[libprotobuf FATAL google/protobuf/descriptor.cc:1371] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
terminate called after throwing an instance of 'google::protobuf::FatalException'
what():  CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
Aborted (core dumped)
This is because test.py loads (among others) the following two .so shared libs:
- onnx_cpp2py_export.cpython-39-s390x-linux-gnu.so (import onnx)
- PyRuntime.cpython-39-s390x-linux-gnu.so (from PyRuntime import ExecutionSession)
Both libs share the same libprotobuf.so when loaded by …
> PyRuntime shared lib protobuf error fix

- src/Compiler/CompilerUtils.cpp
- test/backend/test.py
Add an `onnx-mlir` option to select the optimization level to use when compiling input files. Use the same optimization level to invoke  LLVM's `opt` and `llc`. The default optimization level, if unspecified, is -O0. 
> Add optimization level to onnx-mlir

- src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
- test/mlir/krnl/krnl_category_mapper.mlir
- test/mlir/krnl/krnl_global_with_alignment_lowering.mlir
If `krnl.global` does not have an explicit alignment attribute sets the alignment based on the module's datalayout attribute (if present).
> Set krnl.global alignment using module datalayout if present

- test/numerical/CMakeLists.txt
> Now that O0 is default for models, force numerical to use O3 opt level

- utils/RunONNXModel.py
Fixes #1038 And helps prevent #1041
> Informative messages in `utils/RunONNXModel.py` to help locate PyRuntime.so

- src/Compiler/CompilerUtils.cpp
- test/mlir/driver/unix/check_verbosity.mlir
- test/mlir/driver/windows/check_verbosity.def
- test/mlir/driver/windows/check_verbosity.mlir
- test/mlir/onnx/onnx_location.mlir
Add an option (-v) to print out the commands the `onnx-mlir` driver invokes.
> Add -v option to onnx-mlir

- src/Compiler/CompilerUtils.cpp
- src/Compiler/CompilerUtils.hpp
This PR splits `compileModule()` into three routines (`setupModule()`, `addPasses()`, and `emitOutput()`) to improve reusability.
My use case will reuse `setupModule()` and `emitOutput()` and replace `addPasses()` to add my own passes.
> Split compileModule() to improve reusability

- src/Dialect/Krnl/KrnlOps.td
`krnl.vector_type_cast` op is a view of the source memref, so this patch adds ViewLikeOpInterface to it. 
Though the current onnx-mlir has no problem since `krnl.vector_type_cast` is only used inside MatMul, this change helps buffer-related passes correctly analyze buffer's lifetime when `krnl.vector_type_cast` is used more often.
> Add ViewLikeOpInterface to krnl.vector_type_cast

- README.md
On Mac OS I was not able to run `make check-onnx-backend` due to the following error: 
```
Fatal Python error: Aborted
Current thread 0x0000000107919e00 (most recent call first):
File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 2632 in getproxies_macosx_sysconf
File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 2650 in getproxies
File "/usr/local/Cellar/python@3.9/3.9.7/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 795 in __init__
...
```
I found a workaround that might be useful to others.
> Document Mac OSX workaround for check-onnx-backend.

- src/Support/OMOptions.cpp
Just fix help statement for `--enable-memory-bundling` option. This is update of  https://github.com/onnx/onnx-mlir/pull/1062
> Fix help statement for enable-memory-bundling

- CONTRIBUTING.md
- docs/DebuggingNumericalError.md
- docs/ImportONNXDefs.md
- include/onnx-mlir/Runtime/OnnxDataTypeMetaData.inc
- src/Conversion/ONNXToKrnl/Math/Softmax.cpp
- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/Rewrite.td
- src/Dialect/ONNX/ShapeInference/ONNXShapeHelper.cpp
- src/Runtime/jni/src/com/ibm/onnxmlir/OMTensor.java
- src/Transform/ONNX/ConstProp.cpp
- test/backend/inference_backend.py
- test/numerical/TestConv.cpp
Now that [onnx switched from master to main](https://github.com/onnx/onnx/issues/3901), update URLs in onnx-mlir to also reflect the change.
Also remove some extraneous whitespace that my editor caught in the updated files.
> Switch URLs to use main instead of master

- docker/onnx-mlir.py
onnx-mlir.py warning about binary output (.so and .jar) not directly usable if host is not Linux
> onnx-mlir.py warning about binary output

- docs/Docker.md
- docs/docker-example/Dockerfile
1. Fix some typo in the `docker.md` file, and add `.` (path) to `docker build --tag onnx-mlir-dev .` command.
2. Install `ssh-client` as it is required when using `git fetch`.
> fix typos and add ssh-client to dockerfile

- README.md
- docker/onnx-mlir.py
- include/onnx-mlir/Compiler/OMCompilerTypes.h
- src/Compiler/CompilerUtils.cpp
- src/Compiler/CompilerUtils.hpp
- src/Compiler/OnnxMlirCompiler.cpp
- src/main.cpp
- test/backend/common.py
Add the `--emitObj` option to `onnx-mlir`. This option stops the compiler after an object is created (skips the link step).
> Add an option to stop compilation after objects are created.

- src/Compiler/CompilerUtils.cpp
- src/Compiler/CompilerUtils.hpp
Some functions to be shared among drivers based on onnx-mlir was made static by this PR  https://github.com/onnx/onnx-mlir/pull/1104.
This patch reverses them back so that other drivers can call them.
> Reverse some static functions to make them sharable

- src/Conversion/KrnlToAffine/KrnlToAffine.cpp
- src/Transform/BundleMemoryPools.cpp
- src/Transform/DisconnectKrnlDimFromAlloc.cpp
- src/Transform/ElideKrnlGlobalConstants.cpp
- src/Transform/EnableMemoryPool.cpp
- src/Transform/LowerKrnlShape.cpp
- src/Transform/ONNX/ConstProp.cpp
- src/Transform/ONNX/Decompose.cpp
- src/Transform/ONNX/ElideConstants.cpp
- src/Transform/ONNX/InstrumentONNXPass.cpp
- src/Transform/ONNX/ONNXPreKrnlVerifyPass.cpp
- src/Transform/ONNX/ShapeInferencePass.cpp
- src/Transform/OptimizeMemoryPools.cpp
Replace usage of FunctionPass with OperationPass<FuncOp> within ONNX-MLIR.
This change is motivated by the deprecation of FunctionPass as described here: https://llvm.discourse.group/t/functionpass-deprecated-in-favor-of-operationpass-funcop/5808
> Remove Usage of Deprecated FunctionPass

- CMakeLists.txt
This adds an option `ONNX_MLIR_ENABLE_WERROR` to enable warnings as errors in onnx-mlir. Its implementation is built on `LLVM_ENABLE_WERROR` and is constructed in such a way as it stops `LLVM_ENABLE_WERROR` from working (developers must set `ONNX_MLIR_ENABLE_WERROR`)
The new option `ONNX_MLIR_ENABLE_WERROR` defaults to `OFF`
> Add Option to Enable Warnings as Errors

- test/modellib/CMakeLists.txt
- test/numerical/CMakeLists.txt
`ModelLib` already has a dependency on `ExecutionSession` and `CompilerUtils`. By making the dependency public, it can propagate to other targets simplifying the dependency chain.
> Small dependency optimization for ModelLib

- src/Compiler/CompilerUtils.cpp
- src/Tool/ONNXMLIROpt/ONNXMLIROpt.cpp
- src/main.cpp
MLIR has an infrastructure that is useful to time compiler passes (see section `Pass Timing` in https://mlir.llvm.org/docs/PassManagement). This PR allows `onnx-mlir` and `onnx-mlir-opt` to report timing information by leveraging the MLIR pass timing infrastructure. Here is an example:
```
% onnx-mlir ~/Downloads/gpt2-lm-head-10/GPT-2-LM-HEAD/model.onnx -mlir-timing  -mlir-timing-display=list
===-------------------------------------------------------------------------===
... Execution time report ...
===-------------------------------------------------------------------------===
Total Execution Time: 125.6608 seconds
----Wall Time----  ----Name----
125.6608 (100.0%)  root
57.6053 ( 45.8%)  (anonymous namespace)::ONNXOpTransformPass
0.9355 (  0.7%)  (anonymous …
```
> Allow onnx-mlir, onnx-mlir-opt to use MLIR's timing infrastructure.

- src/Compiler/CompilerUtils.cpp
- src/Compiler/CompilerUtils.hpp
This patch allows other drivers to use the OptLevel option.
> Make OptLevel option sharable

- include/onnx-mlir/Compiler/OMCompilerTypes.h
- src/Compiler/CompilerUtils.cpp
- test/mlir/driver/check_passthrough_options.mlir
There are scenarios where a user of `onnx-mlir` might need to tune the behaviour of the LLVM `opt` and/or `llc` components.  This PR introduces three new options:
- -Xopt <valid opt's flag> -- the flag will be passed to `opt`
- -Xllc <valid llc's flag> -- the flag will be passed to `llc`
- -mllvm <valid opt and llc flag> -- the flag will be passed to both `opt` and `llc`
> Introduce onn-mlir options -Xopt, -Xllc, and -mllvm

- include/onnx-mlir/Runtime/OMTensor.h
- src/Runtime/OMTensor.inc
- src/Runtime/OMTensorHelper.h
- test/backend-cpp/TestCategoryMapper.cpp
In this PR I generalized the test infrastructure for the CategoryMapper operator by providing templated functions to cut down on code duplication. As a side effect I modified the runtime interfaces for querying OMTensor properties to pass input OMTensor(s) with `const`.
> Generalize CategoryMapper test.

- docs/BuildOnLinuxOSX.md
- docs/BuildOnWindows.md
- src/Compiler/CompilerUtils.cpp
- src/Compiler/CompilerUtils.hpp
- src/Conversion/KrnlToLLVM/CMakeLists.txt
- src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
- src/InitMLIRPasses.hpp
- utils/clone-mlir.sh
This PR updates the LLVM level used by `onnx-mlir`.  Changes in MLIR that required corresponding changes in `onnx-mlir` are: 
- https://reviews.llvm.org/D118966 (Split out a new ControlFlow dialect from Standard)
Signed-off-by: Ettore Tiotto <etiotto@gmail.com>
> Update LLVM to b3b129f11f3c.

- src/Dialect/Krnl/Krnl.td
- src/Dialect/Krnl/KrnlOps.cpp
- src/Dialect/ONNX/AdditionalONNXOps.td
- src/Dialect/ONNX/ONNX.td
- src/Dialect/ONNX/ONNXOps.cpp
Several properties (such as verifier, printer & parser) are going to be obsolete in main mlir soon. This change removes the explicit usage of verifier and instead uses the `hasVerifier` option instead.
Also, some minor whitespace cleanup.
> Remove explicit verifier usage as it is about to be obsolete

- docs/DebuggingNumericalError.md
- include/onnx-mlir/Runtime/OMTensor.h
- include/onnx-mlir/Runtime/OnnxDataType.h
- include/onnx-mlir/Runtime/OnnxDataTypeMetaData.inc
- src/Conversion/KrnlToLLVM/CMakeLists.txt
- src/Conversion/KrnlToLLVM/KrnlPrint.cpp
- src/Conversion/KrnlToLLVM/KrnlPrint.hpp
- src/Conversion/KrnlToLLVM/KrnlPrintTensor.cpp
- src/Conversion/KrnlToLLVM/KrnlPrintTensor.hpp
- src/Conversion/KrnlToLLVM/KrnlToLLVM.cpp
- src/Conversion/KrnlToLLVM/KrnlToLLVMHelper.cpp
- src/Conversion/KrnlToLLVM/KrnlToLLVMHelper.hpp
- src/Conversion/KrnlToLLVM/RuntimeAPI.cpp
- src/Conversion/ONNXToKrnl/ML/CategoryMapper.cpp
- src/Dialect/Krnl/Krnl.td
- src/Dialect/Krnl/KrnlHelper.cpp
- src/Dialect/Krnl/KrnlHelper.hpp
- src/Runtime/OMTensor.inc
- src/Runtime/OMTensorHelper.h
- src/Runtime/OnnxDataType.inc
This PR introduces the ability to generate a call to a runtime function `omTensorPrint` while generating code. This function allows printing the content of the supplied tensor. This is intended as an aid for debugging runtime failures.
To use it write:
``` 
LLVM_DEBUG(llvm::dbgs() << "Input tensor:\n"; create.krnl.printTensor(X););
```
In addition is sometime useful to print a primitive value at some program point in the code generated. For that purpose I have also introduced the `krnlPrintOp` Krnl dialect operator. This operator is lowered to a call to `printf` with the appropriate format specifier for the value to be printed. 
To use it write:
```
create.krnl.printf("inputElem: ", inputElem, elementType);
```
where `inputElem` is the value to be printed, and `elementType` is the type of …
> Add OMTensorPrint and KrnlPrintTensorOp

- docs/BuildOnLinuxOSX.md
- docs/BuildOnWindows.md
- src/Dialect/Krnl/Krnl.td
- src/Dialect/Krnl/KrnlOps.cpp
- utils/clone-mlir.sh
This updates LLVM to commit d7f0083d (just about a day ahead from the existing commit) when parser and printer were made obsolete. Then we leverage the new `hasCustomAssemblyFormat` property to replace parser and printer.
> Update LLVM to commit d7f0083d and remove explicit usage of parser and printer

- docs/doc_check/CMakeLists.txt
- src/Builder/CMakeLists.txt
- src/Builder/OpBuildTable.inc.dc
- src/Builder/OpBuildTable.inc.dc.in
- src/Dialect/ONNX/CMakeLists.txt
- src/Dialect/ONNX/ONNXOps.td.inc.dc
- src/Dialect/ONNX/ONNXOps.td.inc.dc.in
In our team's subtree-merge of onnx-mlir, we configure a venv to give us precise control over the python configuration without messing with the system/user python install. The check-doc target fails in this mode, because it defaults to the python in the path. There are a couple of ways to resolve this: one would be to run the tests with 'cmake -E env' and inject the python dir at the head of the PATH. This has insidious potential side effects, as the test will always run with the value of PATH as it was at configure time. Subsequent changes to the PATH in a shell window will have no effect without rebuilding the cmake cache, and then _those_ changes will persist until the next cache rebuild.
The other approach, which is what I've implemented here, is to render the doc-check file as cmake …
> Force check-doc to use Python3_EXECUTABLE

- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXOps.td.inc
- utils/gen_onnx_mlir.py
`verifier` will be obsolete soon to be replaced by `hasVerifier`. This updated the script to use the new form and then applies the updates to the appropriate files.
> Update gen_onnx_mlir.py to use the new hasVerifier form

- docs/BuildOnLinuxOSX.md
- docs/BuildOnWindows.md
- src/Conversion/ONNXToKrnl/ControlFlow/Loop.cpp
- src/Conversion/ONNXToKrnl/Math/Reduction.cpp
- src/Conversion/ONNXToKrnl/NN/Pooling.cpp
- src/Conversion/ONNXToKrnl/Tensor/ArgMax.cpp
- src/Conversion/ONNXToKrnl/Tensor/Range.cpp
- src/Conversion/ONNXToKrnl/Tensor/Resize.cpp
- src/Conversion/ONNXToKrnl/Tensor/Tile.cpp
- src/Dialect/Krnl/KrnlOps.cpp
- src/Dialect/ONNX/MLIRDialectBuilder.cpp
- src/Dialect/ONNX/ONNX.td
- src/Support/KrnlSupport.cpp
- src/Transform/BundleMemoryPools.cpp
- utils/clone-mlir.sh
Ths PR updates the LLVM commit we use to `a7ac120a9ad784998a5527fc0a71b2d0fd55eccb`.
> update llvm to a7ac120a9ad7

- src/Conversion/KrnlToLLVM/ConvertKrnlToLLVM.cpp
- src/Conversion/KrnlToLLVM/ConvertKrnlToLLVM.hpp
> Make checkConstantOutputs and populateAffineAndKrnlToLLVMConversion sharable for other drivers

- src/Compiler/CompilerUtils.cpp
- test/mlir/driver/llvm.ident.mlir
> Emit the onnx-mlir version as llvm.ident metadata.

- include/OnnxMlirCompiler.h
- src/Compiler/CMakeLists.txt
When OnnxMlirCompiler is a static lib, the functions should not be marked for dllexport or dllimport.
> Correctly build OnnxMlirCompiler as a static lib

- src/Compiler/CMakeLists.txt
- test/mlir/driver/llvm.ident.mlir
- test/mlir/driver/llvm.ident.mlir.def
- version/AddLLVMVersionHeader.cmake
- version/CMakeLists.txt
Right now the version is only appended when the source is explicitly available. This is not always the case since onnx-mlir can be built against a build directory as well as against an install directory of llvm. This change tries to check for the llvm source version and if it not found, includes the VCSRevision.h header generated by llvm instead.
> Add the llvm source version to VCSVersion.inc even if we don't have access to the llvm source

- src/Accelerators/CMakeLists.txt
The Accelerators project pulls in some headers that are table-gen generated in llvm-project/mlir. Add an explicit dependency so parallel building works correctly.
Signed-off-by: Ian Bearman <ianb@microsoft.com>
> Fix Missing Dependency

- src/Accelerators/Accelerator.hpp
- src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
- src/Accelerators/NNPA/Compiler/NNPACompilerUtils.hpp
- src/Accelerators/NNPA/NNPAAccelerator.cpp
- src/Accelerators/NNPA/NNPAAccelerator.hpp
Options for NNPA in command `onnx-mlir` like `--EmitZHighIR`, `--EmitZLowIR` do not work because `onnx_mlir::EmissionTargetType` is not modified to stop compilation when NNPA options exist. This patch fixes that issue and makes the options work.
> Make NNPA-related options work

- .gitignore
- CMakeLists.txt
- src/Builder/OpBuildTable.inc.dc.in
- src/Dialect/ONNX/ONNXOps.td.inc.dc.in
- utils/CMakeLists.txt
Changes required to support use cases where onnx-mlir and llvm-project/mlir are generated together.
> [cmake] Support generating onnx-mlir with mlir

- src/Accelerators/NNPA/Transform/ZHigh/Stickify/Stickify.cpp
- src/Runtime/jni/jniwrapper.c
This PR fixes the following compiler warnings: 
- jniwrapper.c:755:28: warning: format specifies type 'ssize_t' (aka 'long') but the argument has type 'int64_t' (aka 'long long') [-Wformat]
-  Stickify.cpp:201:3: warning: default label in switch which covers all enumeration values [-Wcovered-switch-default]
- Stickify.cpp:218:3: warning: default label in switch which covers all enumeration values [-Wcovered-switch-default]
- Stickify.cpp:286:3: warning: default label in switch which covers all enumeration values [-Wcovered-switch-default]
- Stickify.cpp:404:3: warning: default label in switch which covers all enumeration values [-Wcovered-switch-default]
> [NFC]: Fix warnings in Stickify.cpp and jniwrapper.c

- src/Conversion/ONNXToKrnl/Math/Reduction.cpp
- src/Dialect/ONNX/CMakeLists.txt
- src/Dialect/ONNX/ShapeInference/ONNXShapeHelper.cpp
- src/Dialect/ONNX/ShapeInference/ONNXShapeHelper.hpp
- src/Dialect/ONNX/ShapeInference/Reduction.cpp
- test/mlir/onnx/onnx_lowering.mlir
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
This PR updates code generation for `reduction.cpp` to use the builder based interfaces for generation of Krnl loops.
> [Reduction] Use builder based interface to generate Krnl loops

- src/Accelerators/NNPA/Transform/ZHigh/Stickify/Stickify.cpp
- src/Runtime/jni/jniwrapper.c
```
onnx-mlir/src/Accelerators/NNPA/Transform/ZHigh/Stickify/Stickify.cpp:204:1: warning: control reaches end of non-void function [-Wreturn-type]
onnx-mlir/src/Accelerators/NNPA/Transform/ZHigh/Stickify/Stickify.cpp:219:1: warning: control reaches end of non-void function [-Wreturn-type]
onnx-mlir/src/Runtime/jni/jniwrapper.c:755:24: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 3 has type ‘int64_t’ {aka ‘long int’} [-Wformat=]
```
> Fix warnings in onnx-mlir

- src/Runtime/jni/jniwrapper.c
When Java API inputSignature()/outputSignature() calls
input_signature_jni("run_main_graph")/output_signature_jni("run_main_graph"),
"run_main_graph" needs to be converted from ASCII to EBCDIC before being
fed into omInputSignature(epptr)/omOutputSignature(epptr)
> Fix JNI wrapper entry point name encoding on z/OS

- CMakeLists.txt
- src/Compiler/CMakeLists.txt
- src/Compiler/CompilerUtils.cpp
- test/mlir/driver/llvm.ident.mlir
- test/mlir/lit.cfg.py
- test/mlir/lit.site.cfg.py.in
This change adds a `PACKAGE_VENDOR` variable. When set it makes the version output more closely resemble the `onnx-mlir` version output. The idea came from llvm-project: https://github.com/llvm/llvm-project/blob/ceadf6ee619ce610b269459b129996c4ac7173cb/clang/CMakeLists.txt#L340.
For example, when building with `-DPACKAGE_VENDOR="XL for Linux on Power"`, 
then output LLVMIR contains:
```
!llvm.ident = !{!0}
!0 = !{!"XL for Linux on Power, onnx-mlir version 1.0.0"}
```
> `-DPACKAGE_VENDOR` can be used to show vendor-specific text as version information

- src/Dialect/ONNX/Rewrite.cpp
- src/Dialect/ONNX/Rewrite.td
- test/mlir/onnx/onnx_canonicalization.mlir
This patch adds on canonicalization rule to ONNXTranposeOp which does tranpose on concat's inputs instead of output.
> Do transpose on concat's inputs instead of output

- src/Accelerators/Accelerator.hpp
cppcheck verifier had an issue with the unconventional c++ code generated by the macro extensions. This PR trivially eliminates the issue. Also added "NONE" first so as to have a constant value for NONE regardless of the numbers of accelerators present in the cmake customization.
> moved none first, with comment to make verifier happy

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/conv.mlir
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/gemm.mlir
This patch allows lowering ONNXGemm to ZHigh in case of dynamic dimensions. However, if the 1D bias has unknown dimension, we do not allow lowering because we cannot check it is broadcasting or not. 
This patch also fixes a condition for zDNN Conv2D where `height_input` should be "greater than or equal to" instead of just "greater than" `height_kernel`. Similarly for `width_input` and `width_kernel`.
> Allow lowering ONNXGemm with dynamic dims to ZHigh and fix zDNN Conv condition

- src/Conversion/KrnlToAffine/ConvertKrnlToAffine.cpp
- src/Conversion/KrnlToAffine/ConvertKrnlToAffine.hpp
- src/Dialect/Krnl/KrnlTypes.cpp
- test/mlir/conversion/krnl_to_affine/krnl_to_affine_with_canonicalize.mlir
- test/mlir/krnl/krnl_math_function_lowering.mlir
Resolves #1355 : `--convert-krnl-to-affine` pass does not support MemRefType with affine map. This is because it uses LLVMTypeConverter. This patch replaces LLVMTypeConverter by a custom one which simply forwards the type because MemRefType is used both before and after  `--convert-krnl-to-affine`
> Support MemRefs with affine_map in --convert-krnl-to-affine

- src/Dialect/ONNX/Rewrite.cpp
> Fix an issue in function areProducedByTransposeOp when input is a block argument

- test/modellib/LSTMModel.cpp
- test/modellib/ModelLib.hpp
- test/numerical/TestLSTM.cpp
In ONNX LSTM, `initial_h`, `initial_c`, and `P` are optional, but numerical tests didn't test the cases where these parameters are not specified. They always uses tensors with random values. This PR enables the tests with none value for them.
I need these tests for LSTM for NNPA. LSTM op in the zDNN library used in NNPA only supports LSTM whose weight tensor for peepholes is not specified.
Following tests are newly added as an example.
```
func @main_graph(%arg0: tensor<3x3x2xf32>, %arg1: tensor<1x3x2xf32>, %arg2: tensor<1x\
3x2xf32>) -> (tensor<3x1x3x2xf32>, tensor<1x3x2xf32>, tensor<1x3x2xf32>) {
%0 = "onnx.NoValue"() {value} : () -> none
:
%Y, %Y_h, %Y_c = "onnx.LSTM"(%arg0, %1, %2, %3, %0, %0, %0, %0) {direction = "forwa\
rd", hidden_size = 2 : si64, input_forget = 0 : si64} : …
```
> Enable numerical tests for LSTM whose initial_h, initial_c, and P are not specified

- CMakeLists.txt
- MLIR.cmake
- docker/Dockerfile.onnx-mlir
- docker/Dockerfile.onnx-mlir-dev
- docs/BuildOnLinuxOSX.md
- src/Accelerators/CMakeLists.txt
- src/Accelerators/NNPA/CMakeLists.txt
- src/Accelerators/NNPA/zdnn.cmake
- test/mlir/CMakeLists.txt
- test/mlir/accelerators/CMakeFiles.txt
- test/mlir/lit.site.cfg.py.in
- utils/install-onnx-mlir.sh
- force setting cached MLIR_DIR to honor command line argument
- unset cached LLVM_DIR so it changes along with MLIR_DIR
- surround third_party with set(CMAKE_MESSAGE_LOG_LEVEL NOTICE) and
set(CMAKE_MESSAGE_LOG_LEVEL STATUS) to mask out their cmake
output so we can see more clearly output by onnx-mlir only.
third_party cmake output can still be turned on by the --log-level
command line option
- rename cmake option ACCELERATORS_TO_BUILD to ONNX_MLIR_ACCELERATORS
for consistency
- allow accelerator lit tests even if accelerator code itself
cannot be built
- fix bug in zdnn.cmake where ar was run even though libzdnn.so was
already up to date, causing concurrent builds to corrput libzdnn.a
> Misc cmake updates

- docs/Testing.md
Doc currently does not indicate how to re-run a numerical test while generating the same configurations as in a prior run. This ability is super useful, and is now properly documented.
> Added explanations to rerun a numerical test

- src/Builder/FrontendDialectTransformer.cpp
- src/Builder/OpBuildTable.inc
- utils/gen_onnx_mlir.py
The type inference for CategoryMapper in model importer is a special case: The element type of the output type is I64 if the input is string type, or string type if the input is I64 type. onnx-mlir did not handle such case. 
The fix is use a specialized importer for CategoryMapper to determine the output type. Pass the result to the type inference for the output tensor with an added parameter. 
With this PR, bidalf-9.onnx can be parsed by onnx-mlir. Now I got error related to shape inference: 
```
error: Invalid axis value
error: shape inference failed
```
> Fix output type when CategoryMapper is imported

- src/Dialect/Krnl/Krnl.td
Krnl operations whose inputs or outputs are of MemRefType have MemRefNormalizable trait, but the newly added KrnlSeqExtractOp is missing. This patch is to add the trait to KrnlSeqExtractOp.
> Add MemRefNormalizable trait to the newly added KrnlSeqExtractOp

- src/Conversion/ONNXToKrnl/Math/Gemm.cpp
- src/Conversion/ONNXToKrnl/NN/Conv.cpp
- src/Conversion/ONNXToKrnl/NN/Normalization.cpp
- src/Conversion/ONNXToKrnl/NN/Pooling.cpp
- src/Conversion/ONNXToKrnl/ObjectDetection/NonMaxSuppression.cpp
- src/Conversion/ONNXToKrnl/Tensor/NonZero.cpp
- src/Dialect/Mlir/DialectBuilder.hpp
- test/mlir/onnx/onnx_lowering.mlir
- test/mlir/onnx/onnx_lowering_nonmaxsuppression_op.mlir
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
According to https://llvm.org/docs/LangRef.html#alloca-instruction, the `alloca` instruction allocates memory on the stack frame of the currently executing function, to be automatically released when this function returns to its caller. 
We can avoid over allocing by placing `alloca` instruction at the function scope and outside of any loops. This change is motivated by https://github.com/onnx/onnx-mlir/issues/1061, where models segfault at runtime when compiling at `-O0`, due to run out of stack space.
An alternative is to hoist allocation out of loops after creation with `--buffer-hoisting`: https://mlir.llvm.org/docs/Passes/#-buffer-hoisting-optimizes-placement-of-allocation-operations-by-moving-them-into-common-dominators-and-out-of-nested-regions, as suggested in …
> Create alloca outside of loops

- src/Accelerators/NNPA/Runtime/OMRuntimeNNPA.c
- src/Conversion/KrnlToLLVM/KrnlEntryPoint.cpp
- src/Runtime/ExecutionSession.cpp
- test/mlir/krnl/entry_point.mlir
This patch edits the generated entry points, e.g. `run_main_graph` to return NULL when initializing an accelerator fails.
This patch based on PR #1426 (most of the changes are from #1426), so #1426 should be merged first.
> Edit entry points to return NULL if failed to initialize accelerators

- src/Accelerators/NNPA/NNPAAccelerator.cpp
- src/Compiler/CompilerOptions.cpp
- fix ordering of RuntimeNNPA and zdnn when calling addCompilerConfig
- don't use set_union since it sorts the vector
> Fix RuntimeNNPA and zdnn dependency order

- CHANGELOG.md
- docs/docker-example/.vscode/launch.json
- src/Compiler/CompilerUtils.cpp
- test/mlir/driver/llvm.ident.mlir
Move `onnx-mlir` version to `0.3.0` from `0.2.0`. `1.0.0` was a mistake.
> Move onnx-mlir version to 0.3.0

- .azure-pipelines/Windows-CI.yml
- docs/BuildOnWindows.md
- utils/build-onnx-mlir.cmd
- utils/install-protobuf.cmd
This updates the protoc binary build to 3.16.0 and then installs the corresponding pip package.
3.16.0 is the recommended (though not minimum required) version of protobuf for onnx 1.11.0
> Force protobuf 3.16.0 on Windows

- src/Dialect/ONNX/Rewrite.cpp
- test/mlir/onnx/onnx_canonicalization.mlir
This patch uses the ceiling value when computing a max trip count for ONNXLoopOp to make sure the number of iterations is NOT decreased compared to the actual trip count.
This patch also removes a redundant function.
> Use the ceiling value when deriving a max trip count for ONNXLoopOp

- CONTRIBUTING.md
- README.md
- docs/Workflow.md
New contributors often miss the DCO requirements. Added it more visibly in our doc.
> Doc fix for DCO

- test/compilerlib/CompilerLibTest.cpp
I got an error in backend test for compilerlib when used following command. The error issued because `--EmitLib` is not supported in `CompilerLibTest`. Since `--EmitLib` is default option, we don't have to pass it.
This PR ignores the option by using similar way with other options.  
- Command
```
cmake --build . --config Release --target check-onnx-backend-compilerlib
```
- Error message 
```
CompilerLibTest: Unknown command line argument '--EmitLib'.  Try: '/home/imaihal/work/onnx-mlir/build/Debug/bin/CompilerLibTest --help'
CompilerLibTest: Did you mean '--EmitZLowIR'?
Test info:
temporary results are in dir:/tmp/tmp4q6xlu_9/
Failed /home/imaihal/work/onnx-mlir/build/Debug/bin/CompilerLibTest: test_abs
: 
: 
```
> Fix an error in check-onnx-backend-compilerlib

- src/Version/CMakeLists.txt
If onnx-mlir is being built as a sub-project, `CMAKE_SOURCE_DIR` will point to the parent's top-level directory, rather than onnx-mlir's top-level directory. This can can cause issues finding the `VERSION_NUMBER` file.
> Use ONNX_MLIR_SRC_ROOT to find the version file

- src/Compiler/CompilerPasses.cpp
- test/mlir/driver/buffer_loop_hoisting.mlir
According to https://llvm.org/docs/LangRef.html#alloca-instruction, the alloca instruction allocates memory on the stack frame of the currently executing function, to be automatically released when this function returns to its caller.
We can avoid over allocing by placing alloca instruction at the function scope and outside of any loops. 
https://github.com/onnx/onnx-mlir/pull/1397 and https://github.com/onnx/onnx-mlir/pull/1437 attempted to create the allocas outside of loops directly. However, it is not always possible to create outside of the whole loop nest. For example, when lowering an operation that is already in a loop nest, or when the outer loop is only created after the placement of the alloca. 
This PR adds BufferLoopHoistingPass after LowerAffinePass to hoist allocations out …
> Add BufferLoopHoistingPass after LowerAffinePass

- src/Dialect/Krnl/Krnl.td
- src/Dialect/Krnl/KrnlOps.cpp
- src/Dialect/Mlir/DialectBuilder.cpp
- test/mlir/onnx/onnx_lowering.mlir
`MathBuilder::positiveInf` and `MathBuilder::negativeInf` use `type.isSigned` to check an integer type, but the correct one should be `type.isSignlessInteger`.
This patch also adds op name in KrnlInstrumentOp, which helps know from which ONNX op the code is generated.
Resolves #1270 
> Fix a bug in MathBuilder::positiveInf and MathBuilder::negativeInf

- utils/RunONNXModelZoo.py
This patch adds some small changes to RunONNXModelZoo.py, where:
- Use `test_data_set_0` for each model since other datasets, e.g. `test_data_set_1`, `test_data_set_1` are sometimes ill-formed. For example,`test_data_set_1` of `ssd_mobilenet_v1_10` contains `input_1.pb` instead of `input_0.pb` (The input index should start from 0).
- Print the date time when the HTML output is generated for each model's output.
> Run the onnx model zoo with test_data_set_0 by default

- src/Compiler/CompilerUtils.cpp
PR #1463 accidentally removed `.` (dot) in the output file name when `--EmitMLIR`.  This patch adds dot back.
> Missing dot in the output file name

- src/Accelerators/CMakeLists.txt
This PR includes a minor fix to one of the cmake files to support enabling multiple accelerators. Previously, the build system would fail if one added a new accelerator in `src/Accelerators/XXX` and enabled it in addition to `NNPA` via `-DONNX_MLIR_ACCELERATORS="NNPA;XXX"`
> Add fix to cmake file for multiple accelerators

- src/Runtime/OMResize.inc
motivation and explanation is provided on issue #1504 
> fix size of coeffs_buffer to 4, what was actually allocated

- utils/RunONNXModelZoo.py
[A recent commit in onnx](https://github.com/onnx/models/pull/534) updates some broken test_data_sets including `t5-decoder-with-lm-head-12`, `t5-encoder-12`.
This patch updates the configuration for `t5-decoder-with-lm-head-12`, `t5-encoder-12` to use the provided test_data_set instead of randomly generate input data by passing shape_info.
With this patch, `t5-decoder-with-lm-head-12`, `t5-encoder-12` are now passed.
> Update t5-encoder model accoring to the latest onnx model zoo

- src/Conversion/KrnlToLLVM/ConvertKrnlToLLVM.cpp
- src/Conversion/KrnlToLLVM/KrnlEntryPoint.cpp
- src/Dialect/Mlir/DialectBuilder.cpp
- src/Dialect/Mlir/DialectBuilder.hpp
- test/backend/input_verification_backend.py
- test/mlir/krnl/entry_point.mlir
- test/mlir/krnl/input_verification.mlir
Thi patch continues PR #1498 and creates a helper function IfThenElse in LLVMBuilder.
This patch also adds a check to verify non-negative dimensions of the input tensors, reported here #1506
> Use LLVMBuider to simplify generating LLVM code - Part 2

- src/Accelerators/NNPA/Conversion/ZLowToLLVM/CMakeLists.txt
- src/Accelerators/NNPA/Conversion/ZLowToLLVM/ZLowToLLVM.cpp
- src/Accelerators/NNPA/Conversion/ZLowToLLVM/ZLowToLLVMCommon.cpp
This patch uses LLVMBuilder in NNPA accelerator code. It is the finally patch about creating LLVMBuilder and using it in onnx-mlir.
> Use LLVMBuider to simplify generating LLVM code - Part 3 (final)

- src/Compiler/CompilerUtils.cpp
- src/Compiler/CompilerUtils.hpp
When using `--EmitONNXBasic`, `--EmitONNXIR`, `--EmitMLIR`, a `.tmp` file is generated where ONNXConstantOp and KrnlGlobalOp are elided so that the generated file is small and easy to examine. However, the current approach is specific to ONNXConstantOp and KrnlGlobalOp, which is not scalable if, say, an accelerator has a new kind of constant op.
This patch uses another approach that just simply set the flag `elideLargeElementsAttrs` of OpPrintingFlags, so that all Attribute (no matter of which operation) will be elided. It should work for every operation.
> Elide constant operations by setting elideLargeElementsAttrs of OpPrintingFlags

- src/Conversion/ONNXToKrnl/ControlFlow/Loop.cpp
- test/mlir/onnx/onnx_lowering.mlir
- test/numerical/TestLoop.cpp
There are two optional control variable for onnx.LoopOp:  induction variable and termination condition. When LoopOp is controlled by induction variable, onnx.LoopOp can be lowered to krnl.iterate. Otherwise, SCF.While has to be lowered to SCF.While.
This PR implemented the lowering ONNX Loop to SCF.While. 
First, condition of LoopOp is checked to determine whether SCF.While is needed. 
Then the transformation is done in the similar way for krnl.iteration, but with duplicated code. There are three major differences in the code generation:
1. Induction variable has to be explicit in SCF.While, while it is implicit in krnl.iterate. This makes the list of block arguments and return is different.
2. The containing region is different.  In krnl.terate, the onnx loop body is inserted in to the …
> Lower LoopOp to SCF.While when condition is loop variant

- test/accelerators/NNPA/backend/CMakeLists.txt
This PR updates CMakeLists.txt for backend tests for NNPA to catch up with update in PR https://github.com/onnx/onnx-mlir/pull/1472
No need to run input verification test on NNPA, but we needed to copy `input_verification_backend.py` to use `test/backend/test.py` for NNPA.
> [NNPA] Update CMakeLists.txt for backend tests for NNPA

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/conv.mlir
As written in  issue #1517 , we get wrong results on NNPA at C(the number of channels) != 1,  kernel height = 1, and kernel width = 1.  This PR avoids this issue by running CPU instead of NNPA when using the parameter. 
> [NNPA] Run Conv2D on CPU when input parameters are C != 1, kH = 1, kW=1

- src/Transform/ONNX/ConstProp.cpp
- src/Transform/ONNX/ConstProp.td
- test/mlir/onnx/onnx_constprop.mlir
This patch implements constant propagation for ONNXSliceOp.
> Constant propagation for ONNXSliceOp

- src/Dialect/ONNX/ONNXOps.cpp
- test/mlir/onnx/onnx_shape_inference.mlir
Closes #1543
Added @test_gather_elements_negative_axis in onnx_shape_inference.mlir
> Don't crash on negative axis in ONNXGatherElementsOp::verify

- docs/LoweringCode.md
- src/Conversion/KrnlToAffine/KrnlMatmul.cpp
- src/Conversion/ONNXToKrnl/ObjectDetection/NonMaxSuppression.cpp
- src/Dialect/Krnl/DialectBuilder.cpp
- src/Dialect/Krnl/DialectBuilder.hpp
- src/Dialect/Mlir/DialectBuilder.cpp
- src/Dialect/Mlir/DialectBuilder.hpp
- src/Dialect/Mlir/DialectBuilder.hpp.inc
- src/Dialect/ONNX/DialectBuilder.hpp
added load/store with base index and  offset to simplify the reading of the optimized code.
basically, most of our builder's load and store were of the kind
``` C++
create.*.load(memref, indices)
```
I added a version that does this
``` C++
create.*.load(memref, indices, offsets)
```
where the rank of offsets can be smaller than the rank of the memref & indices. When that is the case, the offsets are added to the least significant dimensions of indices.
So if indices are (i, j, k, l) and offsets are (K, L), the results will be (i, j, k+K, l+L).
> Krnl cleanup

- docker/Dockerfile.onnx-mlir-dev
Dev image is getting too big (>20GB), remove test binaries (~6GB) to reduce its size
> Remove test binaries in dev image

- src/Conversion/ONNXToKrnl/Tensor/Transpose.cpp
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
Output MemRefType are used to check the conditions where `reinterpret_cast` can be used, but the MemRefType should be that of input. This is fixed by this PR.
When output MemRefType is used, `reinterpret_cast` is used in following example in onnx-to-krnl lowering, but this is not correct. This issue occurs when the order of dimension where the value is not 1 is changed by transpose.
```
%3 = "onnx.Transpose"(%arg1) {perm = [2, 3, 1, 0]} : (tensor<2x3x1x1xf32>) -> tensor<1x1x3x2xf32>
```
> Fix condition where reinterpret_cast is used in lowering of transpose op.

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/conv.mlir
Issue https://github.com/onnx/onnx-mlir/issues/1517 was resolved by PR https://github.com/onnx/onnx-mlir/pull/1576 
So reverting PR https://github.com/onnx/onnx-mlir/pull/1518 to remove workaround. 
Test results of Conv2D on NNPA (C!=1, kH=1, Kw=1) :   [test-result.txt](https://github.com/onnx/onnx-mlir/files/9264913/conv-kh1xkw1.txt)
> [NNPA] Enabled Conv2D C != 1, kH=1, kW=1 on NNPA

- src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.td
- src/Support/TypeUtilities.cpp
- src/Support/TypeUtilities.hpp
- test/mlir/accelerators/nnpa/conversion/rewrite-onnx-for-zhigh.mlir
- utils/mlir2FileCheck.py
In the bertsquad model, there are many broadcasting BinaryOp(s) whose one of its inputs is a constant, e.g. 
```mlir
%0 = "onnx.Constant"() {value = dense<1.0> : tensor<768xf32>} : () -> tensor<768xf32>
%1 = "onnx.Mul"(%arg0, %189) : (tensor<256x768xf32>, tensor<768xf32>) -> tensor<256x768xf32>
```
Since NNPA does not support broadcasting, these ops will not be executed on NNPA. To overcome this, we expand the constant to have the same shape as the other input, so that there is no broadcasting and the op can be run on NNPA. The above `onnx.Mul` will become:
```mlir
%0 = "onnx.Constant"() {value = dense<1.000000e+00> : tensor<768xf32>} : () -> tensor<768xf32>
%1 = "onnx.Shape"(%arg0) : (tensor<256x768xf32>) -> tensor<2xi64>
%2 = "onnx.Expand"(%0, %1) : (tensor<768xf32>, tensor<2xi64>) -> …
```
> [NNPA] Turn a broadcasting BinaryOp whose one of the inputs is a constant into a non-broadcasting BinaryOp

- .buildbot/LLVM-Watch-Docker-Build.xml
- .buildbot/jenkins-build-llvm-project.py
- .buildbot/jenkins-build-project.py
- .buildbot/jenkins-check-model-zoo.py
- .buildbot/jenkins-cleanup-build-states.py
- .buildbot/jenkins-publish-docker-images.py
- .buildbot/jenkins-stop-previous-build.py
- .buildbot/jenkins-watch-llvm-project.py
- .buildbot/llvm-watch.html
- Implement incremental retrieval of llvm-project commit history to avoid the 5000/hour github REST API call limit
- Use green (instead of orange) for the successful build color
- Add line number to log output in all build scripts
> Fix llvm monitor job to retrieve llvm-project commit history incrementally

- src/Builder/FrontendDialectTransformer.cpp
this PR solves the problem that the onnx parser cannot parse Optional op's type_proto attribute (it crashes in `ImportType` or `convertOnnxAttributeProtoToMlirNamedAttribute` in FrontendDialectTransformer, depending on whether the `--useOnnxModelTypes` flag is used)
this PR was tested by running:
```bash
Debug/bin/onnx-mlir -v --EmitONNXBasic --useOnnxModelTypes ../third_party/onnx/onnx/backend/test/data/node/test_if_opt/model.onnx -o /tmp/test_if_opt
```
and then:
```bash
Debug/bin/onnx-mlir-opt /tmp/test_if_opt.onnx.mlir
```
to verify that the resulting mlir assembly is well-formed
> parse Optional op's TYPE_PROTO attribute

- src/Pass/Passes.hpp
- src/Transform/ONNX/InstrumentONNXPass.cpp
- test/mlir/accelerators/nnpa/conversion/instrument/add-onnx-level.mlir
- test/mlir/accelerators/nnpa/conversion/instrument/add-zhigh-level.mlir
- test/mlir/conversion/instrument/add.mlir
This PR fixes https://github.com/onnx/onnx-mlir/issues/1600 about instrumentation
- `krnl.runtime_instrument` was not inserted before target op for instrumentation. This PR fixes it and it is inserted before and after the op correctly.
- Add lit tests to avoid these bugs in the future.
> Fix an issue about inserting instrument before op

- docs/SupportedONNXOps-NNPA.md
- src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHigh.td
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHighCommon.td
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.td
- src/Dialect/ONNX/DialectBuilder.cpp
- src/Dialect/ONNX/DialectBuilder.hpp
- test/accelerators/NNPA/backend/CMakeLists.txt
- test/mlir/accelerators/nnpa/conversion/rewrite-onnx-for-zhigh.mlir
This patch is to rewrite N-D MatMul into 3-D MatMul so that it can run on NNPA. For example, the following MatMul:
```mlir
func.func @test_matmul(%arg0: tensor<4x12x256x256xf32>, %arg1: tensor<4x12x256x64xf32>) -> (tensor<4x12x256x64xf32>) {
%0= "onnx.MatMul"(%arg0, %arg1) : (tensor<4x12x256x256xf32>, tensor<4x12x256x64xf32>) -> tensor<4x12x256x64xf32>
return %0 : tensor<4x12x256x64xf32>
}
```
will become:
```mlir
func.func @test_matmul(%arg0: tensor<4x12x256x256xf32>, %arg1: tensor<4x12x256x64xf32>) -> tensor<4x12x256x64xf32> {
%0 = "onnx.Constant"() {value = dense<[-1, 256, 256]> : tensor<3xi64>} : () -> tensor<3xi64>
%1 = "onnx.Reshape"(%arg0, %0) {allowzero = 0 : si64} : (tensor<4x12x256x256xf32>, tensor<3xi64>) -> tensor<48x256x256xf32>
%2 = "onnx.Constant"() {value = dense<[-1, 256, …
```
> [NNPA] Rewrite N-D MatMul into 3-D MatMul so that it can run on NNPA

- src/Builder/FrontendDialectTransformer.cpp
- src/Compiler/CompilerUtils.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp
- src/Conversion/ONNXToKrnl/RNN/GRU.cpp
- src/Conversion/ONNXToKrnl/RNN/LSTM.cpp
- src/Conversion/ONNXToKrnl/RNN/RNN.cpp
- src/Conversion/ONNXToKrnl/RNN/RNNBase.cpp
- src/Conversion/ONNXToKrnl/Tensor/Compress.cpp
- src/Conversion/ONNXToKrnl/Tensor/Constant.cpp
- src/Conversion/ONNXToKrnl/Tensor/ConstantOfShape.cpp
- src/Conversion/ONNXToMhlo/Tensor/Constant.cpp
- src/Dialect/Krnl/DialectBuilder.cpp
- src/Dialect/Krnl/KrnlHelper.cpp
- src/Dialect/Krnl/KrnlOps.cpp
- src/Dialect/ONNX/ONNXOpsHelper.cpp
- src/Dialect/ONNX/ShapeInference/Compress.cpp
- src/Dialect/ONNX/ShapeInference/ONNXShapeHelper.cpp
- src/Dialect/ONNX/ShapeInference/Squeeze.cpp
- src/Transform/BundleMemoryPools.cpp
- src/Transform/EnableMemoryPool.cpp
- src/Transform/ONNX/ConstProp.cpp
- src/Transform/ONNX/ElideConstants.cpp
- src/Transform/OptimizeMemoryPools.cpp
the deprecation warnings were caused by the change "[ADT] Deprecate Optional::{hasValue,getValue} (NFC)" that was pulled in from llvm/mlir in PR #1599
the deprecation warnings are noisy so I'm thinking it's worth getting rid of them
> address Optional::{hasValue,getValue} deprecation compiler warnings

- docs/SupportedONNXOps-NNPA.md
- src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.cpp
- src/Accelerators/NNPA/Conversion/ZHighToZLow/ZHighToZLow.cpp
- src/Conversion/KrnlToAffine/ConvertKrnlToAffine.cpp
- src/Conversion/KrnlToAffine/KrnlMemset.cpp
- src/Dialect/Krnl/DialectBuilder.cpp
- src/Dialect/Krnl/DialectBuilder.hpp
- src/Dialect/Krnl/Krnl.td
- test/accelerators/NNPA/backend/CMakeLists.txt
- test/mlir/accelerators/nnpa/conversion/rewrite-onnx-for-zhigh.mlir
- test/mlir/accelerators/nnpa/conversion/zhigh-to-zlow/gru.mlir
- test/mlir/accelerators/nnpa/conversion/zhigh-to-zlow/lstm.mlir
- test/mlir/krnl/krnl_memset.mlir
- test/mlir/onnx/onnx_lowering_nonmaxsuppression_op.mlir
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
In PR #1612, we disabled support for dynamic shape when rewriting N-D Matmul into 3-D Matmul due to an unknown issue.
After investigating it, I found that it was caused by `krnl.memset` when the input is **a MemRef with affine_map**. More info about the issue is in [the below comment](https://github.com/onnx/onnx-mlir/pull/1618#issuecomment-1223420437).
This patch fixes the issue by introducing an attribute, named `delayed`, in `krnl.memset` to indicate two modes of `krnl.memset`: 
- `delayed = false`: do memset over **the original iteration space** of the MemRef with affine_map.
- `delayed = true`: do memset over **the extended iteration space** (the space after the MemRef is normalized) of the MemRef with affine_map.
For example, if we want to set original elements to 1.0 and padding …
> Introduce attribute delayed in krnl.memset and enable N-D Matmul to 3-D MatMul for dynamic shape

- docs/BuildOnLinuxOSX.md
- docs/BuildOnWindows.md
- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Dialect/Mlir/DialectBuilder.cpp
- src/Dialect/Mlir/DialectBuilder.hpp
- test/mlir/conversion/onnx_to_mhlo/Math/GlobalPooling.mlir
- test/mlir/conversion/onnx_to_mhlo/Math/Reduction.mlir
- test/mlir/conversion/onnx_to_mhlo/Math/Softmax.mlir
- test/mlir/conversion/onnx_to_mhlo/NN/Pooling.mlir
- test/mlir/conversion/onnx_to_mhlo/Tensor/Reshape.mlir
- test/mlir/conversion/onnx_to_mhlo/models/mnist.onnx.mlir
- test/mlir/onnx/onnx_lowering.mlir
- utils/clone-mlir.sh
This updates LLVM to a green commit:
```
Week of 8/22/2022:
Green LLVM commit: e5d5146323ffaa13eb5185616c6ae5c36b69352d
Green MHLO commit: ace4030dd55fce2a74e46f71f1937feb61ed1e3f (branch greencommit/2022-08-22-e5d51463)
```
This update is to include a fix for memref normalization where non-normalizable operations with identity map layouts blocked  normalization of the entire function: https://github.com/llvm/llvm-project/commit/183c4a391ef344220664d1d103d43639468bf103
> Update llvm to e5d5146323ffaa13eb5185616c6ae5c36b69352d

- src/Conversion/KrnlToLLVM/KrnlEntryPoint.cpp
- src/Conversion/KrnlToLLVM/KrnlToLLVMHelper.cpp
- src/Conversion/KrnlToLLVM/KrnlToLLVMHelper.hpp
- src/Dialect/ONNX/ONNX.td
- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXOpsHelper.cpp
- src/Dialect/ONNX/ONNXOpsHelper.hpp
- src/Transform/ONNX/Decompose.td
- test/mlir/onnx/onnx_decompose.mlir
- test/mlir/onnx/onnx_shape_inference.mlir
- test/mlir/onnx/onnx_structure.mlir
As I implemented OptType in PR #1589 I noticed some issues with SeqType and sequence ops that are solved here:
1. SeqType required its element type to be a ShapedType, which conflicts with its use with a map element type in ZipMap
2. the SequenceConstruct op decomposition didn't support most data types
3. we didn't infer shapes for the SequenceConstruct op
Note that Conversion/KrnlToLLVM/KrnlToLLVMHelper now depends on Dialect/ONNX/ONNXOpsHelper for mlirTypeToOnnxType. Please let me know if there's a better way to reuse this logic.
> fixes for SeqType and sequence ops

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp
- src/Accelerators/NNPA/Conversion/ZHighToZLow/ZHighToZLow.cpp
- src/Accelerators/NNPA/Transform/FoldStdAlloc.cpp
- src/Accelerators/NNPA/Transform/ZHigh/ZHighConstPropagation.cpp
fixes the warnings:
```
warning: 'ArrayRef' may not intend to support class template argument deduction [-Wctad-maybe-unsupported]
warning: 'getValue' is deprecated: Use value instead. [-Wdeprecated-declarations]
```
I overlooked these in PR #1622 because I didn't build with `-DONNX_MLIR_ACCELERATORS=NNPA`
> fix compiler warnings about Optional::getValue and ArrayRef

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHigh.td
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.td
- src/Accelerators/NNPA/Conversion/ZHighToZLow/CMakeLists.txt
- src/Accelerators/NNPA/Conversion/ZHighToZLow/ZHighToZLow.cpp
- src/Accelerators/NNPA/Dialect/ZHigh/ZHigh.td
- src/Accelerators/NNPA/Dialect/ZHigh/ZHighCombine.cpp
- src/Accelerators/NNPA/Dialect/ZHigh/ZHighCombine.td
- src/Accelerators/NNPA/Dialect/ZHigh/ZHighOps.cpp
- src/Accelerators/NNPA/Dialect/ZHigh/ZHighShapeHelper.cpp
- src/Accelerators/NNPA/Dialect/ZHigh/ZHighShapeHelper.hpp
- src/Accelerators/NNPA/Support/LayoutHelper.cpp
- src/Accelerators/NNPA/Support/LayoutHelper.hpp
- src/Accelerators/NNPA/Transform/ZHigh/ZHighLayoutPropagation.td
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/conv.mlir
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/pool.mlir
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/reducemean.mlir
- test/mlir/accelerators/nnpa/conversion/rewrite-onnx-for-zhigh.mlir
- test/mlir/accelerators/nnpa/conversion/zhigh-to-zlow/stick-unstick.mlir
- test/mlir/accelerators/nnpa/conversion/zhigh-to-zlow/test-datalayout.mlir
- test/mlir/accelerators/nnpa/transform/zhigh-combine.mlir
- test/mlir/accelerators/nnpa/transform/zhigh-layout-propagation.mlir
- test/mlir/accelerators/nnpa/transform/zhigh-shape-inference/stick-unstick.mlir
ONNX uses NCHW layout by default and ZDNN stickify and unstickify can work directly with NCHW layout. It means we don't need to explicitly transpose from/to NCHW to/from NHWC before stickify/unstickify.
Before this patch, an ONNXConv (X: tensor<1x2x3x4xf32>) will be lowered to :
```mlir
X_NHWC = transpose(X)  {to = NHWC} : tensor<1x2x3x4xf32> -> tensor<1x4x2x3xf32>
X_NHWC_S = stick (X_NHWC) {layout = NHWC} : tensor<1x4x2x3xf32> -> tensor<1x4x2x3xf32, "NHWC">
Y_NHWC_S = zhigh.conv(X_NHWC_S) : tensor<1x4x2x3xf32, "NHWC"> -> tensor<1x4x2x3xf32, "NHWC">
Y_NHWC = unstick(Y_NHWC_S) : tensor<1x4x2x3xf32, "NHWC"> -> tensor<1x4x2x3xf32>
Y = transpose (Y_NHWC) {to = NCHW} : tensor<1x4x2x3xf32> -> tensor<1x2x3x4xf32>
```
With this patch an ONNXConv will be lowered to:
```mlir
X_NHWC_S = stick (X) …
```
> [NNPA] Directly stickify/unstickify from/to NCHW without data transpose

- test/mlir/accelerators/nnpa/transform/zlow-normalize-by-using-dummyop.mlir
the output starts with the failed assert message so
there is no label we can use with `FAILED-LABEL:`
closes #1645
> fix lit test zlow-normalize-by-using-dummyop.mlir

- src/Conversion/ONNXToKrnl/Math/MatMul.cpp
- src/Dialect/Mlir/IndexExpr.hpp
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
- test/modellib/MatMulModel.cpp
- test/modellib/ModelLib.hpp
- test/numerical/TestMatMulBroadcast.cpp
- test/perf/PerfGemm.cpp
Extension suggested by @tungld to support more broadcast patterns for matmul, namely when both A &B have the same identical broadcast dimensions (cannot handle dynamic dimension as we cannot rule out that one would be `1` and the other `100`, for example, thus needing an actual broadcast pattern.
This is an example of what this PR adds, where both broadcast dim of arg0 and arg1 (for A and B) are `2x3`.
```mlir
func.func private @test_matmul3(%arg0 : tensor<2x3x10x5xf32>, %arg1 : tensor<2x3x5x10xf32>) -> tensor<*xf32> {
%0 ="onnx.MatMul"(%arg0, %arg1) : (tensor<2x3x10x5xf32>, tensor<2x3x5x10xf32>) -> tensor<*xf32>
"func.return"(%0) : (tensor<*xf32>) -> ()
// mlir2FileCheck.py -a'["A", "B"]' -n'{"0": "RES"}'
// CHECK-LABEL:  func.func private @test_matmul3
// CHECK-SAME:   ([[A_:%.+]]: …
```
> Matmul broadcast when the broadcast dims of A & B are identical

- src/Compiler/CompilerPasses.cpp
- src/Conversion/ONNXToKrnl/CMakeLists.txt
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/InitOMPasses.hpp
- src/Pass/Passes.hpp
Prior to this patch, any consumer of the ONNXToKrnl pass (transitively)
depended on the CompilerOptions library.  This dependency caused
conflicts in identically-named command line options between the
CompilerOptions library and the consumers of the ONNXToKrnl pass.
This patch introduces a local option to the ONNXToKrnl pass so that its
dependency on CompilerOptions is removed, thus eliminating the symbol
conflicts.  When its time to pass a command line option to enable
parallelization in the ONNXTOKrnl pass, the call to
`createLowerToKrnlPass()` in CompilerPasses.cpp, which correctly depends
on the CompilerOptions library, will be able to pass the command line
value to the ONNXToKrnl pass.
> build: decouple CompilerOptions from ONNXToKrnl pass

- test/backend/setup_model_download.cmake
Prior to this patch, in a repository setup where onnx-mlir is not
present in the top-level directory, the build failed because the
`setup_model_download()` function assumed that the `third_party/onnx`
directory is located at the root of the repository.
This patch fixes the problem by replacing the reference to
`CMAKE_SOURCE_DIR` with `ONNX_MLIR_SRC_ROOT`.
Signed-off-by: Ashay Rane <ashay@users.noreply.github.com>
> build: fix path to test data directory

- test/perf/PerfConv.cpp
Added Convolution with kernels of 1x1 to the PerfConv performance benchmark for Convolutions.
> Added Conv1x1 to PerfConv benchmark

- src/Tools/onnx-mlir-opt/onnx-mlir-opt.cpp
I noticed that `onnx-mlir-opt -h` wasn't displaying `--split-input-file` and some other options
this PR adds the following output to `onnx-mlir-opt -h`:
```
ONNX-MLIR-OPT Options:
These are opt frontend options.
--allow-unregistered-dialect                         - Allow operation with no registered dialects
-o <filename>                                        - Output filename
--split-input-file                                   - Split the input file into pieces and process each chunk independently
--verify-diagnostics                                 - Check that emitted diagnostics match expected-* lines on the corresponding line
--verify-each                                        - Run the verifier after each transformation pass
```
Signed-off-by: Soren Lassen …
> show onnx-mlir-opt CLI options

- docs/SupportedONNXOps-NNPA.md
- src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.td
- src/Dialect/ONNX/DialectBuilder.cpp
- src/Dialect/ONNX/DialectBuilder.hpp
- test/accelerators/NNPA/backend/CMakeLists.txt
- test/mlir/accelerators/nnpa/conversion/rewrite-onnx-for-zhigh.mlir
NNPA does not support Pow op and Softmax with rank > 2. In some cases, we can rewrite these ops into the form that NNPA supports. 
This patch rewrites:
- ONNXPowOp into multiple Mul ops if exponent is an integer and <= 64, and 
- Softmax with rank > 2 into Softmax with rank = 2 if axis is the last dimension.
For example, 
```mlir
func.func @test_pow(%arg0: tensor<3x4x5xf32>) -> tensor<3x4x5xf32> {
%cst = "onnx.Constant"() {value = dense<3.0> : tensor<f32>} : () -> tensor<f32>
%0 = "onnx.Pow"(%arg0, %cst) : (tensor<3x4x5xf32>, tensor<f32>) -> tensor<3x4x5xf32>
return %0 : tensor<3x4x5xf32>
}
```
will become
```mlir
func.func @test_pow(%arg0: tensor<3x4x5xf32>) -> tensor<3x4x5xf32> {
%0 = "onnx.Mul"(%arg0, %arg0) : (tensor<3x4x5xf32>, tensor<3x4x5xf32>) -> tensor<3x4x5xf32>
%1 = …
```
> [NNPA] Rewrite ONNXPowOp and ONNXSoftmaxOp for NNPA

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.cpp
- test/mlir/accelerators/nnpa/conversion/rewrite-onnx-for-zhigh.mlir
Minimize the number of onnx.Mul for onnx.Pow(input, exponent) with "exponentiation by squaring" method.
This PR reduces the calculation order from O(exponent) to O(log exponent).
Signed-off-by: Yasushi Negishi <negishi@jp.ibm.com>
> [NNPA] Optimize onnx.pow(input,exponent) with "exponentiation by squaring" method

- src/Conversion/ONNXToKrnl/Tensor/PrintSignature.cpp
- src/Dialect/ONNX/AdditionalONNXOps.td
- src/Transform/ONNX/InstrumentONNXSignaturePass.cpp
- utils/RunONNXLib.cpp
- utils/build-run-onnx-lib.sh
Yolo 4 has ops that have operands with none types. When trying to use `--instrument-onnx-signature` to trace at runtime the operand signatures, the verifier complained as the PrintSignature ONNX op did not support NONE type as one of its input types.
This PR remedy this issue.
> Print signature in presence of operands with  none types

- CMakeLists.txt
- src/Conversion/CMakeLists.txt
- src/Conversion/ONNXToMhlo/ConvertONNXToMhlo.cpp
- src/InitOMPasses.hpp
- src/Pass/Passes.hpp
- src/Tools/onnx-mlir-opt/onnx-mlir-opt.cpp
- src/Transform/ONNX/Decompose.cpp
- test/mlir/CMakeLists.txt
- test/mlir/conversion/onnx_to_mhlo/lit.local.cfg
- test/mlir/lit.site.cfg.py.in
After this change, MHLO can be excluded by setting `ONNX_MLIR_ENABLE_MHLO` to `OFF`. The default remains set to `ON`, so MHLO will continue to be included.
> Make MHLO Optional

- CMakeLists.txt
- docs/doc_example/CMakeLists.txt
- docs/doc_example/main.cpp
- docs/mnist_example/README.md
- include/OnnxMlirCompiler.h
- src/CMakeLists.txt
- src/Compiler/CompilerOptions.cpp
- src/Compiler/CompilerOptions.hpp
- src/Compiler/CompilerUtils.cpp
- src/Compiler/CompilerUtils.hpp
- src/Compiler/OnnxMlirCompiler.cpp
- src/Runtime/OMTensor.inc
- src/Tools/onnx-mlir-opt/onnx-mlir-opt.cpp
- src/onnx-mlir.cpp
- test/compilerlib/CompilerLibTest.cpp
- test/perf/PerfHelper.hpp
New interface allows all of the onnx-mlir options to be used
```
ONNX_MLIR_EXPORT int64_t omCompileFromFileViaCommand(const char *inputFilename,
const char *flags, const char **outputFilename, const char **errorMessage);
```
and, for example, if you need the output to be named after something special, we can simply add `-o output name` in the flag string. Or if you want to output a JNI, just add `-EmitJNI`.
Also, it is now possible to use the `"-customEnvFlags=MY_ONNX_MLIR_FLAGS"` so that the default is taken from a custom environment variable, not necessarily the default `ONNX_MLIR_FLAGS`. 
Full interface:
```C
/*!
*  C interface to compile an onnx model from a file via onnx-mlir command.
*  This interface is thread safe, and does not take any flags from the
*  current environment. All …
```
> Simplified interface for compile from programs

- docs/BuildOnWindows.md
- test/perf/CMakeLists.txt
- test/perf/PerfConv.cpp
- test/perf/PerfGemm.cpp
- test/perf/PerfHelper.cpp
- test/perf/PerfHelper.hpp
- test/perf/PerfRNN.cpp
- utils/build-onnx-mlir.cmd
In the test/perf, there were functions that were inlined by #def macros.This may contribute to compile issue on Windows.
This PR transformed the inline macros into functions integrated in a new `PerfLib`, so hopefully this will help Windows... and it is a nicer code anyway.
> Perf noinline

- src/Transform/ONNX/DecomposeEinsum.cpp
- test/mlir/onnx/onnx_decompose_einsum.mlir
ArrayRef was used after the underlying array changed, fixed it by creating a copy of the underlying array and make the ArrayRef point to the copy
> fix einsum decomposition bug

- src/Conversion/ONNXToKrnl/PerfectHash.cpp
- src/Transform/ONNX/ConvOpt.cpp
- src/Transform/ONNX/Decompose.cpp
fixes `'sprintf' is deprecated` warning on Mac and `base class should be explicitly initialized in the copy constructor` warnings on Linux
the solution to the copy constructor warning was copied from `InstrumentONNXPass.cpp`
warning from Apple clang version 14.0.0 (clang-1400.0.29.201):
```
.../src/Conversion/ONNXToKrnl/PerfectHash.cpp:47:5: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
sprintf(str, "%lld", (long long)val);
/Library/Developer/CommandLineTools/SDKs/MacOSX13.0.sdk/usr/include/stdio.h:188:1: note: 'sprintf' has been explicitly marked deprecated here
__deprecated_msg("This function …
```
> fix 2 compiler warnings

- docs/SupportedONNXOps-cpu.md
- src/Conversion/ONNXToKrnl/CMakeLists.txt
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Conversion/ONNXToKrnl/Tensor/ArgMinMax.cpp
- test/backend/inference_backend.py
- test/mlir/onnx/onnx_shape_inference.mlir
This change adds support for ```ArgMin```  based on ```ArdMax``` with the minor changes, as discussed in https://github.com/onnx/onnx-mlir/issues/922#issuecomment-1255933862
> Add support for ArgMin

- src/Builder/FrontendDialectHelper.cpp
closes #1729
Co-authored-by: Quinn Dawkins <quinn.dawkins@gmail.com>
> redo ArrayRefOrSmallVector with enable_if

- src/Transform/ONNX/SimplifyShapeRelatedOps.cpp
- test/mlir/onnx/onnx_simplify_shape_related_ops.mlir
Some ops to process shape return a scalar tensor `tensor<i64>` instead of `tensor<1xi64>`, while our SimplifyShapeRelatesOps pass always use `tensor<1xi64>`. So we need to convert `tensor<1xi64>` to `tensor<i64>` by a squeeze op.
> Handle scalar tensor tensor<type> in SimplifyShapeRelatesOps pass

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHighCommon.hpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Conversion/ONNXToKrnl/RNN/RNNBase.hpp
- src/Conversion/ONNXToMhlo/ONNXToMhloCommon.cpp
- src/Conversion/ONNXToMhlo/ONNXToMhloCommon.hpp
- src/Conversion/ONNXToTOSA/ONNXToTOSACommon.hpp
- src/Transform/ONNX/ConstPropHelper.cpp
- src/Transform/ONNX/ConstPropHelper.hpp
removed `using namespace mlir` from ConstPropHelper.hpp and added requisite `mlir::` and `llvm::` in header files to get everything to compile again
also put ConstPropHelper definitions in namespace onnx_mlir
> namespace cleanup

- src/Runtime/OMIndexLookup.inc
- src/Runtime/OMInstrument.inc
saw this warning with clang version 14.0.0 on mac:
```
.../src/Runtime/OMIndexLookup.inc:37:3: warning: 'sprintf' is deprecated: This function is provided for compatibility reasons only.  Due to security concerns inherent in the design of sprintf(3), it is highly recommended that you use snprintf(3) instead. [-Wdeprecated-declarations]
sprintf(str, "%lld", (long long)val);
```
> fix two sprintf compiler warnings

- src/Dialect/ONNX/ONNXOps.cpp
> Another place in ScanOp::inferShapes needs refineShape=false

- docs/SupportedONNXOps-NNPA.md
- test/accelerators/NNPA/backend/CMakeLists.txt
Updated supported-ops-NNPA for LeakyRelu to reflect latest status.
This was reporeted in issue https://github.com/onnx/onnx-mlir/issues/1714
> Update document about supported ops on NNPA for LeakyRelu

- src/Dialect/Mlir/IndexExpr.cpp
- src/Dialect/Mlir/IndexExpr.hpp
- src/Dialect/Mlir/IndexExprDetail.cpp
- src/Dialect/Mlir/IndexExprDetail.hpp
Problem: given a tensor value, to do shape computation we call `MemRefBoundsIndexCapture(val)` e.g.
```c
Value data = operandAdaptor.data();
MemRefBoundsIndexCapture dataBounds(data);
```
Assume that axis 2 is an unknown dimension and now we get the QuestionMarkIndexExpr of it.
```c
QuestionMarkIndexExpr dim = dataBounds.getDim(2);
int64_t questionMarkValue = dim.getQuestionmark();
```
The problem is: everytime we call `dataBounds.getDim(2)`, a new QuestionMarkIndexExpr is created and its value is changed.
To keep the question mark value unchanged for a specific axis of a tensor, this patch uses a hash_code, that is a hash combination of the tensor value and axis, for the question mark value. 
> Create unique QuestionMarkIndexExpr by using a hash code of tensor and axis

- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Dialect/ONNX/ShapeInference/ONNXShapeHelper.cpp
- src/Dialect/ONNX/ShapeInference/ONNXShapeHelper.hpp
Though it is quite simple to infer shape for unary element-wise operations, this patch uses IndexExpr for the shape inference to help analyze unknown dimensions in a systematic way in the future.
> Use IndexExpr to compute shape for unary element-wise ops

- utils/RunONNXModel.py
Small update in RunONNXModel.py to avoid an error about command-line option.
I got an error when using "--compile-args -O3&nbsp;&nbsp;--mtriple=s390x-ibm-loz --mcpu=z14".  "--compile-args "-O3&nbsp;--mtriple=s390x-ibm-loz --mcpu=z14" works instead. Looks the same, but the first one has two space between `-O3` and `--mtriple`. 
--compile-args "-O3&nbsp;&nbsp;--mtriple=s390x-ibm-loz --mcpu=z14"  ==> Error
--compile-args "-O3&nbsp;--mtriple=s390x-ibm-loz --mcpu=z14"  ==> No error
To avoid this error, we can use default separator in split().
> Change split(' ') to split() in RunONNXModel.py to avoid an error about command-line option

- src/Compiler/CompilerUtils.cpp
`targetMachine` is created and not destroyed which causes this error reported by valgrind:
```
==3261261== 48 bytes in 1 blocks are indirectly lost in loss record 31 of 90
==3261261==    at 0x4831334: operator new(unsigned long) (in /usr/lib/valgrind/vgpreload_memcheck-s390x-linux.so)
==3261261==    by 0x67A5F4D: createSystemZMCInstrInfo() (in /home/tungld/dl/llvm-project.om/build/lib/libLLVMSystemZDesc.so.16git)
==3261261==    by 0x8BD72CF: llvm::LLVMTargetMachine::initAsmInfo() (in /home/tungld/dl/llvm-project.om/build/lib/libLLVMCodeGen.so.16git)
==3261261==    by 0x66E3B83: llvm::SystemZTargetMachine::SystemZTargetMachine(llvm::Target const&, llvm::Triple const&, llvm::StringRef, llvm::StringRef, llvm::TargetOptions const&, llvm::Optional<llvm::Reloc::Model>, …
```
> Fix a memory leak about targetMachine that is not destroyed

- src/Runtime/jni/src/com/ibm/onnxmlir/OMModel.java
AppScan on Cloud doesn't like other/world permissions set on files.
When running models on Java we extract the .so file from the .jar so we can load it. The file is exacted to a temp directory, loaded and then deleted. For z/OS cases, we have to set the permission to include the execute. However since the file is loaded and immediately deleted, we should be able to restrict the permissions to only the current user to make ASoC happy.
> Use 700 when loading .so for Java

- src/Compiler/CompilerPasses.cpp
Signed-off-by: chentong319 <chentong@us.ibm.com>
KrnlRegionOp is used to mark the boundary of affine scope. Previously, the KrnlRegion is removed after buffer deallocation. For the case of LoopOp, the KrnlRegion is inside the Then region of scf.if. The bufferization deallocation pass did not generate the deallocation for the last used buffer while deallocation is generated for other buffers.  The exact reason need further investigation.
This PR just moved the KrnlRegion lowering pass right after the affine is lowered and before the buffer deallocation pass.  This should be the right order in the first place.
> Remove KrnlRegion earlier

- src/Transform/ONNX/ONNXDimAnalysis.cpp
Resolves #1843 
DimAnalysis borrows ShapeHelper of unary elementwise ops for analysing unknown dimensions of ReduceMean. That's because there is no ShapeHelper using IndexExpr for ReduceMean currenlty. 
But this emits a warning related to mismatch in static dimensions.
For the purpose of unknown dimension analysis, we simply pass the input unknown dimension to the output unknown dimension. This patch does it manually. 
However, a long-term solution should be writing IndexExpr-based ShapeHelper for ReduceMean.
> Fix shape inference warning related to ReduceMean

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.cpp
- src/Transform/ONNX/ONNXDimAnalysis.cpp
- test/mlir/accelerators/nnpa/conversion/rewrite-onnx-for-zhigh.mlir
This patch applies DimAnalysis to the pass `rewrite-onnx-for-zhigh`.
> Use DimAnalysis in rewrite-onnx-for-zhigh pass

- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Dialect/Krnl/DialectBuilder.cpp
- src/Dialect/Krnl/DialectBuilder.hpp
- src/Dialect/Mlir/DialectBuilder.hpp
- src/Dialect/Mlir/DialectBuilder.hpp.inc
- src/Dialect/Mlir/IndexExprBuilder.hpp
- src/Dialect/ONNX/DialectBuilder.hpp
- test/modellib/ModelLib.hpp
Fixes for mac build, originally introduced by #1859
* Warning for non virtual destructors of classes with virtual functions
* `template` keyword where the compiler may be confused as templates are used for the class and a function call within the class. See https://www.aerialmantis.co.uk/blog/2017/03/17/template-keywords/ for explanation on the second point. Added a warning comment in the file that needed this fix so that we may better remember the cause of this extra `template` keyword.
> fixes for mac

- src/Dialect/ONNX/ONNXOps/NewShapeHelper.hpp
warning was:
```
'onnx_mlir::NewONNXOpShapeHelper<mlir::Operation>' has virtual functions but non-virtual destructor [-Wnon-virtual-dtor]
```
> made ~NewONNXOpShapeHelper() virtual to fix warning

- docs/DebuggingNumericalError.md
- utils/RunONNXModel.py
- utils/RunONNXModelZoo.py
This patch updates the python script `RunONNXModel.py` to allow compiling and running a `.mlir` file. This is very useful for debugging and profiling an MLIR program instead of an ONNX model.
For example, we have a `matmul.mIir` program as follows
```llvm
module attributes {llvm.data_layout = "E-m:e-i1:8:16-i8:8:16-i64:64-f128:64-v128:64-a:8:16-n32:64", llvm.target_triple = "s390x-ibm-linux"} {
func.func @main_graph(%arg0: tensor<?x4xf32>, %arg1: tensor<4x3xf32>) -> tensor<?x3xf32> attributes {input_names = ["a", "b"], output_names = ["c"]} {
%0 = "onnx.MatMul"(%arg0, %arg1) : (tensor<?x4xf32>, tensor<4x3xf32>) -> tensor<?x3xf32>
return %0 : tensor<?x3xf32>
}
"onnx.EntryPoint"() {func = @main_graph} : () -> ()
}
```
We can use RunONNXModel.py to compile and run it. Input data are …
> Support .mlir file as input to RunONNXModel.py

- src/Transform/ONNX/ONNXDimAnalysis.cpp
SliceOp and SplitOp are found in the GPT2 model. So add them to DimAnalysis.
> Support SliceOp and SplitOp in DimAnalysis

- src/Tools/onnx-mlir-opt/onnx-mlir-opt.cpp
- test/mlir/driver/outputfile.mlir
If `onnx-mlir-opt` was used with `-o` to create an outputfile, the file was always deleted after the run. This fixes it and also adds a test to make sure a file is created.
The implementation and test are adapted from [upstream MLIR](https://github.com/llvm/llvm-project/blob/05ff7606c9d47135ecf5b69e25b1327634f6fa27/mlir/lib/Tools/mlir-opt/MlirOptMain.cpp#L306-L315).
Signed-off-by: Maximilian Bartel <maximilian.bartel@amd.com>
> Fix -o in onnx-mlir-opt

- src/Dialect/ONNX/ONNXOps.td.inc
- src/Dialect/ONNX/Rewrite.cpp
- src/Dialect/ONNX/Rewrite.td
- test/mlir/onnx/onnx_canonicalization.mlir
- utils/gen_onnx_mlir.py
When `axis` in Softmax version 11 is the last dimension, Softmax version 11 is the same as Softmax version 13. This patch adds a rule for such a case.
This patch also re-organizes the list of canonicalization operations in the alphabetical orders without functional changes. 
> Rewrite softmax v11 to v13 when axis is the last dimension

- CMakeLists.txt
MSVC recently started issuing warnings when `std::complex` template is instantiated with types other than `float` and `double`, which caused failures in our builds. More details at https://github.com/microsoft/STL/pull/2759.
Unfortunately, the code that triggered the warning is part of upstream `mlir`, and accommodating this change isn't trivial. I propose that we suppress the warning for the time being.
> Suppress non-floating complex warning on newer MSVC versions

- src/Dialect/ONNX/Rewrite.td
- test/mlir/onnx/onnx_canonicalization.mlir
Currently when `beta=0`. This will incorrectly fuse the add op.
`beta` should be set to 1 in the pattern that it is replaced with.
Co-authored-by: Zachary Cetinic <zcetinic@groq.com>
Signed-off-by: Philip Lassen <plassen@groq.com>
> Fix issue in Gemm Add fusion

- src/Builder/FrontendDialectHelper.cpp
- src/Support/CMakeLists.txt
- src/Support/FloatingPoint16.cpp
- src/Support/FloatingPoint16.hpp
- test/mlir/onnx/parse/fp16_nonraw_data.json
- test/mlir/onnx/parse/fp16_raw_data.json
- utils/testing/floatingpoint16_data.py
introduces float_16 and bfloat_16 data types to represent both FLOAT16 and BFLOAT16 as c++ data types, which makes it possible to treat them like the other scalar types in many ways
this will also make it possible to do constant propagation, see PR #1874
this PR has been factored out from PR #1874
> ingest BFLOAT16

- src/Dialect/ONNX/ONNXOps/Tensor/Upsample.cpp
I updated the comment from `sanity` to `safety`. Also I did a search in VSCode to see if there are any lingering references to `master` in the `onnx-mlir` repo. Seems like there are only 3 places where `master` is present. Two instances are `PyTorch` links which will break if we use the word `main` and another section that uses the following link: `https://raw.githubusercontent.com/caldwell/renderjson/master/` . This link is actually broken, I get back a 400- Invalid response so I wonder if we can just remove this from the `onnx-mlir/.buildbot/jenkins-check-model-zoo.py`.
> Scrub upsample comment

- .github/workflows/macos-amd64-build.yml
> Preinstall numpy 1.23.5 since 1.24 appears to break onnx

- src/Runtime/OMSort.inc
On newer msvc versions (starting with Visual Studio 17.1), warning 4113 is issued in place of 4028. To preserve the same behaviour, also disable 4113 before using `qsort_s`.
Please see https://learn.microsoft.com/en-us/cpp/overview/cpp-conformance-improvements?view=msvc-170#c4028-is-now-c4133-for-function-to-pointer-operations for more details.
> Suppress parameter list mismatch warning on newer msvc versions

- src/Compiler/CMakeLists.txt
- src/Compiler/CompilerOptions.cpp
- src/Compiler/CompilerOptions.hpp
- src/Compiler/CompilerUtils.cpp
- src/Compiler/HeapReporter.cpp
- src/Compiler/HeapReporter.hpp
- utils/onnx-mlir-report-heap.sh
Added HeapReporter PassInstrumentation which dumps a heap log before/after the passes specified in the command line arguments ---report-heap-before and --report-heap-after.
Added script utils/onnx-mlir-report-heap.sh to run onnx-mlir with the necessary setup and execution environment, which means running it in the debugger on MacOS.
Only implemented for MacOS for now. Hopefully, someone will implement it on other OSs in the future.
Was used to measure the memory effects in PR #1874.
> heap reporting

- src/Dialect/ONNX/ONNXOps/Tensor/Resize.cpp
- test/mlir/onnx/onnx_shape_inference.mlir
This PR reverts the resize implementation of `shapeInference`. The issue is the new implementation casts `scales[i]` to an integer. This is not the correct behavior. 
It is hard to implement Resize with `indexExprs` because of the lack of support for the float type. Since Resize shape inference has a bug for `scales` I've elected to go to the old implementation that way we have it working correctly on `main`. 
I have filed an associated issue https://github.com/onnx/onnx-mlir/issues/1958.
@AlexandreEichenberger this only meant as a temporary roll back until we figure out a proper way to support floating point numbers in the `IndexExpr` framework.
> Fix Resize implementation

- src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.cpp
- src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.hpp
- src/Dialect/ONNX/ElementsAttr/ElementsAttrHelper.cpp
- src/Dialect/ONNX/ElementsAttr/ElementsAttrHelper.hpp.inc
- src/Transform/ONNX/ConstProp.cpp
- src/Transform/ONNX/ConstProp.td
- test/mlir/onnx/onnx_constprop.mlir
includes a bug fix in getMemoryBuffer() in ElementsAttrBuilder.cpp, which was exposed by the new const prop for Where
similarly, also added some checks in ElementsAttrHelper.hpp.inc in ElementsAttrHelper.cpp which would have caught some mistakes, and I threw in a refactor to remove code duplication between the get/readElementsWideNums() implementations, plus an optimization when the ElementsAttr is splat
> constant propagation for ONNXWhereOp

- src/Interface/CMakeLists.txt
`OMShapeHelperOpInterface.hpp` uses `#include "mlir/Support/LLVM.h"`, so the correct link library should be `MLIRSupport` instead of `LLVMSupport`.
Without this change, I got the following error when building onnx-mlir on a Z machine:
```
CMakeFiles/OMShapeHelperOpInterface.dir/ShapeHelperOpInterface.cpp.o: In function `mlir::detail::TypeIDResolver<mlir::OpTrait::ConstantLike<mlir::TypeID::get<mlir::OpTrait::ConstantLike>()::Empty>, void>::resolveTypeID()':
/home/tungld/dl/llvm-project/mlir/include/mlir/Support/TypeID.h:195: undefined reference to `mlir::detail::FallbackTypeIDResolver::registerImplicitTypeID(llvm::StringRef)'
collect2: error: ld returned 1 exit status
src/Interface/CMakeFiles/OMShapeHelperOpInterface.dir/build.make:97: recipe for target …
```
> Fix a wrong link in OMShapeHelperOpInterface

- README.md
- docs/ONNXAI.md
Previous link did not let folks join in without being invited by someone. The new link, borrowed from onnx site, worked for me.
> update the how to join for slack

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHigh.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHigh.td
- src/Conversion/ONNXToKrnl/Math/Clip.cpp
- src/Conversion/ONNXToKrnl/RNN/GRU.cpp
- src/Conversion/ONNXToKrnl/RNN/LSTM.cpp
- src/Conversion/ONNXToKrnl/RNN/RNN.cpp
- src/Conversion/ONNXToKrnl/RNN/RNNBase.cpp
- src/Conversion/ONNXToKrnl/RNN/RNNBase.hpp
- src/Conversion/ONNXToKrnl/Tensor/Transpose.cpp
- src/Dialect/ONNX/ONNXOps/Math/Gemm.cpp
- src/Dialect/ONNX/ONNXOps/NN/Conv.cpp
- src/Dialect/ONNX/ONNXOps/NN/Dropout.cpp
- src/Dialect/ONNX/ONNXOps/OpHelper.cpp
- src/Dialect/ONNX/ONNXOps/RNN/RNN.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Optional.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Pad.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Slice.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Split.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Squeeze.cpp
Signed-off-by: chentong319 <chentong@us.ibm.com>
Two changes:
1. Detect optional input. The NoneType is originally used to represent the optional input when it is not presented. Later, some onnx model used 0 length tensor for that purpose. We have function isFromNone for both case.  This change replace the NoneType check for some old code with isFromNone. Also isFromNone is changed to check the type, not how the value (definition point) is defined because a Value may not have a definition point in constructing process.
2. Delete unnecessary use of TypeConverter. The TypeConverter should be called automatically on the input by Conversion process, according to the document. Old code did not use type converter and the explicit type conversion was replaced with type converter when type …
> clean up some old code

- docs/DocumentList.md
- docs/UpdatingLLVMCommit.md
This adds a new document with instructions on how to update the LLVM commit or mlir-hlo submodule.
> Add llvm/mlir-hlo update instructions

- src/Conversion/ONNXToTOSA/CMakeLists.txt
- src/Conversion/ONNXToTOSA/ConvertONNXToTOSA.cpp
- src/Conversion/ONNXToTOSA/ONNXToTOSACommon.hpp
- src/Conversion/ONNXToTOSA/Tensor/Constant.cpp
- test/mlir/conversion/onnx_to_tosa/Tensor/Constant.mlir
This implements the conversion of the `ONNXConstantOp` to TOSA. 
Signed-off-by: Maximilian Bartel <maximilian.bartel@amd.com>
> Add Conversion for ConstOp ONNX to TOSA

- src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.cpp
- src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.hpp
- src/Dialect/ONNX/ElementsAttr/Strides.cpp
- src/Dialect/ONNX/ElementsAttr/Strides.hpp
- src/Dialect/ONNX/ElementsAttr/Strides.hpp.inc
- src/Dialect/ONNX/ElementsAttr/WideNum.hpp
- src/Dialect/ONNX/ElementsAttr/WideNum.hpp.inc
- src/Transform/ONNX/ConstProp.cpp
- src/Transform/ONNX/ConstProp.td
- test/mlir/onnx/onnx_constprop.mlir
constant propagates ReduceSum/Prod/Min/Max/Mean when data and axes are constant
implemented with a new ElementsAttrBuilder::reduce() method, which uses traverseStrides() in an unusual nested way: the outermost loop runs through all the elements to reduce into each output element and the inner loop reduces the next element into the output element (and all of this is done in a way that supports traversing the input with arbitrary strides)
the above logic needs to read the next input element to reduce with an offset and therefore traverseStrides() is refactored to pass arguments as const pointers to the lambda argument
ReduceMean is implemented with ReduceSum followed by dividing the result with the number of elements summed into each output element:
```
if constexpr …
```
> constant propagate ReduceSum/Prod/Min/Max/Mean

- src/Accelerators/CMakeLists.txt
- src/Compiler/CMakeLists.txt
Moves MLIRIR from DEPENDS section of `add_onnx_mlir_library` to
`LINK_LIBS PUBLIC` section across CMakeLists files.
Other instances were corrected by 368d368a31410c6e2047e122df425184506d741d.
Fixes #1988.
> [cmake] Fix linkage of MLIRIR target at various locations

- src/Dialect/ONNX/ONNX.td
- src/Dialect/ONNX/ONNXOps/Additional/None.cpp
see https://discourse.llvm.org/t/psa-new-improved-fold-method-signature-has-landed-please-update-your-downstream-projects/67618
eliminated the warning:
```
src/Dialect/ONNX/ONNX.td:36:5: warning: Using deprecated def `kEmitRawAttributesFolder`
```
> migrated ONNX dialect to new fold API

- README.md
Right now, the meeting is hardwired in the README page. I moved it to the wiki page, with only a reference here to the wiki page. Easier to maintain.
> [non functional changes] Update of meeting calling info.

- src/Builder/ModelInputShaper.cpp
- src/Builder/ModelInputShaper.hpp
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- test/mlir/onnx/onnx_lowering_entry_point.mlir
After updating LLVM, we internally use `ShapedType::kDynamic`(that is `std::numeric_limits<int64_t>::min()`) because that is the way MLIR handles dynamic dimension.
But, for onnx-mlir's users, it is convenient to use `-1` to denote a dynamic dimension, e.g. in the model signatures or `--shapeInformation` option, which is easy to remember.
This patch fixes #1995 #1996 issues and add a LIT test for lowering `onnx.EntryPoint` to `krnl.entry_point`.
> Handle -1 in --shapeInformation option and model signature

- src/Transform/ONNX/ONNXDimAnalysis.cpp
There is a bug in the unknown dimension analysis where it tried to explore a dimension of a ONNXConstantOp.
In such case, a dimension is a constant, so we can stop the analysis.
> Stop unknown dimension analysis when a dimension comes from a constant

- test/backend/inference_backend.py
Based on the information available from `onnx`, access to these has been lost for the moment (possibly forever?). Until there's a better solution, disable them to unblock everyone.
See https://github.com/onnx/onnx-mlir/issues/2001 and https://github.com/onnx/onnx/issues/4857 for more information
> Disable failing onnx models from the backend tests

- docs/BuildOnLinuxOSX.md
- docs/BuildOnWindows.md
- src/Compiler/CompilerUtils.cpp
- src/Conversion/KrnlToLLVM/ConvertKrnlToLLVM.cpp
- src/Dialect/ONNX/ONNXOps/Sequence/Sequence.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Optional.cpp
- test/modellib/LSTMModel.cpp
- test/onnx2mlir/CustomFnTest.cpp
- utils/clone-mlir.sh
This is using the green commits that match torch-mlir and that are published here (https://github.com/onnx/onnx-mlir/issues/1971#issuecomment-1419182049).
Green LLVM commit: `ba8b8a73fcb6b830e63cd8e20c6e13b2a14d69bf`
Green MHLO commit: `d5a2c51fd78cca9dd91611137cc3d3e89ddf6aa9` (branch: `greencommit/2023-02-06-ba8b8a73`)
The major changes that impact the update are:
https://reviews.llvm.org/D142855
https://reviews.llvm.org/D142463
https://reviews.llvm.org/D137731
Overall, this is a pretty easy update.
> LLVM Update to green commit for the week of 2/6/2023

- src/Dialect/ONNX/ElementsAttr/Strides.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Upsample.cpp
Replace "sanity" references with "safety"
Signed-off-by: Charles Volzka <cjvolzka@us.ibm.com>
> Replace "sanity" references with "safety"

- .azure-pipelines/Windows-CI.yml
- .github/workflows/macos-amd64-build.yml
- README.md
- docs/BuildOnWindows.md
- docs/Prerequisite.md
- requirements.txt
This adds a `requirements.txt` file at the root of the repository with the current PyPi package requirements and pinned versions for them. This is the equivalent of the mlir change that pinned their package requirements (https://reviews.llvm.org/D142563). 
This change is pinning the requirements to a specific version (or a range) depending on the requirement. A couple of considerations:
* numpy 1.24 deprecates np.object, np.bool, np.float, np.complex, np.str, and np.int which are used heavily in onnx-mlir
* not all versions of each package are available on every platform - to the best of my knowledge, these ranges should work on Ubuntu, CentOS, macOS and Windows
Adding a minimum and maximum version, or pinning to a specific versions where possible, helps with two major goals - security …
> Add a requirements.txt file for PyPi requirements in onnx-mlir

- docs/doc_example/CMakeLists.txt
This should, in theory, work on all platforms now.
Before this change, the test worked correctly with `Makefiles` on any platform because `Makefiles` always use the full path to the library. It also worked correctly on Windows regardless of generator because by default an executable will look for any `dlls` in the same directory first. However, it did not work correctly with `ninja` on non-Windows because `ninja` was converting the full path to a path relative to the root of the binary tree for the build step and then failing at execution. More specifically, the library would be linked as `docs/doc_example/add.so`, then at execution time of the test, the test would run from `docs/doc_example`, so it would look for the library in `docs/doc_example/docs/doc_example`. The behavior could not …
> Make the doc example test work with Ninja on Ubuntu

- src/Dialect/ONNX/ElementsAttr/BType.hpp
- src/Dialect/ONNX/ElementsAttr/DisposableElementsAttr.hpp
This fixes warnings that are present when building with clang-15.
> NFC: remove redundant or unnecessary semicolons

- src/Dialect/ONNX/ElementsAttr/DisposableElementsAttr.cpp
- src/Dialect/ONNX/ElementsAttr/DisposableElementsAttr.hpp
- src/Dialect/ONNX/ONNXAttributes.cpp
Solves #1975 
I changed the print format a little bit, removing the `#` before the "id", so it's now
```
#onnx.dense_disposable<1:"0x00010000">
```
instead of
```
#onnx.dense_disposable<1:"0x00010000">
```
I made the change because I couldn't figure out how to parse the `#`
I ran it on @tungld's example model bertsquad-12-int8.onnx and I no longer see the error `error: unknown attribute 'dense_disposable' in dialect 'ONNX'`
> parse DisposableElementsAttr

- src/Conversion/KrnlToLLVM/KrnlToLLVMHelper.cpp
- src/Dialect/ONNX/ONNXOps/ShapeHelper.cpp
- test/mlir/krnl/input_verification.mlir
- test/mlir/krnl/krnl_category_mapper.mlir
An error occurs with “Redefinition of symbol named free” in KrnlToLLVM conversion pass, because the current onnx-mlir generate each symbol with its corresponding string used in the onnx model. 
This PR prepends “om_”  to symbol names for string constants to avoid the symbol conflict with C function names and symbol names for the string constants.
> Fix duplicated symbol errors in KrnlToLLVM conversion.

- src/Conversion/KrnlToLLVM/KrnlGlobal.cpp
- test/mlir/krnl/krnl_category_mapper.mlir
Assertion error occurs in KrnlToLLVM conversion pass for onnx.ml.CategoryMapper with 129+ element string arrays. 
This PR fixes this error in the KrnlToLLVM conversion pass. Reported in issue #2045.
The compilation time may be long in this case, because symbols are generated for each elements in string array, the compilation time is long, so that compilation time optimization may be necessary.
> Fix assertion error in the KrnlToLLVM conversion pass for onnx.ml.CategoryMapper with 129+ element string arrays. 

- utils/RunONNXModel.py
- utils/RunONNXModelZoo.py
- add --log-to-file to optionally log output to a file
- allow max 30 minutes for compilation+inference for a model check
> Fix Modelzoo Check

- docs/mnist_example/README.md
- docs/mnist_example/mnist.cpp
- src/Conversion/KrnlToLLVM/KrnlEntryPoint.cpp
- src/Conversion/KrnlToLLVM/RuntimeAPI.cpp
- test/modellib/CategoryMapperModel.cpp
- test/modellib/ConvModel.cpp
- test/modellib/GRUModel.cpp
- test/modellib/GemmModel.cpp
- test/modellib/LSTMModel.cpp
- test/modellib/LeakyReluModel.cpp
- test/modellib/RNNModel.cpp
- test/modellib/ScanModel.cpp
- utils/RunONNXLib.cpp
* The generated llvm code for run_main_graph was still using malloc to create a temporary list array. This changes that to a stack alloc instead.
* Fixed some warnings
* Fix some leaks in code examples
* Removed unused param from `CREATE_OMTENSOR_LIST`
> Fix run_man_graph leak after OMTensorList changes

- utils/RunONNXLib.cpp
dll_omTensorCreateWithOwnership is actaully using omTensorCreate, which doesn't set _owning to true so tensor data was not freed by omTensorListDestroy.
> Fix memory leak in utils/RunONNXLib.cpp

- src/Accelerators/NNPA/Conversion/ZHighToZLow/ZHighToZLow.cpp
- src/Accelerators/NNPA/Transform/ZLow/ZLowRewrite.cpp
- src/Dialect/ONNX/ONNXOps/Additional/ShapeTransform.cpp
- test/modellib/MatMulModel.cpp
Fixed 4 compiler warnings reported by Apple clang version 14.0.0.
Please see the 4 commits for details.
AFAICT they were introduced by:
@hamptonm1 in #2046
@tungld in #2011 and #2022
@AlexandreEichenberger in #2042
> fix compiler warnings

- CMakeLists.txt
- src/Transform/ONNX/Decompose.cpp
This is needed for Groq to disable this.
> introduce cmake option ONNX_MLIR_DECOMP_ONNX_CONVTRANSPOSE

- include/onnx-mlir/Runtime/OMTensor.h
- include/onnx-mlir/Runtime/OMTensorList.h
- src/Runtime/ExecutionSession.cpp
- src/Runtime/OMResize.inc
- src/Runtime/OMTensor.inc
- src/Runtime/OMTensorList.inc
- src/Runtime/jni/jniwrapper.c
- test/modellib/ModelLib.cpp
- test/numerical/TestGemm.cpp
- test/numerical/TestScan.cpp
- test/unit/Runtime/OMTensorTest.c
* Set parameters returns of arrays like `shape`, `strides` and some TensorList pointers as `const`
* Implements https://github.com/onnx/onnx-mlir/issues/2075
> Set const for array passed or returned from C/C++ API

- src/Accelerators/NNPA/Dialect/ZHigh/ZHighOps/OpHelper.cpp
- src/Accelerators/NNPA/Dialect/ZHigh/ZHighOps/OpHelper.hpp
- src/Accelerators/NNPA/Dialect/ZHigh/ZHighOps/OpHelper.td
- src/Accelerators/NNPA/Dialect/ZHigh/ZHighOps/Stick/ZHighStick.td
- test/mlir/accelerators/nnpa/transform/zhigh-combine.mlir
Because of [an issue](https://github.com/onnx/onnx-mlir/issues/1940) about wrong index access for 1D and 2DS layout, this patch disables the replacement of unstic/stick by LayoutTransform in case of 1D and 2DS layout.
> Do not replace unstick/stick by LayoutTransform when layout is 1D or 2DS

- src/Conversion/ONNXToKrnl/Tensor/Transpose.cpp
- utils/RunONNXLib.cpp
This patch fixes an issue about IndexExprScope in TransposesOp lowering and a function signature in RunONNXLib.cpp
> Fix IndexExprScope in TransposesOp lowering

- docs/SupportedONNXOps-cpu.md
- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- test/backend/inference_backend.py
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
- utils/RunONNXModel.py
This patch supports ONNXDequantizeLinear, where:
- ONNXDequantizeLinear is lowered to Krnl dialect
- Backend and LIT tests for ONNXDequantizeLinear are enables.
- Only support for per-tensor or layer dequantization. Not support for per-axis dequantization at this moment.
Besides, this patch edits `RunONNXModel.py` script to support `ui8` input.
The lowering of ONNXDequantizeLinear borrows `ONNXElementwiseUnaryOpLowering`, so this patch contains some code from #2056. It's better to land #2056 before this patch.
> Lower ONNXDequantizeLinear to krnl

- src/Support/TypeUtilities.cpp
- src/Support/TypeUtilities.hpp
- src/Transform/ONNX/ConstProp.td
- test/mlir/onnx/onnx_constprop.mlir
This patch adds an additional condition for ConstantOfShape's constant propagation that is to check whether the output type is static or not. Constant propagation should happen when the output type is static (for example by shape inference).
> Fix an error in constant propagation for ConstantOfShape

- src/Dialect/ONNX/ONNXOps/Additional/LayoutTransform.cpp
The else if statement is now binding to the if outside the for loop, which is not the intended behavior. I've added some additional curly braces to fix this.
> fix issue with if statement nesting in ONNXLayoutTransformOp::verify

- src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.cpp
- src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.hpp
- src/Transform/ONNX/ConstProp.cpp
- src/Transform/ONNX/ConstProp.td
- test/mlir/onnx/onnx_constprop.mlir
Note that it is implemented with a reusable helper method ElementsAttrBuilder::matMul() which is designed to also work for the MatMul op, so it will be easy to add const prop for MatMul afterwards.
> MatMulInteger const prop

- src/Dialect/ONNX/ONNXOps/OpHelper.cpp
- src/Dialect/ONNX/ONNXOps/OpHelper.hpp
- src/Dialect/ONNX/Rewrite.cpp
- src/Dialect/ONNX/Rewrite.td
- src/Transform/ONNX/ConstProp.cpp
- src/Transform/ONNX/Decompose.td
I studied AreTheSameConstantOpDenseAttr() to see if it was a candidate for using the ElementsAttr equal() function in PR #2114. I discovered that it isn't. I found it a little bit confusing and this PR attempts to to simplify it and clarify how it's used.
In more detail: Renamed `AreTheSameAxisArray` and `AreTheSameConstantOpDenseAttr` to `AreTheSameAxesArrayAttr` and `AreTheSameAxesConstant` and cleaned up their comments, contracts, and implementation. Moved them from OpHelper to Rewrite.cpp because they are only used in Rewrite.td. Also simplified the implementation of `createArrayAttrFromConstantOp`.
> simplify AreTheSameAxes logic and createArrayAttrFromConstantOp

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHigh.td
- src/Builder/FrontendDialectHelper.cpp
- src/Builder/FrontendDialectTransformer.cpp
- src/Dialect/ONNX/ONNX.td
- src/Dialect/ONNX/ONNXOps/OpHelper.cpp
- src/Dialect/ONNX/ONNXOps/OpHelper.hpp
- src/Dialect/ONNX/Rewrite.td
- src/Transform/ONNX/Decompose.cpp
- src/Transform/ONNX/Decompose.td
- test/mlir/onnx/onnx_canonicalization.mlir
- test/mlir/onnx/onnx_decompose.mlir
Replaced the use of empty tensors to represent 'none' in ONNXResizeOp decompositions and simplified isFromNone() to
```
// Test if the value is none. Since none is a unit value it never makes a
// difference whether it's a constant (the result of ONNXNoneOp) or the
// optional result of some other op (e.g. ONNXDropoutOp mask result).
// Note: It's ok to inline the isa<NoneType> test and not call this function.
inline bool isFromNone(mlir::Value value) {
return llvm::isa<mlir::NoneType>(value.getType());
}
```
I inlined the implementation to emphasize that it's fine to inline the `isa<NoneType>` test like we already do in many places.
> use the same 'none' of NoneType everywhere

- CONTRIBUTING.md
- docs/DocumentList.md
- docs/DynamicDimensionAnalysis.md
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.cpp
- src/Dialect/ONNX/ONNXDimAnalysis.cpp
- src/Dialect/ONNX/ONNXDimAnalysis.hpp
- src/Dialect/ONNX/ONNXOps/OpHelper.cpp
- src/Dialect/ONNX/ONNXOps/OpHelper.hpp
- test/mlir/krnl/permute.mlir
This patch adds some additional functions to DimAnalysis:
- `sameDynShape` to check if dynamic dimensions from two tensors are the same or not by ignoring static dimensions
- `broadcastLastDim` to check if one tensor is broadcasting to the other tensor using **the last dimension**
For example:
- For `tensor<?x1xf32>` and `tensor<?x5xf32`:  `sameDynShape` and `broadcastLastDim` return `true` if their dynamic dimensions are the same.
- For `tensor<?x2xf32>` and `tensor<?x5xf32`, `sameDynShape` returns `true` but `broadcastLastDim` return `false`  if their dynamic dimensions are the same.
- For `tensor<?x2x1xf32>` and `tensor<?x?x5xf32`, `sameDynShape` and `broadcastLastDim` return `false` because it cannot check equality of the second dimension: `2` vs `?`.
This patch also re-words …
> Add sameDynShape and broadcastLastDim in DimAnalysis and re-word unknown to dynamic

- src/Dialect/ONNX/ONNXOps/ControlFlow/Loop.cpp
- src/Dialect/ONNX/ONNXOps/ControlFlow/Scan.cpp
- src/Dialect/ONNX/ONNXOps/NN/Pooling.cpp
- test/mlir/onnx/onnx_lowering.mlir
- test/mlir/onnx/onnx_lowering_O3.mlir
- test/mlir/onnx/onnx_shape_inference.mlir
Fixed inferShapes() crashes on unranked inputs in LoopOp, ScanOp, ONNXGlobalAveragePoolOp, ONNXGlobalLpPoolOp, ONNXGlobalMaxPoolOp. Added lit tests which would crash before these fixes. These crashes were discovered in draft PR #2098.
Cleaned up the LoopOp and ScanOp inferShapes() implementations to make them easier to read and compare.
Also fixed ill-formed loops in test_loop lit test is onnx_lowering.mlir and onnx_lowering_O3.mlir which crashed on a new assert 
```
assert(loopBody.getNumArguments() == 2 + getVInitial().size())
```
in ONNXLoopOp::inferShapes(). I added a TODO to add a verify() method to check this.
> make inferShapes() not crash on unranked inputs

- test/backend/common.py
Checking if compiled model exists or not is not reliable.
> Fix test error report by passing check=True to subprocess.run

- src/Dialect/ONNX/ElementsAttr/DisposableElementsAttr.cpp
- src/Transform/ONNX/ONNXOpTransformPass.cpp
fixes #1963
Tested on the arcfaceresnet100-8.onnx model. On my MacBook when I run:
```
RelWithDebInfo/bin/onnx-mlir arcfaceresnet100-8.onnx --mlir-timing
```
ONNXOpTransformPass takes 2.7387s before the change and 0.0032s after the change.
> OperationFingerPrint instead of printing to sha1_ostream

- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
- test/mlir/onnx/onnx_lowering_with_canonicalize_O3.mlir
The lowering_with_canonicalize lit tests lowered test_if_sign differently than the real compiler because it skipped constant propagation which hoists constants out of the if and else branches and somehow leads to different lowered code.
Now the constants are hoisted in the lit test just like constant propagation would do.
This was discovered in PR #2098 where the new pattern-based shape inference hoists constants like propagation does.
> hoist constants in test_if_sign lit test

- src/Compiler/CompilerOptions.cpp
- src/Compiler/CompilerOptions.hpp
- src/Compiler/CompilerPasses.cpp
- src/InitOMPasses.hpp
- src/Pass/Passes.hpp
- src/Transform/ONNX/CMakeLists.txt
- src/Transform/ONNX/ONNXHybridTransformPass.cpp
Includes a new pattern-based shape inference implementation.
So far only combines shape inference and canonicalization but the plan is to include constant propagation and decomposition so that a single pass with all the patterns can cascade shape inference and all the transforms in a single pass.
I encountered a model with a long dependency chain between shape inference, canonicalization, and constant propagation which requires an incredible number of repetitive passes with the current pass infrastructure.
See PR #1770 for an earlier version of this PR.
> ONNXHybridTransformPass

- src/Dialect/ONNX/ONNXDimAnalysis.cpp
- test/mlir/onnx/onnx_dim_analysis.mlir
This patch improves DimAnalysis to handle a case about Reshape that was found in the T5 model in onnx model zoo.
> Add a case about Reshape to DimAnalysis

- src/Transform/ONNX/Decompose.cpp
- test/mlir/onnx/onnx_decompose.mlir
Transform rules for onnx.PadV13 are prepared, but onnx.PadV13 ops are not transformed to onnx.Pad (probably by typo), and the following error messages are shown.
```
error: 'onnx.PadV13' op op is not supported at this time. Please open an issue on https://github.com/onnx/onnx-mlir and/or consider contributing code. Error encountered in shape inference.
```
This PR includes fixe and lit test of onnx.PadV13 to onnx.Pad transformation issue.
> Fix onnx.PadV13 to onnx.Pad transformation issue.

- src/Dialect/ONNX/ONNXDimAnalysis.cpp
- test/mlir/onnx/onnx_dim_analysis.mlir
This patch adds a pattern for Tile op in DimAnalysis. 
Dimension in `output` tensor is dimension in `input` tensor multiplied by value in `repeats` tensor. (output_dim[i] = input_dim[i] * repeats[i])
So, if input_dim[i] is 1, output_dim[i]  and repeats[i] are equal.
Example
```
%0 = "onnx.Dim"(%arg0) {axis = 0 : si64} : (tensor<?x?xi64>) -> tensor<1xi64>
%1 = "onnx.Dim"(%arg0) {axis = 1 : si64} : (tensor<?x?xi64>) -> tensor<1xi64>
%2 = "onnx.Concat"(%0, %1) {axis = 0 : si64} : (tensor<1xi64>, tensor<1xi64>) -> tensor<2xi64>
%3 = "onnx.Tile"(%arg1, %3) : (tensor<1x1xi64>, tensor<2xi64>) -> tensor<?x?xi64>
```
This pattern appears in `t5-decoder-with-lm-head.onnx` in model zoo.
> Add a pattern for Tile op in DimAnalysis 

- src/Runtime/jni/jniwrapper.c
- src/Runtime/jni/src/com/ibm/onnxmlir/OMTensor.java
Fixes https://github.com/onnx/onnx-mlir/issues/2171. The Java `OMTensor` object was not taking full ownership duties of the backing data within the native `OMTensor` object, leading to a memory leak. This fix solves the issue by allocating a new `ByteBuffer` in the JNI `OMTensor` constructor with a copy, leaving the original data to be freed along with the jni `OMTensor`.
Some initial timings suggest that there isn't any meaningful difference in timing due to the copy in the YOLOv3-12 and MNIST models.
> Fix memory leak due to unallocated tensor data

- src/Runtime/jni/jniwrapper.c
- src/Runtime/jni/src/com/ibm/onnxmlir/OMTensor.java
Cherry Pick of https://github.com/onnx/onnx-mlir/pull/2176 to fix https://github.com/onnx/onnx-mlir/issues/2171 in the 0.4.0 release.
The Java `OMTensor` object was not taking full ownership duties of the backing data within the native `OMTensor` object, leading to a memory leak. This fix solves the issue by allocating a new `ByteBuffer` in the JNI `OMTensor` constructor with a copy, leaving the original data to be freed along with the jni `OMTensor`.
Some initial timings suggest that there isn't any meaningful difference in timing due to the copy in the YOLOv3-12 and MNIST models.
(cherry picked from commit dca1b634ed03ef68b09669d3f0c3da398dacb4ed)
> Fix memory leak due to unallocated tensor data (#2176)

- src/Conversion/ONNXToMhlo/DialectBuilder.cpp
- src/Conversion/ONNXToMhlo/Math/Reduction.cpp
- src/Conversion/ONNXToMhlo/Tensor/Expand.cpp
- src/Conversion/ONNXToMhlo/Tensor/Reshape.cpp
- src/Transform/ONNX/Decompose.cpp
- test/mlir/conversion/onnx_to_mhlo/Math/GlobalPooling.mlir
- test/mlir/conversion/onnx_to_mhlo/Math/Reduction.mlir
- test/mlir/conversion/onnx_to_mhlo/Math/Softmax.mlir
- test/mlir/conversion/onnx_to_mhlo/Tensor/Expand.mlir
- test/mlir/conversion/onnx_to_mhlo/Tensor/Reshape.mlir
This pull request lowers the following ops to MHLO:
1. reduction ops with dynamic shape
2. ONNXReshapeOp with dynamic shape (shape-related IR generated with IndexExpr)
3. reduction ops on integer input tensor
4. ONNXExpandOp on integer input tensor
1 & 2 together solve issue https://github.com/onnx/onnx-mlir/issues/2181
LIT tests are added correspondingly.
@AlexandreEichenberger @tungld @hamptonm1 @yaochengji
> [MHLO] lowering to MHLO for ReshapeOp, ExpandOp, and reduction ops

- src/Dialect/Mlir/IndexExpr.cpp
- src/Dialect/Mlir/IndexExpr.hpp
- src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.cpp
- src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.hpp
- src/Dialect/ONNX/ElementsAttr/ElementsAttrHelper.cpp
- src/Transform/ONNX/ConstProp.cpp
This addresses leftover TODOs from PR #1874 and will make it easier to migrate current constant propagation for ScatterND, Slice, Concat, and Gather to constant folding in the future, see issue #2143.
Also made IndexExpr::getLiteral/Shape/DynSymbols/OpOrFoldResults use ArrayRef like IndexExpr::getValues.
> move ConstProp implementations to ElementsAttrBuilder methods

- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/Conversion/ONNXToKrnl/Math/MatMul.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- test/mlir/onnx/onnx_lowering_with_canonicalize_O3.mlir
This patch uses DimAnalysis to detect broadcasting when lowering `N-D x N-D` ONNXMatMul to krnl dialect. If there is no broadcasting, SIMD path will be used for the lowering.
> Use DimAnalysis in lowering MatMul

- src/Dialect/ONNX/ONNXDimAnalysis.cpp
- src/Dialect/ONNX/ONNXOps.cpp
- src/Dialect/ONNX/ONNXOps/ShapeHelper.hpp
- src/Interface/ShapeHelperOpInterface.hpp
- src/Interface/ShapeHelperOpInterface.td
- test/mlir/onnx/onnx_shape_inference.mlir
Before, calling shape inference on ops that were unimplemented failed. This caused an issue as some ONNX operations may be lowered after shape inference to other ONNX ops for which shape inference is known.
Thus the "default" shape inference for unimplemented ops `ONNXUnimplementedOpShapeHelper` now succeeds when calling `computeShape`. At times, we still need to know if compute shape is implemented (e.g. for Dim Analysis). Thus `isImplemented()` can be used on all shape inference helper to determine whether there is an actual implementation. In case of Dim Analysis, ops without `isImplemented() == true` are conservatively approximated.
I didn't implement a new pass to verify that all ops (after a certain point) have implemented shape inference. Instead, I just added an assert on using …
> Shape Inference now succeeds for unimplemented ops

- src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.cpp
- src/Dialect/ONNX/ElementsAttr/Strides.cpp
- src/Dialect/ONNX/ElementsAttr/StridesRange.hpp
- src/Dialect/ONNX/ElementsAttr/StridesRange.hpp.inc
Changed `pos` to `offsets` and the type from `size_t` to `int64_t` to match how negative values are used with negative strides in the case of negative steps in `ElementsAttrBuilder::slice()`
> fix StridesIterator offsets to properly support negative values

- src/Transform/ONNX/Decompose.cpp
- src/Transform/ONNX/Decompose.td
- test/mlir/onnx/onnx_decompose.mlir
It seems I forgot to add a decomposition for SplitV13 when I upgraded Split for opset 18
> Splitv13 decomp

- docs/mnist_example/requirements.txt
- requirements.txt
I have upgraded the following based on the synk scan results https://app.snyk.io/org/megan-uqq:
numpy to `1.22.2`
pillow to `9.4.0`
> Upgrade numpy and pillow dependencies 

- docs/SupportedONNXOps-cpu.md
- src/Conversion/ONNXToKrnl/CMakeLists.txt
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/Conversion/ONNXToKrnl/Math/Trilu.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- test/backend/inference_backend.py
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
- utils/documentOps.py
This patch lowers ONNXTrilu into Krnl.
ONNXTrilu is like an unary operation, but its computation uses loop indices that has not supported yet by the lowering pattern of unary operations. So, this patch lowers ONNXTrilu as an independent operation.
> Lower Trilu in opset 14 to krnl

- src/Builder/FrontendDialectHelper.cpp
- src/Builder/FrontendDialectHelper.hpp
- src/Builder/FrontendDialectTransformer.cpp
Follow up to PR #2133 to distinguish `none` from empty tensors.
Also removed unnecessary `EmitInitializerForInputTensor()` function and cleaned up the use of namespaces in FrontendDialectHelper.cpp.
> don't treat empty tensor as none

- docs/mnist_example/requirements.txt
We have to upgrade torch and torchvision to avoid vulnerabilities mentioned in the LFX and snyk scans. 
`torchvision 0.15.1 depends on torch==2.0.0`
> Upgrade torch and torchvision

- utils/RunONNXModel.py
Added an argument in `--verify-with-softmax` option to specify axis along which Softmax is performed. -1 indicates last dimension.
ex.
--verify ref --verify-with-softmax -1
> An option to specify axis for verification with softmax in RunONNXModel.py

- docs/Dialects/onnx.md
- src/Builder/FrontendDialectTransformer.cpp
- src/Conversion/ONNXToKrnl/ControlFlow/If.cpp
- src/Conversion/ONNXToKrnl/ControlFlow/Loop.cpp
- src/Dialect/ONNX/AdditionalONNXOps.td
- src/Dialect/ONNX/Rewrite.cpp
- src/Transform/ONNX/InstrumentPass.cpp
- src/Transform/ONNX/ONNXHybridTransformPass.cpp
- src/Transform/ONNX/ShapeInference.cpp
- test/mlir/onnx/invalid.mlir
- test/mlir/onnx/onnx_canonicalization.mlir
- test/mlir/onnx/onnx_lowering.mlir
- test/mlir/onnx/onnx_lowering_O3.mlir
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
- test/mlir/onnx/onnx_lowering_with_canonicalize_O3.mlir
- test/mlir/onnx/onnx_shape_inference.mlir
- test/mlir/onnx/parse/test_range_float_type_positive_delta_expanded.json
- test/modellib/ScanModel.cpp
- test/numerical/TestLoop.cpp
to follow the MLIR naming scheme in the SCF dialect:
https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Dialect/SCF/IR/SCFOps.td
follows the suggestion by @AlexandreEichenberger: https://github.com/onnx/onnx-mlir/pull/2239#discussion_r1200101718
> rename ONNXReturnOp to ONNXYieldOp

- src/Accelerators/NNPA/Dialect/ZHigh/ZHighOps/Stick/Stick.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Compress.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/ConstantOfShape.cpp
- test/mlir/onnx/invalid.mlir
Don't run inferShapes() on inputs the shape helper computeShape() cannot handle.
Fixes #2271.
> fix inferShapes() for inputs without static shapes

- src/Transform/ONNX/ShapeInference.cpp
- src/Transform/ONNX/ShapeInference.hpp
- src/Transform/ONNX/ShapeInferencePass.cpp
Made matchAndRewrite() in shape inference patterns InferShapesPattern and YieldShapesPattern return failure() when no op changes are made. Otherwise applyPatternsAndFoldGreedily() would repeat GreedyRewriteConfig.maxIterations==10 times.
Also copied the optimization from the old shape inference to not (re)infer shapes for simple ops (without subgraphs) with known and static result shapes.
> reduce repeated pattern-based shape inference computations

- src/Dialect/ONNX/ONNXOps.td.inc
- src/Dialect/ONNX/ONNXOps/Tensor/Resize.cpp
- src/Dialect/ONNX/Rewrite.cpp
- test/mlir/onnx/onnx_canonicalization.mlir
- utils/gen_onnx_mlir.py
The yolo4 model uses a float tensor with shape [0] to represent that roi
or scales is absent in accordance with the Resize v11 spec. This violates
the spec from v13 onwards which says that empty string
inputs represents absent arguments in the protobuf model representation.
We work around this by interpreting a tensor with empty shape as an
alternative way to express that an input is absent.
Fixes #2276
> interpret empty tensors as absent Resize inputs

- src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.cpp
- src/Dialect/ONNX/ElementsAttr/ElementsAttrBuilder.hpp
- src/Dialect/ONNX/ElementsAttr/StridesRange.hpp
- src/Transform/ONNX/ConstProp.cpp
- src/Transform/ONNX/ConstProp.td
- test/mlir/onnx/onnx_constprop.mlir
This PR illustrates the problem with changing shape in constant propagation, which doesn't work with `func.return` and was solved with `onnx.Return` in PR #2239. See the lit test in onnx_constprop.mlir:
```
func.func @test_nonzero() -> tensor<2x?xi64> {
%0 = "onnx.Constant"() {value = dense<[[2, 1], [0, 2], [0, 1]]> : tensor<3x2xi8>} : () -> tensor<3x2xi8>
%1 = "onnx.NonZero"(%0) : (tensor<3x2xi8>) -> tensor<2x?xi64>
// NOTE: We cannot use return (i.e. "func.return") because the change of shape makes
// func::ReturnOp::verify() fail with:
//
//   error: type of return operand 0 ('tensor<2x4xi64>') doesn't match function result type ('tensor<2x?xi64>') in function @test_nonzero
//
onnx.Return %1 : tensor<2x?xi64>
}
```
> NonZero constant propagation

- src/Dialect/ONNX/ONNXOps/Tensor/Expand.cpp
We let shape inference of Expand pass when its shape input is still unknown (say, `tensor<*xdtype>`). Otherwise, it causes shape inference pass failed.
> Expand's shape inference returns success when shape input is unknown

- src/Builder/FrontendDialectTransformer.cpp
- test/mlir/onnx/parse/prims_convert_element_type.onnxtext
This PR fixes a bug in function inlining where the substituted attributes were lost (accidentally imported the nodes before substitution).
I discovered the bug with @MikeHolman's  model maf_gpt2_tiny_display_name.onnx with model local function.
Before the fix in this PR compilation failed with:
```
$ onnx-mlir maf_gpt2_tiny_display_name.onnx
Unsupported data type encountered.
UNREACHABLE executed at /Users/slassen/git/onnx-mlir-einsum/src/Dialect/ONNX/ONNXOps/OpHelper.cpp:619!
```
after the fix the compilation fails with:
```
Assertion failed: (isa<To>(Val) && "cast<Ty>() argument of incompatible type!"), function cast, file Casting.h, line 566.
```
because there is an If op where the then branch has a tensor type `tensor<?xf32>` and the else branch has NoneType - let's get back to fixing …
> use graph nodes with substituted attributes

- src/Dialect/ONNX/ONNXOps/Quantize/DequantizeLinear.cpp
squeezenet1.0-13-qdq and ssd_mobilenet_v1_13-qdq from the model zoo hit this error
with this PR these models now make it through the frontend passes and fail in lowering to Krnl instead:
```
$ onnx-mlir /tmp/squeezenet1.0-13-qdq.onnx
Assertion failed: (isScalarValue(operands[i]) && "unary expected scalar additional values"), function operator(), file Elementwise.cpp, line 1991.
zsh: abort      Debug/bin/onnx-mlir /tmp/squeezenet1.0-13-qdq.onnx
```
```
$ onnx-mlir /tmp/ssd_mobilenet_v1_13-qdq.onnx
Scan output for while loop is not supported
UNREACHABLE executed at /Users/slassen/git/onnx-mlir-einsum/src/Conversion/ONNXToKrnl/ControlFlow/Loop.cpp:392!
zsh: abort      Debug/bin/onnx-mlir /tmp/ssd_mobilenet_v1_13-qdq.onnx
```
> make DequantizeLinear i32 zero check work for non-splat zeros

- src/Compiler/CompilerOptions.cpp
- src/Transform/ONNX/ShapeInference.cpp
Reverting PR #2270 which disabled pattern-based shape inference by default.
The problems that caused us to disable it in PR #2270 were all shape inference bugs that were hidden by the legacy shape inference (see the bug fixes in PR #2273).
Let's go back to shape-based shape inference by default so we can surface and fix any other hidden bugs and ultimately phase out the legacy shape inference which has bit rotted, see PR #2243.
> reenable pattern-based shape inference by default

- src/Transform/ONNX/ConstProp.td
bidaf-11-int8.onnx from model zoo failed with
```
Assertion failed: (type.hasStaticShape() && "type must have static shape"), function getRaw, file BuiltinAttributes.cpp, line 1317.
```
after this PR it fails in lowering because of unranked types
> restrict MatMulIntegerConstZero patterns to ops with static result shape

- test/accelerators/NNPA/numerical/CMakeLists.txt
I forgot this line in https://github.com/onnx/onnx-mlir/pull/2283 to enable numerical tests for NNPA in `check-onnx-backend-numerical-nnpa`
> [NNPA] Fix to run numerical tests for NNPA

- src/Dialect/ONNX/ONNXOps.td.inc
- src/Dialect/ONNX/ONNXOps/Tensor/Reshape.cpp
- test/mlir/onnx/onnx_shape_inference_error.mlir
- utils/gen_onnx_mlir.py
with this change tiny-yolov3-11.onnx compiles without error message and no longer fails shape inference with `-pattern-shape-inference=false`
see the last comments in PR #2301
> implement ONNXReshapeOp::verify() and don't fail in inferShapes()

- utils/gen_onnx_mlir.py
removes these warnings
```
utils/gen_onnx_mlir.py:1003: UserWarning: OpSchema.FormalParameter.typeStr is deprecated and will be removed in 1.16. Use OpSchema.FormalParameter.type_str instead.
if input.typeStr :
utils/gen_onnx_mlir.py:1004: UserWarning: OpSchema.FormalParameter.typeStr is deprecated and will be removed in 1.16. Use OpSchema.FormalParameter.type_str instead.
if not input.typeStr in type_str_dict :
utils/gen_onnx_mlir.py:1010: UserWarning: OpSchema.FormalParameter.typeStr is deprecated and will be removed in 1.16. Use OpSchema.FormalParameter.type_str instead.
return type_str_dict[input.typeStr]
utils/gen_onnx_mlir.py:704: UserWarning: OpSchema.FormalParameter.typeStr is deprecated and will be removed in 1.16. Use OpSchema.FormalParameter.type_str instead.
if input.typeStr : …
```
> fix deprecated warnings in gen_onnx_mlir.py

- src/Transform/ONNX/Decompose.cpp
- src/Transform/ONNX/Decompose.td
addresses failure of MaskRCNN-10.onnx from model zoo
before it failed with:
```
Assertion failed: (!inputType.isDynamicDim(axis) && "Spatial dimensions for input data tensor need to be static."), function emitSplitAxisOutputLength1, file Decompose.cpp, line 326
```
after it fails with:
```
loc("1140"): error: 'arith.extui' op result #0 must be signless-fixed-width-integer-like, but got 'ui8'
```
> only decompose ConvTranspose when spatial dims are static

- docs/BuildOnLinuxOSX.md
- src/Support/FloatingPoint16.hpp
- test/unit/FloatingPoint16/CMakeLists.txt
- test/unit/FloatingPoint16/TestFloatingPoint16.cpp
When the CPU is known to support native conversion between float and float_16, use them in class float_16 below to override the slow default APFloat-based conversions.
Implemented for ARM64 when `__ARM_FP16_FORMAT_IEEE` is defined and for x86-64 when `__F16C__` is defined.
Added benchmarks of conversion between float and float_16 in TestFloatingPoint16.cpp.
Measured the benchmarks on a MacBook pro with Apple M1 Pro cpu. Before the per-CPU optimization:
```
Benchmark                          Time             CPU   Iterations
--------------------------------------------------------------------
BM_F32_TO_FP16<float_16>     2655030 ns      2654890 ns          263
BM_F32_TO_FP16<bfloat_16>    2741322 ns      2741320 ns          259
BM_FP16_TO_F32<float_16>     1824425 ns      1824426 ns …
```
> override float_16::to/fromFloat() with per-CPU optimized versions 

- src/Runtime/OMTensor.inc
- test/backend/input_verification_backend.py
- utils/check-onnx-backend-numerical.sh
before this PR it failed with:
```
Undefined symbols for architecture x86_64 (or arm64):
"___errno_location", referenced from:
_run_main_graph in add_wrong_data_type.o
```
on both x86_64 and arm64, because `__errno_location` is not defined on MacOS
as well as:
```
File "/Users/sorenlassen/git/onnx-mlir-einsum/build/test/backend/RelWithDebInfo/input_verification_backend.py", line 170, in _redirect_stdout
c_stdout = ctypes.c_void_p.in_dll(libc, 'stdout')
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: dlsym(RTLD_DEFAULT, stdout): symbol not found
```
which is fixed with the solution from stackoverflow: https://stackoverflow.com/a/47616945
> fix check-onnx-backend-input-verification on MacOS

- src/Dialect/Mlir/DialectBuilder.cpp
When I fix PR #2267, I found simple ifThenElse didn't work. So I investigated it.
In original code, original Block is split into `ifBlock` and `thenBlock`, and create additional blocks for `elseBlock` and `endBlock`. In this PR, `thenBlock` and `elseBlock` are inserted between `ifBlock` and `endBlock`.
Following figure shows my understanding. if there is "instruction A" in ifBlock, it seems to put unexpected place, but in this PR, the instruction put in expected place. I referred to [llvm-project/mlir/lib/Conversion/MemRefToLLVM/MemRefToLLVM.cpp](https://github.com/llvm/llvm-project/blob/main/mlir/lib/Conversion/MemRefToLLVM/MemRefToLLVM.cpp#L177-L184)
I want to hear your comments.
> Fix ifThenElse function of LLVMBuilder.

- src/Dialect/ONNX/ONNXOps/OpHelper.cpp
- src/Transform/ONNX/ConstProp.td
This should prevent any ONNXConstantOp with a DenseResourceElementsAttr value from getting into constant propagation (which doesn't support DenseResourceElementsAttr).
fixes #2344
> don't treat DenseResourceElementsAttr as dense ONNXConstant

- src/Dialect/ONNX/ElementsAttr/DisposablePool.cpp
- src/onnx-mlir.cpp
ScrubDisposablePass can be slow if there are large constants to rewrite from DisposableElementsAttr to DenseElementsAttr. This change parallelizes the work with each worker rewriting a subset of the constants. This speeds things up provided that the work is not all in a single large constant.
Tested it on arcfaceresnet100-8.onnx from the model zoo on a MacBook M1
```
RelWithDebInfo/bin/onnx-mlir arcfaceresnet100-8.onnx -mlir-timing --EmitMLIR
```
and saw the time spent in ScrubDisposablePass drop by 45% from 85ms to 47ms.
Also fixed MLIRContext creation in onnx-mlir.cpp to make the `--mlir-disable-threading` flag work and added debug logging, so you can see a debug log message confirming that threading is disabled if you call
```
onnx-mlir --mlir-disable-threading …
```
> parallel scrub

- .azure-pipelines/Windows-CI.yml
- .github/workflows/macos-amd64-build.yml
- docker/Dockerfile.onnx-mlir
- docker/Dockerfile.onnx-mlir-dev
- docs/SupportedONNXOps-cpu.md
- docs/doc_example/CMakeLists.txt
- docs/doc_example/main.c
- utils/check-doc-example.sh
- utils/documentOps.py
- utils/gen_onnx_mlir.py
Run quick check-docs or check-doc-example before slow numerical tests on all platforms.
Made OMRuntimeTest print and check the result tensor, like in OMRuntimeCppTest, and remove duplicate cruntime linkage.
Regenerated SupportedONNXOps-cpu.md. Changed documentOps.py and gen_onnx_mlir.py to use python3, otherwise 'ninja onnx_mlir_supported_ops' failed for me because I only have python3 and not python.
> miscellaneous docs fixes

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHigh.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.cpp
- src/Builder/FrontendDialectTransformer.cpp
- src/Dialect/ONNX/DialectBuilder.cpp
- src/Dialect/ONNX/ONNXOps/OpHelper.cpp
- src/Dialect/ONNX/ONNXOps/OpHelper.hpp
- src/Dialect/ONNX/ONNXOps/Tensor/Slice.cpp
- src/Dialect/ONNX/Rewrite.cpp
- src/Transform/ONNX/Decompose.cpp
changed all non-test code paths to create onnx constants using OnnxBuilder::constant()
added assert in OnnxBuilder::constant() and isDenseONNXConstant() to enforce the invariant that the value attribute is always a DenseElementsAttr or DisposableElementsAttr, since the way we use the value attribute of onnx constants throughout the code base generally assumes that it behaves like those, namely that getValues<T>() works for all data types T and that you can use ElementsAttrBuilder for constant propagation and constant folding
this PR could also help track down how a DenseResourceElementsAttr ends up in a constant operand to onnx.Reshape in issue #2344
> limit onnx constant value attribute to dense or disposable ElementsAttr

- utils/onnxExternalizeData.py
This makes it possible to turn large constants which are not raw into external data.
I tested this on arcfaceresnet100-8.onnx (size 249MB) from the model zoo.
Without --make_raw it produced no external data, because none its constants are raw.
With --make_raw almost all the 249MB went into a flat .ext file and the .onnx protobuf file was reduced 1345x to 189KB.
> add --make_raw flag to onnxExternalizeData.py

- src/Support/CMakeLists.txt
- src/Support/SmallFP.hpp
- src/Support/SmallFPConversion.c
- src/Support/SmallFPConversion.h
- test/unit/SmallFP/TestSmallFP.cpp
also added fast non-APFloat implementations for both f16 and bf16
verified exact match with APFloat with exhaustive test, invoked with `--exhaustive` flag
put the implementations in a C library to prepare for adding f16 and bf16 support into cruntime (not in this PR)
moving from a macro to a function made f32->f16 conversion 1.5% slower on my MacBook M1 which uses clang's bulitin `__fp16` conversion, and made f32->bf16 and bf16->f32 conversion 19x and 8x faster
before:
```
$ RelWithDebInfo/bin/TestSmallFP
Benchmark                          Time             CPU   Iterations
--------------------------------------------------------------------
BM_F32_TO_FP16<float_16>      138918 ns       138897 ns         4818
BM_F32_TO_FP16<bfloat_16>    2658403 ns      2658372 ns          258 …
```
> factor out f32<->f16 conversion to C library

- docs/DebuggingNumericalError.md
- utils/CheckONNXModel.py
Added a new python script built on top of runONNXModel.py to quickly compare the results of a single model compiled under 2 set of different options.
Added .md info as well as a small example in the header file, copied below
```python
#
#
#
#
```
> Check onnx models more easily

- src/Support/SmallFPConversion.h
The '#pragma once' is not supported on z/OS and causes a warning during compile.  This warning shows up when compiling the Runtime code to be used when linking a z/OS shared object model.
This PR changes the  '#pragma once' to a header guard in SmallFPConversion.h.
> Add header guard for SmallFPConversion

- docs/AddCustomAccelerators.md
- src/Accelerators/Accelerator.hpp
- src/Accelerators/NNPA/NNPAAccelerator.cpp
- src/Accelerators/NNPA/NNPAAccelerator.hpp
- src/Compiler/CMakeLists.txt
- src/Compiler/CompilerDialects.cpp
- src/Compiler/CompilerDialects.hpp
- src/Compiler/CompilerUtils.cpp
- src/Compiler/CompilerUtils.hpp
- src/Compiler/OnnxMlirCompiler.cpp
- src/Tools/onnx-mlir-opt/CMakeLists.txt
- src/Tools/onnx-mlir-opt/onnx-mlir-opt.cpp
- src/Tools/onnx-mlir-reduce/CMakeLists.txt
- src/Tools/onnx-mlir-reduce/onnx-mlir-reduce.cpp
- src/Version/Version.cpp
- src/Version/Version.hpp
- src/onnx-mlir.cpp
- test/modellib/ModelLib.cpp
- test/modellib/ModelLib.hpp
- test/modellib/ScanModel.cpp
- test/numerical/TestLoop.cpp
- test/unit/CustomFn/TestCustomFn.cpp
Replaced duplicated dialect regitration and loading with the `registerDialects(maccel)` and `loadDialects(context)` functions.
Removed accelerator support from onx-mlir-reduce because it didn't seem to be working since there is no call to `accel::initAccelerators(maccel)` and there are no command line options to specify `maccel`.
> reuse dialect registration/loading

- src/Compiler/CompilerOptions.cpp
- src/Compiler/CompilerOptions.hpp
- src/Compiler/CompilerPasses.cpp
- src/Compiler/CompilerPasses.hpp
- src/Compiler/CompilerUtils.cpp
- src/Pass/Passes.hpp
- src/Tools/onnx-mlir-opt/onnx-mlir-opt.cpp
- src/Transform/ONNX/ConstProp.cpp
- src/Transform/ONNX/ConstProp.td
- test/mlir/onnx/onnx_constprop_expansion_bound.mlir
Adds a command line option `--onnx-const-prop-expansion-bound`:
```
ONNX dialect constant propagation maximum expansion factor.
Constants are not propagated if their bytes size exceed
the aggregate operands' sizes by more than this factor.
Set to -1 to always propagate, which is the default.
```
This makes it possible to prevent generating very large constants at compile time, e.g. through broadcast, which are more efficient to generate during runtime.
The expansion bound is checked in tablegen DDR patterns in ConstProp.td by calling a function `satisfiesExpansionBound(result)` which reads the flag value from a global variable `ConstPropONNXToONNXPassConfiguration::expansionBound`, because we cannot pass the flag value as a pass parameter to the DDR pattern. Since the value is determined …
> const prop expansion bound

- src/Transform/ONNX/ConstProp.td
Since we have problem in importing string type input to model, I used the following test case to see whether the new implementation of EqualOp on string type is correct or not.
```
func.func @test_equal_string() -> tensor<*xi1> {
%c1 = onnx.Constant dense<["string1"]> : tensor<1x!onnx.String>
%c2 = onnx.Constant dense<["string2"]> : tensor<1x!onnx.String>
%0 = "onnx.Equal"(%c1, %c2) : (tensor<1x!onnx.String>, tensor<1x!onnx.String>) -> tensor<*xi1>
return %0 : tensor<*xi1>
}
```
This test case caused trouble in constant propagation for string type. 
This PR is a hack to turn off constant propagation for EqualOp on string type. 
@sorenlassen This PR is not  needed, if you can fix the problem in constant folding quickly. With this PR, I found the test case exposed another issue in lowering …
> Avoid constant folding for EqualOp on string type

- test/backend/inference_backend.py
- utils/documentOps.py
Can add `==MIN== <num>` or `==MAX== <num>` comments to specify min/max onset supported. 
Otherwise, the min/max is defined by a default min/max value in conjunction with the values of `version_dict` in `gen_onnx_mlir.pl` 
```
"test_abs_cpu": {STATIC_SHAPE:{}, DYNAMIC_SHAPE:{-1:{-1}}, CONSTANT_INPUT:{-1}},
```
The resulting table is as below:
== Table ===========================
Onnx-mlir currently supports ONNX operations targeting up to opset 19. Limitations are listed when applicable.
* Operations are defined by the [ONNX Standard](https://github.com/onnx/onnx/blob/main/docs/Operators.md).
* Opset indicates, for each operation, the minimum and the maximum ONNX opset that is supported by the current version of onnx-mlir. Limitation field indicates limitations in the current …
> Added logic for simple min/max when generating the md files that describe our support

- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- utils/RunONNXLib.cpp
- utils/build-run-onnx-lib.sh
To me, it is easier to debug to run a model with the c interface. I found some issues in supporting string type input. 
1. The EntryPoint signature can not be parsed by llvm::Jason::parser because of the missing quotation marks. I also simplified the type from !krnl.StringType to just "string"
2. In the driver, utils/RunONNXLib.cpp, string type inputs are not handled. I added a simple workaround, which need further work. I think that the OMTensor utilities should be modified for string type, and the driver should use omTensorCreateWithRandomData().
With this PR, the test_equal_string can be ran with a tensor containing the same string for every element.
> support string input for c interface

- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Conversion/ONNXToKrnl/Tensor/Reshape.cpp
- test/mlir/onnx/onnx_lowering_with_canonicalize.mlir
This patch is to use DimAnalysis when lowering ONNXReshape. In particular, DimAnalysis is used to detect "identity" reshape, so that we can remove reshape.
> Use DimAnalysis when lowering ONNXReshape to krnl

- src/CMakeLists.txt
- src/Compiler/CMakeLists.txt
- src/Compiler/CompilerDialects.cpp
- src/Compiler/CompilerPasses.cpp
- src/Conversion/KrnlToAffine/ConvertKrnlToAffine.cpp
- src/Conversion/KrnlToLLVM/CMakeLists.txt
- src/Conversion/KrnlToLLVM/ConvertKrnlToLLVM.cpp
- src/Conversion/KrnlToLLVM/ConvertKrnlToLLVM.hpp
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Conversion/ONNXToKrnl/Math/Gemm.cpp
- src/Conversion/ONNXToKrnl/Math/MatMul.cpp
- src/Conversion/ONNXToKrnl/Math/Reduction.cpp
- src/Conversion/ONNXToKrnl/Math/Softmax.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Conversion/ONNXToKrnl/Tensor/Concat.cpp
- src/Conversion/ONNXToKrnl/Tensor/Transpose.cpp
- src/Dialect/Krnl/DialectBuilder.cpp
- src/Dialect/Krnl/DialectBuilder.hpp
- src/Dialect/Krnl/Krnl.td
- src/Pass/Passes.hpp
- src/Tools/onnx-mlir-opt/CMakeLists.txt
- src/Tools/onnx-mlir-opt/RegisterPasses.cpp
- src/onnx-mlir.cpp
- test/mlir/onnx/onnx_lowering_with_parallel_canonicalize_O3.mlir
Continued PR of #2426
Enable the multi-threading in onnx-mlir by utilizing OpenMP.  Tested on x86 with performance gain. 
Introduced a new operator in krnl dialect: krnl.parallel which takes a loop as input to specify the loop will be parallelized. 
To parallelization is **enabled** with the argument `--parallel` in `onnx-mlir` and  `--convert-onnx-to-krnl=enable-parallel` in `onnx-mlir-opt`.
To parallel an operator while lowering, you can follow the attached example below: 
```diff
ValueRange loopDef = create.krnl.defineLoops(outputRank);
SmallVector<IndexExpr, 4> lbs(outputRank, LiteralIndexExpr(0));
SmallVector<IndexExpr, 4> ubs;
+ create.krnl.parallel(loopDef[0]) // parallelize the outermost loop
create.krnl.iterateIE(loopDef, loopDef, lbs, ubs,
[&](KrnlBuilder &createKrnl, ValueRange …
```
> add support of multi-threading in ONNX-MLIR by leveraging OpenMP

- src/Accelerators/NNPA/Transform/ZLow/ZLowRewrite.cpp
- test/mlir/accelerators/nnpa/driver/softmax-matmul-in-attention-layer.mlir
- test/mlir/accelerators/nnpa/transform/zlow-rewrite.mlir
This patch is to remove consecutive zlow.unstick and zlow.stick ops if they use the same layout.
For example,
```mlir
zlow.unstick(%x, %y) {layout = 3DS}
zlow.stick(%y, %z) {layout = 3DS}
zlow.relu(%z)
```
will be replaced by
```mlir
zlow.relu(%x)
```
where `zlow.unstick` and `zlow.stick` are removed if they don't have any other use.
> [NNPA] Remove consecutive zlow.unstick and zlow.stick ops if they use the same layout

- src/Conversion/KrnlToAffine/ConvertKrnlToAffine.cpp
- src/Conversion/ONNXToKrnl/Math/Reduction.cpp
- test/mlir/krnl/block.mlir
- test/mlir/onnx/onnx_lowering_with_canonicalize_O3.mlir
- utils/CheckONNXModel.py
- utils/RunONNXModel.py
There was an issue with "unrequested" blocked inner loops being generated (when the control flow was simplified to fully nested) while lowering krnl to affine dialect.
The fix is relatively simple. I detect when the inner loop of a blocked loop is unused (aka its loop def is not used by any krnl operation). When that is the case, we still use the affine support to block the loop. The code simply forces the inner loop (which is not requested) to become a trivial `for(I=0; I<1; I++)` loop.
I also added a seed to generate different test case for `RunONNXModel.py` as it is useful to detect if several versions of a code always fail in the same way because of structural issues, or simply because they use the same seed.
I also added a few lit tests that cover this new issue, both to make sure …
> Fix for reduction simdization in presence of constant dimensions

- src/Compiler/CompilerPasses.cpp
fixes #2443 
For the issue in #2443, after calling all onnx transformations, there is still the following code (extracted from the roberta model and put into a single test):
```mlir
func.func @test(%arg0 : tensor<12x5x5xf32>, %arg1: tensor<f32>) -> tensor<?x12x5x5xf32>{
%35 = onnx.Constant dense<8.000000e+00> : tensor<f32>
%0 = onnx.Constant dense<[1, 12, 5, 5]> : tensor<4xi64>
%641 = "onnx.Reshape"(%arg0, %0) {allowzero = 0 : si64} : (tensor<12x5x5xf32>, tensor<4xi64>) -> tensor<?x12x5x5xf32>
%1 = "onnx.Div"(%641, %35) {onnx_node_name = "Div_560"} : (tensor<?x12x5x5xf32>, tensor<f32>) -> tensor<?x12x5x5xf32>
return %1 : tensor<?x12x5x5xf32>
}
```
where Reshape's output is still dynamic, but it could be static. So when lowering ONNXReshape to `ReinterpretCastOp`, `ReinterpretCastOp` …
> Call HybridTransformPass one more time to update shape if possible

- src/Compiler/CompilerOptions.cpp
- src/Compiler/CompilerOptions.hpp
- src/Compiler/CompilerPasses.cpp
- src/Pass/Passes.hpp
- src/Transform/ONNX/ConstProp.cpp
- src/Transform/ONNX/ConstProp.td
- test/mlir/onnx/onnx_constprop.mlir
- test/mlir/onnx/onnx_constprop_no_shape_inference.mlir
Added a flag to disable select onnx const prop patterns. This upstreams logic that proved useful at Groq on a specific model where an onnx const prop pattern was counter-productive.
Removed ConstPropSplitV11Pattern because it should be unnecessary since we canonicalize SplitV11 to Split.
Migrated ConstPropScatterNDPattern to tablegen. Couldn't migrate ConstPropSplitPattern to tablegen because it has a variadic return value but refactored it to follow the style of the tablegen const prop patterns.
For the record, I modified the tablegen file with this script:
```
sed -i 's/^def \(\w\w*\) : Pat<$/def \1 : NamedPat<"\1",/' ConstProp.td
```
> flag -onnx-const-prop-disable-pattern

- test/mlir/accelerators/nnpa/conversion/zhigh-to-onnx/relu.mlir
Just added a missing lit test for relu in PR #2463
> [NNPA] Reconstruct onnx element-wise ops from zhigh ops - add a missing lit test for relu

- src/Compiler/CMakeLists.txt
- src/Compiler/CompilerOptions.cpp
- src/Compiler/CompilerUtils.cpp
- src/Compiler/OnnxMlirCompiler.cpp
- Do not remove LLVM "internal" options such as --debug
- Clean up some header includes and library link dependencies
> Do not remove LLVM "internal" options

- src/Compiler/CompilerUtils.cpp
- test/mlir/driver/shape_information.mlir
This patch is to make `--shapeInformation` work with .mlir input files. It was only working with .onnx input files.
> Support --shapeInformation for .mlir input files

- docs/BuildOnLinuxOSX.md
- docs/BuildOnWindows.md
- utils/clone-mlir.sh
The goals of the LLVM rotation were to
- Keep the LLVM dependency up to date
- Sync on a commit that matches other projects
The torch-mlir community has a weekly cadence.
Unfortunately LLVM didn't get updated for about a month. When it did get updated it was on one of the weeks that we don't uplift (this week). 
I've done this second bump for this week so we can have a matching LLVM commit between both `torch-mlir` and `onnx-mlir` for the first time in over a month.
Specifically matching this parallel commit in `torch-mlir` https://github.com/llvm/torch-mlir/pull/2454
> Bump LLVM/MHLO

- src/Builder/CMakeLists.txt
- src/Builder/FrontendDialectTransformer.cpp
- src/Builder/FrontendDialectTransformer.hpp
- src/Compiler/CompilerPasses.cpp
- src/Compiler/CompilerUtils.cpp
- src/Conversion/KrnlToAffine/CMakeLists.txt
- src/Conversion/KrnlToAffine/ConvertKrnlToAffine.cpp
- src/Conversion/ONNXToKrnl/CMakeLists.txt
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/Pass/Passes.hpp
- src/Transform/ONNX/CMakeLists.txt
- src/Transform/ONNX/ONNXOpTransformPass.cpp
to make it easy to use each of the dialects and passes as libraries that people can link into their own compiler binaries without using the onnx-mlir binary, and to avoid unnecessary cyclical dependencies, we should avoid making the dialects and passes depend on anything in src/Compiler (with #include or cmake LINK_LIBS)
> remove src/Compiler dependencies from src/{Builder,Transform,Conversion}

- test/mlir/onnx/onnx_constprop.mlir
To remind that Expand's shape can be shorter than the data input shape.
> Expand const prop lit test with short shape operand

- .azure-pipelines/Windows-CI.yml
see @jcwchen advice in issue #2481
> grew windows CI timeout

- src/Dialect/ONNX/ONNXOps/OpHelper.cpp
- test/mlir/onnx/onnx_canonicalization.mlir
new lit test test_rewrite_batchnormtestmode_1d_f16 crashed in createDenseElementsAttrFromFloatAttr because DenseElementsAttr::get(t, apfloat) wants apfloat to have the semantics of t's element type
createDenseElementsAttrFromFloatAttr was called on the result element type and `$epsilon` in the RewriteBatchNormInferenceModeConvPattern1 pattern
> fix f16 onnx.BatchNormalizationInferenceMode canonicalization

- src/Dialect/ONNX/ONNXOps.td.inc
- src/Dialect/ONNX/Rewrite.cpp
- src/Dialect/ONNX/Rewrite.td
- test/mlir/onnx/onnx_canonicalization.mlir
- test/mlir/onnx/onnx_hybrid_transform.mlir
- utils/gen_onnx_mlir.py
With this change it should be the case that no pattern introduces ops that are decomposed in DecomposeONNXToONNXPass and therefore they don't undo the work of that pass.
This will avoid unnecessary chains of patterns in the hybrid pass with decomposition (PR #2496). While chains of patterns should work, without them it is simpler to understand the interplay between sets of pattens.
> don't canonicalize to SqueezeV11, UnsqueezeV11

- src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/CMakeLists.txt
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/DevicePlacement.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHigh.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHigh.hpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHighCommon.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHighCommon.hpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.hpp
- src/Accelerators/NNPA/NNPAAccelerator.cpp
- src/Accelerators/NNPA/Pass/NNPAPasses.hpp
- test/mlir/accelerators/nnpa/conversion/device-placement/device_placement_pass.mlir
- test/mlir/accelerators/nnpa/conversion/device-placement/emit-onnxir.mlir
- test/mlir/accelerators/nnpa/conversion/device-placement/emit-zhighir.mlir
- test/mlir/accelerators/nnpa/conversion/device-placement/lit.local.cfg
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/add-exec-cpu-opt.mlir
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/add-exec-cpu.mlir
To set device for an ONNX operation (say,  the op in the output of --EmitONNXIR where all onnx-to-onnx transformations has been applied), we set the device attribute for the ONNX operation, e.g.
```mlir
%0 = "onnx.Add"(%arg0, %arg1) {device = "cpu", onnx_node_name = "test/add0"} : (tensor<10x10xf32>, tensor<10x10xf32>) -> tensor<*xf32>
```
will place `onnx.Add` on CPU.
```mlir
%0 = "onnx.Add"(%arg0, %arg1) {device = "nnpa", onnx_node_name = "test/add0"} : (tensor<10x10xf32>, tensor<10x10xf32>) -> tensor<*xf32>
```
will place `onnx.Add` on NNPA.
If there is no `device` attribute, the compiler will make decision.
`device` attribute would facilitates our next steps, in particular, using a cost model proposed in #2507, or using a configuration file by users to specify where to place an ONNX …
> [NNPA] Use device attribute to control device placement for ONNX operations

- docs/BuildOnLinuxOSX.md
- docs/BuildOnWindows.md
- src/Conversion/KrnlToLLVM/CMakeLists.txt
- src/Dialect/Mlir/DialectBuilder.cpp
- test/mlir/conversion/onnx_to_krnl/ObjectDetection/onnx_lowering_nonmaxsuppression_op.mlir
- utils/clone-mlir.sh
Bump LLVM to f66cd9e9556a53142a26a5c21a72e21f1579217c 
I haven't bumped MHLO in absence of a green commit. Should I try to bump it to a closer commit, or should we just disable MHLO as suggested in the thread?
> Bump LLVM commit to f66cd9e9556a53142a26a5c21a72e21f1579217c 

- src/Support/Diagnostic.cpp
I looked into the model zoo ssd_mobilenet_v1_10 segfault and found it was because of infinite recursion when trying to emit an error in ONNXConcatOp::verify()
I didn't 100% understand how the infinite recursion happened but the workaround in this PR fixed it and it now fails with
```
loc("Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/concat"): error: onnx.Concat: operand '%8071 = "onnx.Expand"(%14, %8070) : (tensor<f32>, tensor<1xi64>) -> tensor<?xf32>' has rank 1, rank should be 2
loc("Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/concat"): error: 'onnx.Concat' op verification failed
loc("Postprocessor/BatchMultiClassNonMaxSuppression/map/while/PadOrClipBoxList/cond/concat"): error: onnx.Concat: operand '%7691 = …
```
> avoid infinite verify() recursion in Diagnostic

- src/Compiler/CompilerOptions.cpp
- src/Compiler/CompilerOptions.hpp
- src/Compiler/CompilerPasses.cpp
- src/Pass/Passes.hpp
- src/Transform/ONNX/ConstProp.cpp
- test/backend/inference_backend.py
- test/mlir/accelerators/nnpa/conversion/device-placement/emit-onnxir.mlir
- test/mlir/accelerators/nnpa/conversion/device-placement/emit-zhighir.mlir
- test/mlir/accelerators/nnpa/conversion/rewrite-onnx-for-zhigh.mlir
- test/mlir/onnx/onnx_constprop.mlir
- test/mlir/onnx/onnx_constprop_expansion_bound.mlir
- test/mlir/onnx/onnx_constprop_no_shape_inference.mlir
- test/mlir/onnx/onnx_hybrid_transform.mlir
- test/mlir/onnx/onnx_simplify_shape_related_ops.mlir
I changed the flag from `enableConstantProp` to `disableConstantProp` so from now on the user would have to manually specify if they want to disable constant propagation. It is no longer tied to level 3 and the default behavior will be to always enable constant propagation unless a user feels otherwise. I was also able to renable the two backend tests that were failing.
> Remove Level Constraint for Constant Propagation 

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.hpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/RewriteONNXForZHigh.cpp
> [NNPA] Check element types in rewrite-onnx-for-zhigh pass

- MLIR.cmake
- docs/SupportedONNXOps-NNPA.md
- docs/SupportedONNXOps-cpu.md
- test/accelerators/NNPA/backend/CMakeLists.txt
- utils/documentOps.py
It seems like when the documentation was being updated, the command to generate the `SupportedONNXOps-NNPA.md` was accidentally switched with `onnx_mlir_supported_ops`. The `onnx_mlir_supported_ops` only updates the `SupportedONNXOps-CPU.md` file. So when issuing the command, I received the incorrect results for the `NNPA` documentation. Changing it back to what it originally was :)
> Update SupportedONNXOps-NNPA.md to include the correct command

- docs/mnist_example/requirements.txt
There was a vulnerability found in pillow:
```
Remediation
Upgrade Pillow to version 10.0.1 or later. For example:
Pillow>=10.0.1
Always verify the validity and compatibility of suggestions with your codebase.
```
> Update Pillow dependency

- test/accelerators/NNPA/backend/CMakeLists.txt
When issuing the `check-onnx-backend-nnpa` or `check-onnx-numerical-nnpa` I get the following error:
```
===================================================== ERRORS ======================================================
_________________________________________ ERROR collecting Debug/test.py __________________________________________
ImportError while importing test module '/workdir/onnx-mlir/build/test/accelerators/NNPA/backend/Debug/test.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib/python3.10/importlib/__init__.py:126: in import_module
return _bootstrap._gcd_import(name[level:], package, level)
Debug/test.py:35: in <module>
from inference_backend import (
Debug/inference_backend.py:29: in <module>
from onnxmlir_node_tests import …
```
> Add missing python file to CMakeLists.txt

- src/Compiler/CompilerPasses.cpp
- src/Pass/Passes.hpp
- src/Transform/ONNX/ConvOpt.cpp
- src/Transform/ONNX/ConvOpt.hpp
- src/Transform/ONNX/ONNXHybridTransformPass.cpp
- test/mlir/onnx/onnx_hybrid_transform.mlir
replaces ONNXOpTransformPass and the repeatOnnxTransform loop in addONNXToMLIRPasses() with hybrid transform, unless disabled with `--onnx-hybrid-pass=false`
set maxNumRewrites in onnx-hybrid-transform to 300 and tested that the model https://huggingface.co/xlnet-large-cased succeeds without warning with this value
prints warning to stderr if onnx-hybrid-transform doesn't converge with the given maxNumRewrites
I tested this PR on the models in the model zoo and the same models passed and failed as with main
possible future work:
- replace const-prop, shape-inference, canonicalizer passes in SimplifyShapeRelatedOpsPass with hybrid transform
- replace some shape-inference/const-prop/canonicalizer passes in addONNXToZHighPasses() with hybrid transform
> replace ONNXOpTransformPass with hybrid transform

- src/Dialect/ONNX/ONNXDimAnalysis.cpp
- src/Dialect/ONNX/ONNXOps/OpHelper.cpp
- src/Dialect/ONNX/ONNXOps/OpHelper.hpp
- test/mlir/onnx/onnx_shape_inference.mlir
This patch is a complement to #2450 to improve ShapeInference when a shape input is defined by Concat of dimensions.
Before this patch, it was required that the inputs of Concat must be defined by Constant, Dim or Cast. But now, the inputs can be defined by any operation as long as they contain only one i64 element.
For example, with this patch, we can infer shape for the following Expand:
```
func.func @test_expand_with_concat(%arg0: tensor<1xi64>, %arg1: tensor<1xi64>, %arg2: tensor<f32>) -> tensor<*xf32> { 
%0 = onnx.Constant dense<1> : tensor<1xi64>                                                      
%1 = "onnx.Concat"(%arg0, %0, %arg1) {axis = 0 : si64} : (tensor<1xi64>, tensor<1xi64>, tensor<1xi64>) -> tensor<3xi64>
%2 = "onnx.Expand"(%arg2, %1) : (tensor<f32>, tensor<3xi64>) -> …
```
> Relax the condition for checking a shape defined by Concat

- src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
Since `ZHighConstPropagation` currently works with `DenseElementAttr` only, call `ScrubDisposablePass` to replace any `DisposableElementsAttr` with `DenseElementsAttr` before calling `ZHighConstPropagation`.
> [NNPA] Call ScrubDisposablePass before ZHighConstPropagation

- src/Transform/ONNX/SimplifyShapeRelatedOps.cpp
In Llama-2-Onnx-7-32. there is SliceOp generates empty tensor, namely tensor<0xi64>. Such SliceOp cannot be replaced with DimOp, unless we introduce empty dim.
```
%801 = "onnx.Shape"(%713) {onnx_node_name = "/transformer/block_list.0/attention/Shape_47", start = 0 : si64} : (tensor<*xf32>) -> tensor<?xi64>
%802 = onnx.Constant dense<0> : tensor<1xi64>
%803 = onnx.Constant dense<4> : tensor<1xi64>
%804 = onnx.Constant dense<9223372036854775807> : tensor<1xi64>
%805 = "onnx.NoValue"() {value} : () -> none
%806 = "onnx.Slice"(%801, %803, %804, %802, %805) {onnx_node_name = "/transformer/block_list.0/attention/Slice_22"} : (tensor<?xi64>, tensor<1xi64>, tensor<1xi64>, tensor<1xi64>, none) -> tensor<?xi64>
%807 = "onnx.Concat"(%763, %806) {axis = 0 : si64, onnx_node_name = …
```
> Handle empty tensor from SliceOp in SimplifyShapeRelatedOps

- test/accelerators/NNPA/backend/CMakeLists.txt
- test/accelerators/NNPA/numerical/CMakeLists.txt
When testing on a z16, several backend tests were failing for NNPA because we included the `--mcpu` flag recently to check hw and so this was also missing from the backend tests.
> Add --mcpu flag to ensure NNPA backend tests are executing

- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- test/mlir/conversion/onnx_to_krnl/onnx_lowering_fuse.mlir
Op fuse use ONNXBroadcastOpShapeHelper to generate access expression. However, memref.dim, which is not needed, is also generated. 
Details explanation can be found in the code.
More test cases are added.
> fix op fuse error

- src/Transform/ONNX/Recompose.cpp
- test/mlir/onnx/onnx_recompose.mlir
T5 model apparently use a `x * (1 / y)` pattern instead of `x / y`. The new recompose also now check for reciprocal and divide 1 by patterns.
Lit tests added.
> Detect LayerNorm in presence of reciprocal and div of 1

- src/Tools/onnx-mlir-opt/onnx-mlir-opt.cpp
`--maccel` needs `--mcpu` to know it is z16 or not, so this patch parses and sets `--mcpu` in the `onnx-mlir-opt` command. Otherwise, we will see a warning `Warning: No NNPA code is generated because --mcpu is not set or < z16.` when running `onnx-mlir-opt` for NNPA.
> Parse and set --mcpu in onnx-mlir-opt command

- src/Dialect/ONNX/ONNXDimAnalysis.cpp
- src/Dialect/ONNX/ONNXDimAnalysis.hpp
- test/mlir/onnx/onnx_dim_analysis.mlir
This patch improves the dynamic dimension analysis by getting the relationship between input and output dimensions via `onnx.dim_params` attribute.
> Use dim_params in dynamic dimension analysis

- CMakeLists.txt
- README.md
- docker/Dockerfile.llvm-project
- docs/BuildOnLinuxOSX.md
- docs/BuildOnWindows.md
- docs/Prerequisite.md
- requirements.txt
- utils/install-protobuf.cmd
- utils/install-protobuf.sh
Upgrading Protobuf to match the onnx community. In order to upgrade Protobuf we have to include the abseil dependencies as well or else we will receive failures. I am hoping by upgrading Protobuf it will help us with ONNX 1.15.0 upgrade.
> Update Protobuf to v21.12

- docs/BuildOnLinuxOSX.md
- docs/BuildOnWindows.md
- test/mlir/conversion/onnx_to_krnl/Tensor/Pad_with_canonicalize.mlir
- test/mlir/conversion/onnx_to_stablehlo/Tensor/Reshape.mlir
- utils/clone-mlir.sh
This PR updates onnx-mlir to LLVM commit `28b27c1b10ae8d1f5b4fb9df691e8cf0da9be3f6`.
This is the same LLVM commit level that torch-mlir is currently at.
> Update to LLVM 28b27c1b10ae8d1f5b4fb9df691e8cf0da9be3f6

- src/Compiler/CMakeLists.txt
- src/Runtime/CMakeLists.txt
- src/Runtime/omp/CMakeLists.txt
If LLVM is built with OpenMP support enabled, a corresponding `libOMomp.a` will be built in `$<CONFIG>/lib`. This library can then be embedded into the generated model.so to provide OpenMP support for the model runtime.
> OpenMP support in model runtime

- src/Accelerators/NNPA/Dialect/ZHigh/ZHighOps/OpHelper.cpp
- src/Accelerators/NNPA/Dialect/ZHigh/ZHighOps/OpHelper.hpp
- src/Accelerators/NNPA/Dialect/ZHigh/ZHighOps/OpHelper.td
- src/Accelerators/NNPA/Dialect/ZHigh/ZHighOps/Unstick/Unstick.cpp
- src/Accelerators/NNPA/Dialect/ZHigh/ZHighOps/Unstick/ZHighUnstick.td
- test/mlir/accelerators/nnpa/transform/zhigh-combine.mlir
This patch is to add a rewriting pattern that removes `zhigh.unstick` when getting dimensions.
For example, the following code
```mIir
%0 = "zhigh.Unstick"(%arg0) : (tensor<?x?x?xf16, #zhigh.layout<{dataLayout = "3D"}>>) -> tensor<?x?x?xf32>
%1 = "onnx.Dim"(%0) {axis = 1 : si64}: (tensor<?x?x?xf32>) -> tensor<1xi64>
```
will be replace by 
```mlir
"onnx.Dim"(%arg0) {axis = 1 : si64} : (tensor<?x?x?xf16, #zhigh.layout<{dataLayout = "3D"}>>) 
```
where the dimension is obtained directly from a zTensor without unstickifying the zTensor.
> [NNPA] A rewrite pattern to get dim directly from a zTensor without unstickification.

- src/Dialect/ONNX/ONNXOps/OpHelper.cpp
- src/Dialect/ONNX/ONNXOps/OpHelper.hpp
- src/Dialect/ONNX/Rewrite.cpp
- test/mlir/onnx/onnx_canonicalization.mlir
In the self-attention layer, the output of MatMul is scaled by a constant factor via a division/multiplication operation. This patch rewrites the division/multiplication operation so that the constant input of MatMul will be scaled instead of its output. Thus, the scaling of the constant inputs can be folded at compile time. 
For example, this patch rewrites the following pattern:
```
shape_transform(X1 * A1 + B1) * shape_transform(X2 * A2 + B2) / k
```
into
```
shape_transform(X1 * A1 + B1) * shape_transform(X2 * A2/k + B2/k)
```
if A2, B2 and k are constants,
or into
```
shape_transform(X1 * A1/k + B1/k) * shape_transform(X2 * A2 + B2)
```
if A1, B1 and k are constants,
where
- `*` is matrix multiplication; `+` and `/` are element-wise addition and division
- A1, A2, B1, B2, and k are …
> A rewrite pattern to optimize constant scaling in self-attention layer

- src/Conversion/KrnlToAffine/ConvertKrnlToAffine.cpp
- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Dialect/Krnl/DialectBuilder.cpp
- src/Dialect/Krnl/DialectBuilder.hpp
- src/Dialect/Krnl/Krnl.td
- test/mlir/conversion/onnx_to_krnl/Math/Elementwise_with_parallel_canonicalize_O3.mlir
- test/mlir/conversion/onnx_to_krnl/Math/Gemm_with_parallel_canonicalize_O3.mlir
- test/mlir/conversion/onnx_to_krnl/Math/MatMul_with_parallel_canonicalize_O3.mlir
- test/mlir/conversion/onnx_to_krnl/Math/Reduction_with_parallel_canonicalize_O3.mlir
- test/mlir/conversion/onnx_to_krnl/Math/Softmax_with_parallel_canonicalize_O3.mlir
- test/mlir/conversion/onnx_to_krnl/Tensor/Concat_with_parallel_canonicalize_O3.mlir
- test/mlir/conversion/onnx_to_krnl/Tensor/Transpose_with_parallel_canonicalize_O3.mlir
Previously, only one loop ref is allowed by krnl.parallel.
This PR allows a variadic input of loop refs for krnl.prallel. For example, the krnl for an element wise op on three dimension tensor could be (if our parallelization had been modified):
```
%0:3 = krnl.define_loops 3
krnl.parallel %0#0, %0#1, %0#2 : !krnl.loop, !krnl.loop, !krnl.loop
krnl.iterate(%0#0, %0#1, %0#2) with (%0#0 -> %arg2 = 0 to 3, %0#1 -> %arg3 = 0 to 4, %0#2 -> %arg4 = 0 to 5){
%1:3 = krnl.get_induction_var_value(%0#0, %0#1, %0#2) : (!krnl.loop, !krnl.loop, !krnl.loop) -> (index, index, index)
%2 = krnl.load %arg0[%1#0, %1#1, %1#2] : memref<3x4x5xf32>
%3 = krnl.load %arg1[%1#0, %1#1, %1#2] : memref<3x4x5xf32>
%4 = arith.addf %2, %3 : f32
krnl.store %4, %alloc[%1#0, %1#1, %1#2] : memref<3x4x5xf32>
} 
```
In the Krnl …
> Enable krnl.parallel to have multiple loops

- src/Compiler/CompilerDialects.cpp
- src/Compiler/CompilerOptions.cpp
- src/Compiler/CompilerOptions.hpp
- src/Compiler/CompilerPasses.cpp
- utils/RunONNXModel.py
The new LLVM bufferization mechanism causes the inference time very slow. While it may take time for the new bufferization to produce good performance, this patch adds a compile option `--use-old-bufferization` to enable the old LLVM bufferization mechanism.
> Use old LLVM bufferization to avoid performance regression

- .buildbot/jenkins-verify-user-image.py
Use docs/mnist_example/mnist.onnx for verifying user docker image so we don't depend on modelzoo, which has just been completely restructured.
This is a blocking issue for Jenkins CI so we should merge asap.
> Modelzoo restructure breaks verifying user docker image

- docs/doc_example/main.c
- src/Compiler/CompilerOptions.cpp
- src/Compiler/CompilerOptions.hpp
- src/Compiler/CompilerUtils.cpp
The default ONNX_MLIR_FLAGS env variable was not scanned in `onnx-mlir`. This opinion is useful and documented. This PR restore its proper usage.
> fix broken ONNX_MLIR_FLAGS

- test/accelerators/NNPA/backend/CMakeLists.txt
- test/backend/variables.py
NNPA tests segfault because different set of tests such as `check-onnx-backend-nnpa`, `check-onnx-backend-dynamic-nnpa`, `check-onnx-backend-constant-nnpa`, etc. are running in parallel and generating model.so in the same directory.
> Fix NNPA tests segfault

- CMakeLists.txt
Remove a Window warning suppression because the latest LLVM has included a fix for that warning.
> Remove a Window warning suppression

- test/mlir/conversion/onnx_to_krnl/Sequence/Sequence_with_dealloc.mlir
Remove the check of the order of operands in affine.apply, which is discussed in https://github.com/onnx/onnx-mlir/issues/2667.
> [onnx-to-krnl] remove the check of operands for affine.apply

- docs/UpdatingLLVMCommit.md
I pretty much kept the same outline of what was written previously and simply changed `MLIR-HLO` to `StableHLO`. I also updated the links so that we can reference the appropriate location of things. As a community we agreed on updating LLVM and StableHLO simultaneously which would be much easier than separating the two processes (It keeps everything in sync on a biweekly cadence). Please provide comments and feedback if you see any way we can improve what I have. Thanks so much for reviewing!
> Update document for LLVM and StableHLO process

- src/Accelerators/NNPA/Conversion/ZHighToZLow/ZHighToZLow.cpp
- src/CMakeLists.txt
- src/Compiler/CMakeLists.txt
- src/Compiler/CompilerOptions.cpp
- src/Compiler/CompilerOptions.hpp
- src/Compiler/CompilerPasses.cpp
- src/Compiler/CompilerUtils.cpp
- src/Compiler/CompilerUtils.hpp
- src/Compiler/OptionUtils.cpp
- src/Compiler/OptionUtils.hpp
- src/Conversion/ONNXToKrnl/Additional/LayoutTransform.cpp
- src/Conversion/ONNXToKrnl/CMakeLists.txt
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Conversion/ONNXToKrnl/Math/Gemm.cpp
- src/Conversion/ONNXToKrnl/Math/MatMul.cpp
- src/Conversion/ONNXToKrnl/Math/Reduction.cpp
- src/Conversion/ONNXToKrnl/Math/Softmax.cpp
- src/Conversion/ONNXToKrnl/NN/Conv.cpp
- src/Conversion/ONNXToKrnl/NN/Normalization.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Conversion/ONNXToKrnl/Tensor/Concat.cpp
- src/Conversion/ONNXToKrnl/Tensor/Transpose.cpp
- src/Dialect/ONNX/ONNXOps/NN/Normalization.cpp
- src/Pass/Passes.hpp
- src/Transform/ONNX/CMakeLists.txt
- src/Transform/ONNX/InstrumentPass.cpp
- utils/analyze-simd.py
- utils/make-report.py
Up to know, we either parallelized all operations (with `-parallel`) or none. This PR add the ability to define a `-parallelize-ops=regexp` to decide which operation should be parallelized. It must be used in conjunction with the `-parallel` flag.
As we already had some support for regex processing, I factorized the regex processing from InstrumentOps to compiler util so that it may be reused where ever needed.
> Added an onnx-mlir option to select which operation to parallelize

- src/Accelerators/NNPA/Runtime/zDNNExtension/zDNNExtension.h
- src/Runtime/jni/jniwrapper.c
This PR adds a header guard for zDNNExtension.h instead of using `#pragma once`.  The `#pragma once` is not supported on z/OS and causes a warning during compile. This warning shows up when compiling the Runtime code to be used when linking a z/OS shared object model.
This PR also corrects a warning message issued when compiling jniwrapper.c on z/OS.
> Fix compile messages for z/OS

- src/Accelerators/NNPA/Runtime/zDNNExtension/Elementwise.c
I forgot to add zdnn div into the list of supported ops for splitting in #2690. Added it here.
> [NNPA] Enable splitting zdnn div

- src/Dialect/ONNX/Rewrite.cpp
- src/Dialect/ONNX/Rewrite.td
- src/Transform/ONNX/Decompose.cpp
- src/Transform/ONNX/Decompose.td
- test/mlir/onnx/onnx_canonicalization.mlir
- test/mlir/onnx/onnx_decompose.mlir
Move constant normalization rules from Canonicalization pass into Decompose pass, so that we always have ConstantOp with ElementAttrs in the following passes.
> Move constant normalization rules into Decompose pass

- src/Compiler/CompilerUtils.cpp
There is a bug in saving LLVMIR to `.ll`. It was always saving to a .ll file (which is slow) then deleting the file if not requested from users.
This patch adds a `if` statement so that the saving to .ll is done only when users request.
> Do not save LLVMIR to .ll file if not requested

- utils/analyze-simd.py
Useful to detect SIMD instructions for stick and unstick operations.
Example from compiler generated code:
```
analyze-simd.py -t z -a -p add.so
[...]
8c02:	41 10 10 08       	la	%r1,8(%r1)
8c06:	e7 00 30 00 40 06 	vl	%v0,0(%r3),4                         <<<<==== vload
8c0c:	e6 10 00 00 20 56 	vclfnh	%v1,%v0,2,0                      <<<<==== vconv
8c12:	e6 00 00 00 20 5e 	vclfnl	%v0,%v0,2,0                      <<<<==== vconv
8c18:	e7 10 20 00 40 0e 	vst	%v1,0(%r2),4                        <<<<==== vstore
8c1e:	e7 00 20 10 40 0e 	vst	%v0,16(%r2),4                       <<<<==== vstore
8c24:	41 20 20 20       	la	%r2,32(%r2)
8c28:	41 30 30 10       	la	%r3,16(%r3)
8c2c:	c2 1e 00 00 3f f8 	clgfi	%r1,16376
8c32:	a7 44 ff e8       	jl	8c02 <main_graph_add+0xf12>
```
> [Non-functional change] Added analyze-simd functionality for stick/unstick simd instructions

- src/Accelerators/NNPA/Conversion/ZLowToLLVM/ZLowToLLVM.cpp
In general LLVM side effect is meant to act as a barrier for scheduling; it does not feel right to have the SIMD conversion ops to have this property. This PR removes the side effects.
It did not impact the quality of the generated code for the F32ToDLF16 (and reverse) operations because LLVM did not unroll the loop. Subsequent PRs will aim to improve the generated code.
Created a PR with only this change so that it may be pulled out easily if it turned out to generate issues down the line.
> No side effect for vec converion FP32 <-> DLF16

- src/Accelerators/NNPA/Runtime/zDNNExtension/zDNNExtension.h
The link of the runtime fails on z/OS with recent changes in zDNNExtension.
```
IEW2456E 9207 SYMBOL __builtin_unreachable UNRESOLVED. MEMBER COULD NOT BE
INCLUDED FROM THE DESIGNATED CALL LIBRARY.
FSUM3065 The LINKEDIT step ended with return code 8.
```
Update the` omUnreachable()` to account for `__builtin_unreachable` and `__assume(false)` not being available on z/OS.
> Fix link error on z/OS

- src/CMakeLists.txt
- src/Compiler/CMakeLists.txt
- src/Compiler/CompilerDialects.cpp
- src/onnx-mlir.cpp
This PR moves `registerOpenMPDialectTranslation()` into `registerDialects()`. This should be better position. The `registry.insert<mlir::omp::OpenMPDialect>()` removed in this PR is done in `mlir::registerOpenMPDialectTranslation()`.
Without this PR, I got following errors when specifying `-parallel` option in numerical tests as shown below.
Example:
```
$ export OMP_NUM_THREADS=4
$ TestMatMul2D  -O3 -mcpu=z16 --mtriple=s390x-ibm-loz -parallel
error: cannot be converted to LLVM IR: missing `LLVMTranslationDialectInterface` registration for dialect for op: omp.parallel
```
> Fix position of registry for OpenMP dialect 

- src/Accelerators/NNPA/Runtime/zDNNExtension/MatMul.c
This PR fixes a link error on z/OS.  The `sched_getcpu` function does not exist on z/OS.
```
IEW2456E 9207 SYMBOL sched_getcpu UNRESOLVED.  MEMBER COULD NOT BE INCLUDED    
FROM THE DESIGNATED CALL LIBRARY. 
```
> Fix sched_getcpu link error on z/OS

- src/Dialect/ONNX/ONNXDimAnalysis.cpp
- src/Dialect/ONNX/Rewrite.cpp
- src/Dialect/ONNX/Rewrite.td
- test/mlir/onnx/onnx_canonicalization.mlir
This patch moves CastOp up before Concat/Slice, which facilitates DimAnalysis, since DimAnalysis is the best working with Concat as a shape producer.
Resolves #2633.
> Propagate CastOp throught Concat and Slice to facilitate DimAnalysis

- src/Accelerators/NNPA/Runtime/zDNNExtension/zDNNExtension.c
This PR fixes a warning message when compiling the runtime on z/OS.
```
WARNING CCN3068 /tmp/zdlc-zos-src-tmp-27956/src/Accelerators/NNPA/Runtime/zDNNExtension/zDNNExtension.c:495   Operation between types "struct zdnn_ztensor*" and "const struct zdnn_ztensor*" is not allowed.
```
> Remove warning message when compiling runtime for z/OS

- src/Conversion/ONNXToStablehlo/Math/Reduction.cpp
- test/mlir/conversion/onnx_to_stablehlo/Math/Reduction.mlir
This pull request updates conversion for Reduction ops to stablehlo.
> [stablehlo] Reduction upgrade

- src/Conversion/ONNXToStablehlo/NN/ConvTranspose.cpp
- src/Dialect/ONNX/ONNXOps/NN/Conv.cpp
- src/Dialect/ONNX/ONNXOps/ShapeHelper.hpp
- test/mlir/conversion/onnx_to_stablehlo/NN/ConvTranspose.mlir
This pull request fixes the original conversion of ConvTranspose to stablehlo. Speicifically, we should use outputPadding Attribute to calculate the padding for stablehlo.convolution, instead of doing conv then pad.
> [stablehlo] fix ConvTranspose

- test/backend/inference_backend.py
This PR uses "{0:{-1}}" for the dynamic shape for the backend dynamic test cases test_constant_pad_cpu, test_edge_pad_cpu, and test_reflect_pad_cpu.
> Update test_constant_pad_cpu, test_edge_pad_cpu, and test_reflect_pad_cpu

- docs/SupportedONNXOps-cpu.md
This PR corrects the version for ConstantOfShape in the SupportedONNXOps-cpu.md file.
> Correct SupportedONNXOps-cpu version for ConstantOfShape

- test/backend/inference_backend.py
When issuing the target `check-onnx-backend-dynamic` we receive the following error for all `onnx.Castlike` tests:
`error: failed to materialize conversion for result #0 of operation 'onnx.CastLike' that remained live after conversion`
I simply update the dynamic shape values to bypass this error. Please let me know your thoughts. Thank you!
> Update the dynamic shape values for onnx.CastLike

- src/Dialect/ONNX/ONNXOps.td.inc
- src/Dialect/ONNX/ONNXOps/Canonicalize.cpp
- src/Dialect/ONNX/ONNXOps/Canonicalize.td
- test/mlir/onnx/onnx_canonicalization.mlir
- utils/gen_onnx_mlir.py
Canonicalize `TileOp` when it is identity, i.e. when the input/result shape is same and all `repeat` values are constantly known to be 1.
> [mlir][ONNX] Implement `TileOp` canonicalizer

- test/accelerators/NNPA/backend/CMakeLists.txt
- test/backend/common.py
This patch fix issue #2749 with reducing tests for check-onnx-backend-dynamic-nnpa, since NNPA cannot be used for some cases with dynamic inputs.
> Fix Issue #2749 with reducing tests for check-onnx-backend-dynamic-nnpa .

- src/Conversion/ONNXToKrnl/ML/CategoryMapper.cpp
- src/Dialect/Mlir/DialectBuilder.cpp
- src/Dialect/Mlir/DialectBuilder.hpp
This PR fixes an error of result type mismatch in the lowering of CategoryMapper when the input is dynamic.
Resolves #2770
> Fix an error in CategoryMapper

- docs/SupportedONNXOps-cpu.md
https://github.com/onnx/onnx-mlir/pull/2721 updated the ops to include opset 20 support but set the documented min to opset to 20. This reverts the documented min opset to what it was before.
> Fix min opset doc for IsInf and IsNaN

- docs/SupportedONNXOps-cpu.md
https://github.com/onnx/onnx-mlir/pull/2721 updated the ops to include opset 20 support but set the documented min to opset to 20. This reverts the documented min opset to what it was before.
> Cherry-pick Fix min opset doc for IsInf and IsNaN (#2777)

- src/Dialect/Krnl/DialectBuilder.cpp
- src/Dialect/Krnl/DialectBuilder.hpp
Added a function in Krnl Dialect Builder to create a region using the standard format
``` c++
create.krnl.region([&](KrnlBuilder &createKrnl) {
// code inside the body of the region
});
```
Did not test, as there is no easy place to use it in the current code base.
> Added krnl region to krnl dialect builder

- src/Accelerators/NNPA/Compiler/CMakeLists.txt
- src/Accelerators/NNPA/Compiler/NNPACompilerOptions.cpp
- src/Accelerators/NNPA/Compiler/NNPACompilerOptions.hpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/CMakeLists.txt
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHigh.td
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHighCommon.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHighCommon.hpp
- src/Accelerators/NNPA/Pass/NNPAPasses.hpp
- src/Conversion/KrnlToAffine/KrnlGetLinearOffsetIndex.cpp
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/div-bcast.mlir
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/div.mlir
- test/mlir/accelerators/nnpa/driver/matmul-div-in-attention-layer.mlir
Add a compile flag, `--nnpa-enable-scalar-bcast-binary`, to turn on/off the lowering of scalar broadcasting binary ops to NNPA, which is flexible for debugging. Default value is off.
> Add a flag to turn on/off the lowering of scalar broadcasting binary ops to NNPA

- src/Conversion/ONNXToStablehlo/Tensor/ScatterND.cpp
- test/mlir/conversion/onnx_to_stablehlo/Tensor/ScatterND.mlir
The previous implementation asserted that all dims of the `indices` operand were static. First of all, assertion isn't appropriate here as the definition of the op allows dynamic.  This is a condition for the pattern match and thus should fail the match with `notifyMatchFailure`. Second, the implementation only relies on the last dim being static, so we can relax the match condition and only fail if last dim is dynamic.
> Relax dynamic restriction on `ScatterND` stablehlo conversion

- src/Accelerators/NNPA/Compiler/CMakeLists.txt
- src/Accelerators/NNPA/Compiler/NNPACompilerOptions.cpp
- src/Accelerators/NNPA/Compiler/NNPACompilerOptions.hpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/CMakeLists.txt
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHigh.td
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHighCommon.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHighCommon.hpp
- src/Accelerators/NNPA/Pass/NNPAPasses.hpp
- src/Conversion/KrnlToAffine/KrnlGetLinearOffsetIndex.cpp
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/div-bcast.mlir
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/div.mlir
- test/mlir/accelerators/nnpa/driver/matmul-div-in-attention-layer.mlir
* Add a flag to turn on/off scalar broadcasting binary op in NNPA
---------
Co-authored-by: Alexandre Eichenberger <alexe@us.ibm.com>
(cherry picked from commit 08d4fed88105cd8bba1d4ce5da1cd0ccbbf1af0d)
> Cherry-pick Add a flag to turn on/off the lowering of scalar broadcasting binary ops to NNPA

- src/Compiler/CompilerOptions.cpp
- src/Compiler/CompilerOptions.hpp
- src/Compiler/HeapReporter.cpp
- src/Compiler/HeapReporter.hpp
This PR uses `llvm::cl::list` to handle the parsing of a list of passes past as command line options. 
This is consistent with the `onnx-const-prop-disable-pattern` and `functions-to-decompose` implementations for list command line parsing.
> Cleanup HeapReporter command line options

- src/Accelerators/NNPA/Compiler/NNPACompilerOptions.cpp
- src/Accelerators/NNPA/Dialect/ZLow/ZLow.td
- src/Accelerators/NNPA/Dialect/ZLow/ZLowOps.cpp
- src/Conversion/KrnlToLLVM/KrnlGlobal.cpp
- src/Dialect/Krnl/Krnl.td
- src/Dialect/Krnl/KrnlOps.cpp
The new bufferization mechanism in recent LLVM was slower than the old one, and we proposed `--use-old-bufferization=true` to use the old one.
Today, I tested the new mechanism again by `--use-old-bufferization=false`, and it failed to compile a model. To fix it, we need to add  `DeclareOpInterfaceMethods<MemoryEffectsOpInterface>]>` to all operations that work with MemRef.
This PR is to add `DeclareOpInterfaceMethods<MemoryEffectsOpInterface>]>` to krnl and zlow ops.
> Update op definitions to make them work with the new bufferization

- src/Accelerators/NNPA/Transform/ZLow/ZLowRewrite.cpp
It seems we need to check the operations are in the same block before using `isBeforeInBlock()`.
Example in MLIR: https://github.com/llvm/llvm-project/blob/main/mlir/lib/Conversion/PDLToPDLInterp/PDLToPDLInterp.cpp#L940-L941
Without this, we get following error.
```
mlir::operation::isBeforeInBlock(mlir::Operation*): Assertion `other && other->block == block && "Expected other operation to have the same parent block."' failed.
```
> [NNPA]Update condition to apply unstickStickRemoval optimization

- src/Accelerators/NNPA/Runtime/zDNNExtension/Elementwise.c
- src/Accelerators/NNPA/Runtime/zDNNExtension/MatMul.c
- src/Accelerators/NNPA/Runtime/zDNNExtension/Softmax.c
- src/Accelerators/NNPA/Runtime/zDNNExtension/zDNNExtension.h
* On z/OS `CLOCKS_PER_SEC` is in time.h and `timeval` is in sys/time.sh so we need both imported.
> On z/OS import time.h in addition to sys/time.h

- src/Accelerators/NNPA/Runtime/zDNNExtension/Elementwise.c
- src/Accelerators/NNPA/Runtime/zDNNExtension/MatMul.c
- src/Accelerators/NNPA/Runtime/zDNNExtension/Softmax.c
- src/Accelerators/NNPA/Runtime/zDNNExtension/zDNNExtension.h
* On z/OS import time.h in addition to sys/time.h
* On z/OS `CLOCKS_PER_SEC` is in time.h and `timeval` is in sys/time.sh so we need both imported.
---------
> [Cherry-pick] On z/OS import time.h in addition to sys/time.h (#2788)

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/CMakeLists.txt
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/DevicePlacement.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHigh.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ZHighToONNX.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ZHighToONNX.td
- test/mlir/accelerators/nnpa/conversion/instrument/add-onnx-zhigh-level.mlir
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/conv.mlir
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/matmul.mlir
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/softmax.mlir
- test/mlir/accelerators/nnpa/conversion/zhigh-to-onnx/mul.mlir
The onnx-to-zhigh pass has two phases: 1) converting multiple onnx ops into a single zhigh op, and 2) converting a single onnx op to a single zhigh op, where the second phase uses DimAnalysis (Patterns in the 1st phase at this moment does not use DimAnalysis)
The problem is DimAnalysis is currently called before the 1st phase, which is not good because the 1st  phase may change the IR so the information from DimAnalysis is obsoleted to the 2nd phase. Correct position for DimAnalysis would be just before the 2nd phase.
Other than that, this PR changes slightly the rules in zhigh-to-onnx pass so that for binary ops, only one input (instead of two) that is from stick would be enough to trigger the rule to convert a zhigh op back to an onnx op.
Resolves #2789
> Fixing the location of DimAnalysis in onnx-to-zhigh pass and some rules in zhigh-to-onnx pass

- src/Conversion/KrnlToAffine/ConvertKrnlToAffine.cpp
- src/Conversion/KrnlToAffine/KrnlTerminator.cpp
- src/Conversion/ONNXToKrnl/Math/MatMul.cpp
- src/Conversion/ONNXToKrnl/Math/Softmax.cpp
- src/Conversion/ONNXToKrnl/NN/Conv.cpp
- src/Dialect/Krnl/DialectBuilder.cpp
- src/Dialect/Krnl/DialectBuilder.hpp
- src/Dialect/Krnl/Krnl.td
- src/Dialect/Krnl/KrnlOps.cpp
- test/mlir/conversion/krnl_to_affine/yield_to_affine.mlir
- test/mlir/conversion/onnx_to_krnl/Math/MatMul.mlir
- test/mlir/conversion/onnx_to_krnl/Math/MatMulInteger_with_canonicalize.mlir
- test/mlir/conversion/onnx_to_krnl/Math/MatMul_with_canonicalize.mlir
- test/mlir/conversion/onnx_to_krnl/Math/MatMul_with_canonicalize_O3.mlir
- test/mlir/conversion/onnx_to_krnl/Math/Softmax_with_canonicalize.mlir
- test/mlir/conversion/onnx_to_krnl/Math/Softmax_with_parallel_canonicalize_O3.mlir
- test/mlir/conversion/onnx_to_krnl/NN/Conv_with_canonicalize.mlir
- test/mlir/krnl/ops.mlir
Introduce the `krnl.yield` operation within the `krnl.iterate` construct.
This operation functions analogously to `affine/scf.yield`,
yielding zero or more SSA values from a `krnl.iterate` operation region and subsequently terminating said region.
With 'krnl.yield', 'krnl.iterate' will be able to have results like affine.for.
krnl.iterate with results will be look like this.
```
%y0, %y1 = krnl.iterate(%2#0, %2#1) with (%2#0 -> %arg2 = 0 to 10, %2#1 -> %arg3 = 0 to 10) iter_args(%arg4 = %cst, %arg5 = %cst) -> (f32, f32) 
...
krnl.yield %val0, %val1 : f32, f32
}
```
There're 2 iter_args which match the number of results.
The krnl.yield will yield 2 values also.
The init values for iter_args will be at end of the operands for the krnl.yield.
After convert to affine, the above example will …
> [RFC] Introduce `krnl.yield` Operation for `krnl.iterate`

- src/Dialect/ONNX/ONNXOps.td.inc
- src/Dialect/ONNX/ONNXOps/Canonicalize.cpp
- src/Dialect/ONNX/ONNXOps/Canonicalize.td
- test/mlir/onnx/onnx_canonicalization.mlir
- utils/gen_onnx_mlir.py
This patch adds a canonicalization rule to WhereOp to simplify the following pattern (found in the model xlm-roberta-base-language-detection):
```mlir
%0 = onnx.Constant dense<-1> : tensor<2xi64>
%1 = onnx.Constant dense<1> : tensor<2xi64>
%2 = "onnx.Dim"(%arg0) {axis = 0 : si64} : (tensor<?x?xi64>) -> tensor<1xi64>
%3 = "onnx.Dim"(%arg0) {axis = 1 : si64} : (tensor<?x?xi64>) -> tensor<1xi64>
%4 = "onnx.Concat"(%2, %3) {axis = 0 : si64} : (tensor<1xi64>, tensor<1xi64>) -> tensor<2xi64>
%5 = "onnx.Equal"(%4, %0) : (tensor<2xi64>, tensor<2xi64>) -> tensor<2xi1>
%6 = "onnx.Where"(%5, %1, %4) : (tensor<2xi1>, tensor<2xi64>, tensor<2xi64>) -> tensor<2xi64>
```
Since the condition of where, i.e. `%5`, is always false (it compares dimension sizes with -1, and dimension sizes are always positive …
> A pattern to simplify WhereOp

- src/Compiler/CompilerOptions.cpp
- src/Conversion/KrnlToLLVM/ConvertKrnlToLLVM.cpp
Many users of onnx-mlir are not aware of the option `--store-constants-to-file` that would be used for big models. Thus, this patch enables store-constants-to-file by default so that constants will be automatically stored on file whenever the total size of the constants is >= 1.5GB.
> Enable store-constants-to-file by default

- .github/workflows/macos-amd64-build.yml
The macos-latest version is macos 14 that removed python 3.10, so it failed to install protobuf 4.21.12 using python 3.11 or 3.12 in macos 14. So, specifically use macos-13 to avoid unexpected failures, and we would update the macos version at a good timing in the future.
> Use macos-13 for Github Action MacOS

- src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
- src/Accelerators/NNPA/NNPAAccelerator.cpp
- src/Accelerators/NNPA/Pass/NNPAPasses.hpp
- src/Accelerators/NNPA/Transform/ZHigh/CMakeLists.txt
- src/Accelerators/NNPA/Transform/ZHigh/ZHighRecomposeToStickUnstick.cpp
- src/Accelerators/NNPA/Transform/ZHigh/ZHighRecomposeToStickUnstick.td
- test/mlir/accelerators/nnpa/transform/zhigh-recompose-to-stick-unstick.mlir
When using `--enable-zhigh-decompose-stick-unstick` to decompose stick and unstick into LayoutTransform, DLF16ToF32 and F32ToDLF16 ops, some optimizations are applied to remove DLF16ToF32 and F32ToDLF16 ops. But when they are not removed, we would recompose back to zhigh stick and unstick to utilize the optimized code generation for zhigh stick and unstick.
This patch adds a pass for recomposition. The pass is enabled if we compile a model with the option `--enable-zhigh-decompose-stick-unstick`.
Below is the result for roberta-base, where the number of stick and unstick dramatically decreased.
**without --enable-zhigh-decompose-stick-unstick**
**with --enable-zhigh-decompose-stick-unstick**
> [NNPA] Recompose ops back to zhigh stick and unstick if they are not optimized by decomposition

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp
Method `isValidElementTypeAndRank` in  NNPA `ONNXLegalityCheck.cpp` validates that the input tensor is rank 4 or less.  Remove the extraneous checks for this in methods that call `isValidElementTypeAndRank`.
> Remove extraneous rank checks in NNPA ONNXLegalityCheck

- src/Conversion/KrnlToLLVM/ConvertKrnlToLLVM.cpp
New LLVM/MLIR bump introduced a new way to initialize the legality of the OMP ops during OMP to LLVM lowering.
This PR update our code to this new approach.
fixes #2847
> Parallel fix for new mlir

- src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
- src/Conversion/ONNXToKrnl/Additional/LayoutTransform.cpp
- test/mlir/accelerators/nnpa/conversion/onnx-to-krnl/onnx-on-ztensor.mlir
Right now, under the `--enable-zhigh-decompose-stick-unstick` flag, we decompose the stick/unstick into a data conversion and a layout transformation.
The layout transformation op lowering to KRNL was implemented using a simple load/store saving one value at a time.
That implementation significantly lagged in performance compared to zDNN stick/unstick and the compiler generated pattern for stick/unstick.
This implementation look at one stick at a time (guaranteed to be contiguous in memory) and generate a mem copy for all (typically 64) values at once.
It works in a non NNPA context. Given a map `(d0, d1, d2)` it simply checks that the mapped version is either `d2` (identity) or `d2 mod lit` (last dim tiled by `lit` constant value).
When storing into a tiled array, the code does not check …
> Optimize ONNXLayoutTransform

- src/Conversion/ONNXToKrnl/Tensor/ScatterND.cpp
- test/mlir/conversion/onnx_to_krnl/Tensor/ScatterND.mlir
This fix needs to solve this issue for compiling granite-3b-code-instruct https://github.com/onnx/onnx-mlir/issues/2814
Example
```
func.func @test_scatter_nd_with_multiple_remaining_indices(%arg0: tensor<?x?x?x?xi64>, %arg1: tensor<?x?x?x?x4xi64>, %arg2: tensor<?x?x?x?xi64>) -> tensor<?x?x?x?xi64> {
%0 = "onnx.ScatterND"(%arg0, %arg1, %arg2) {reduction = "none"} : (tensor<?x?x?x?xi64>, tensor<?x?x?x?x4xi64>, tensor<?x?x?x?xi64>) -> tensor<?x?x?x?xi64>
return %0 : tensor<?x?x?x?xi64>
}
```
Following code is the part of the results of lowering onnx.ScatterND to krnl.
Before fixing, the number of arguments in `krnl.load` was wrong. This happens `data` rank >= 2 and `indices` rank >= `data` rank.
```
krnl.iterate(%8#0, %8#1, %8#2, %8#3) with (%8#0 -> %arg3 = 0 to #map(%dim_14), %8#1 -> %arg4 …
```
> Fix OnnxToKrnl lowering for ScatterND (data rank >=2 and indices rank >= data rank)

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp
This PR is a fix to the issue found here: https://github.com/onnx/onnx-mlir/issues/2850
We were receiving an error: `Could not get layout by rank. Rank must be 1, 2, 3, or 4` because the check for the rank was off. After several hours of testing, I was able to narrow it down to this commit [cf651e7](https://github.com/onnx/onnx-mlir/commit/cf651e75ba88e391b786b9c7e7009d6efcd02c49) and from there I was able to figure out `src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp` specifically` bool isValidElementTypeAndRank` was generating an incorrect result. 
I noticed it had to do with the range for the rank, previously it was `(rank == 0) || (rank > 5) `but this means if rank is  equal to zero or if rank is greater than 5 but we were not covering the case of `5` itself. That …
> Update Supported Range for Rank in NNPA

- src/Conversion/KrnlToLLVM/KrnlGlobal.cpp
By using this PR, segfault on GPT2 (https://github.com/onnx/onnx-mlir/issues/2822) can be avoided. Still not sure the reason why we can avoid it, but from the tests using following test cases, it seems we can not use the StringAttr for dense constant with i1 (or need to do something to use i1).
- Example including single ConstantOp with i1 type
[model.onnx.const-i1.mlir.txt](https://github.com/user-attachments/files/16104573/model.onnx.const-i1.mlir.txt)
This MLIR file includes only single ConstantOp with dense attribute of i1 type. When running this using following commands, the results were strange (wrong results, segfault, bus error) in main branch. This happened both MaxOS and z16. By using this PR, we got expected results.
```
ONNX_MLIR_HOME=${ONNX_MLIR_ROOT}/build/Debug python …
```
> Avoid using StringAttr when lowering dense constant with i1 type

- src/Compiler/CompilerUtils.cpp
- src/Compiler/CompilerUtils.hpp
- src/onnx-mlir.cpp
- test/mlir/accelerators/nnpa/module_op_be/compiler-config.mlir
- test/mlir/driver/check_passthrough_options.mlir
- test/mlir/driver/compile_phases.mlir
- test/mlir/driver/unix/check_verbosity.mlir
This patch is to show the compilation phases which is helpful when compiling a big model that takes a long time.
This is one example of the printed information:
```shell
$ onnx-mlir -mcpu=z16 -maccel=NNPA bert_base_uncased_1.onnx
[1/5] Wed Jul  3 03:36:50 2024 Importing ONNX Model to MLIR Module
[2/5] Wed Jul  3 03:36:51 2024 Compiling and Optimizing MLIR Module
[3/5] Wed Jul  3 03:37:14 2024 Translating MLIR Module to LLVM and Generating LLVM Optimized Bitcode
[4/5] Wed Jul  3 03:37:35 2024 Generating Object from LLVM Bitcode
[5/5] Wed Jul  3 03:37:39 2024 Linking and Generating the Output Shared Library
```
Starting time is added to each phase so that users know how long the current phase takes
> Show the compilation phases

- src/Dialect/ONNX/ONNXOps/OpHelper.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Reshape.cpp
- test/mlir/onnx/onnx_shape_inference.mlir
The problem was that the check:
```
if ((getShape(vType)[0] == 1) && getElementType(vType).isSignlessInteger(64))
return true;
```
can succeed even if `areDims(Value val)` is not true for all operands of Concat. 
This causes a crash in `getDims`, which recursively calls `getDims` on all operands of Concats, without checking if these operands are dims.
> Fix crash in ReshapeOp inference when an input to the previous concat is not a valid dimension

- utils/RunONNXModel.py
When running with shared library (`--load-so`) and verifying results with onnxruntime (`--verify onnxruntime`), input onnx model (input_model_path) was not set to run onnxruntime. This PR set it and adds error handling.
> Set input onnx model in RunONNXModel.py when running with shared lib and verifying using onnxruntime

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp
I found that message for `--opt-report=NNPAUnsupportedOps` was not displayed in one of the condition in MatMul op.
This PR just adds the missing message.This should have been added in PR https://github.com/onnx/onnx-mlir/pull/2819 .
> [NNPA] Add missing message for `--opt-report=NNPAUnsupportedOps` for MatMul op

- src/Dialect/ONNX/ONNXOps/ShapeHelper.cpp
- src/Dialect/ONNX/ONNXOps/ShapeHelper.hpp
- test/mlir/conversion/onnx_to_krnl/Additional/Custom_with_canonicalize.mlir
The shapehelper for Custom op gives out isImplemented as False in case there is no pattern. This PR solves this issue https://github.com/onnx/onnx-mlir/issues/2870
> [BUG FIX] Added is implemented flag for custom op

- utils/RunONNXModel.py
A prior PR seems to have broken the script
```
alexe@AChampignon roberta-base-11 % RunONNXModel.py -m roberta-base-11.onnx
Traceback (most recent call last):
File "/Users/alexe/OM/onnx-mlir/utils/RunONNXModel.py", line 234, in <module>
if args.verify.lower() == "onnxruntime":
```
this PR fixes this.
> Fix for runing RunONNXModel without verify

- src/Accelerators/NNPA/Transform/ZLow/ZLowStickExpansion.cpp
- src/Compiler/CMakeLists.txt
- src/Dialect/Mlir/DialectBuilder.cpp
- src/Dialect/Mlir/DialectBuilder.hpp
This algorithm adds the equivalent of this (per William Jones) to the stickify compiler generated code.
```C
static const __vector float min_vec = {-8573157376.F, -8573157376.F, -8573157376.F, -8573157376.F};
static const __vector float max_vec = {8573157376.F, 8573157376.F, 8573157376.F, 8573157376.F};
float* a = ...;
float* b = ...;
int16_t* out = ...;
__vector float* vec_a = (__vector float*)a;
__vector float* vec_b = (__vector float*)b;
__vector short* vec_out = (__vector short*)out;
*vec_out = vec_round_from_fp32(
vec_max(vec_min(*vec_a, max_vec), min_vec),
vec_max(vec_min(*vec_b, max_vec), min_vec),
0);
```
When running on z16 with Roberta base 11 and 6x384 in sequential mode
```
zdnn
zhigh.Stick, 85, 0.5742549, 48.8116667, 5.6%
compiler gen code without saturation
zhigh.Stick, 85, …
```
> Saturation in compiler generated Stickify

- src/Dialect/ONNX/DialectBuilder.cpp
- src/Dialect/ONNX/DialectBuilder.hpp
- src/Dialect/ONNX/ONNXOps.td.inc
- src/Dialect/ONNX/ONNXOps/Canonicalize.cpp
- src/Dialect/ONNX/ONNXOps/Canonicalize.td
- src/Dialect/ONNX/Transforms/CMakeLists.txt
- src/Dialect/ONNX/Transforms/Recompose.cpp
- test/mlir/driver/compile_phases.mlir
- test/mlir/driver/static_quantization.mlir
- test/mlir/onnx/onnx_canonicalization.mlir
- test/mlir/onnx/onnx_recompose.mlir
- utils/gen_onnx_mlir.py
Add two patterns found when doing static quantization for bert-base models using onnxruntime.
- 1st pattern: recompose `DequantizeLinear - MatMul - QuantizeLinear` back to `QLinearMatmul`
- 2nd pattern: remove `QuantizeLinear-DequantizeLinear` pairs
> Recompose QLinearMatMul and remove Quantize-Dequantize pairs

- src/Runtime/OMSort.inc
This PR corrects an error in OMSort where the log2u function is incorrectly computing the log base 2.
> Correct log2u in OMSort

- src/Conversion/KrnlToLLVM/ConvertKrnlToLLVM.cpp
This PR partially solves an issue of memory consumption reported in https://github.com/onnx/onnx-mlir/issues/2821 
We found that there is a spike in memory consumption when writing a constant into a file (`model.constants.bin`). This is because all constants into a buffer once and write it to a file at once. This PR changes to write the constant to the file without the buffering. This removes the spike in memory consumption.
> Write a constant value to a file without buffering

- src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
Currently we have issues generating the asm instructions needed for stick/unsick on zOS.
This PR disable this feature until we solve this issue
Issue is tracked in a separate issue
> Disable compliler stick/unstick on zOS

- src/Compiler/CompilerUtils.cpp
- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp
- src/Dialect/Krnl/DialectBuilder.cpp
- test/mlir/conversion/onnx_to_krnl/ControlFlow/Loop.mlir
- test/mlir/conversion/onnx_to_krnl/Math/MatMulInteger_with_canonicalize.mlir
- test/mlir/conversion/onnx_to_krnl/Math/MatMulInteger_with_canonicalize_O3.mlir
Scalar tensor can be tensor<dtype> or tensor<1xdtype>. This patch updates function isScalarTensor and builders for krnl.load and krnl.store to handle both cases.
Resolves #2885
> Update isScalarTensor and krnl.load and krnl.store to hanlde both tensor<dtype> and tensor<1xdtype>

- src/Accelerators/NNPA/Transform/ZLow/ZLowStickExpansion.cpp
Since NHWC is similar to 4D, add it. Did not add the HWCK as this is typically for constants and want to preserve the high level constant propagation of constant values into the Convolution filters.
Saw that during stckification, I was doing a minimum of 64 conversions; but convolutions sometimes have very small E1 dimensions (e.g. 3). So it was wasteful. I now check that if E1 is constant and very small, I do a maximum of `E1<U*VL` iterations where U is as small as possible.
Not needed for unstick as there we must do the exact number of conversions.
> Add NHWC as target for compiler enabled stickification

- src/Accelerators/NNPA/Compiler/NNPACompilerOptions.cpp
- src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
- src/Accelerators/NNPA/Conversion/ZHighToZLow/ZHighToZLow.cpp
- test/accelerators/NNPA/backend/CMakeLists.txt
- test/backend/common.py
- test/mlir/accelerators/nnpa/conversion/zhigh-to-zlow/compiler-stick-unstick.mlir
- test/mlir/accelerators/nnpa/conversion/zhigh-to-zlow/stick-unstick.mlir
- test/mlir/accelerators/nnpa/conversion/zhigh-to-zlow/test-datalayout.mlir
The compiler-generated stick/unstick now supports NHWC layout, but not NCHW layout. To support NCHW, we explicitly do NCHW-NHWC transformation before stick and after unstick.
To get correct results for convolutional models in the backend test, `--nnpa-saturation` is needed. So this patch also enables saturation in the NNPA backend test. We may consider to enable saturation by default.
> Transpose NCHW to NHWC if compiler stick/unstick is enabled and enable model zoo tests on NNPA

- src/Compiler/CompilerOptions.cpp
- src/Compiler/CompilerOptions.hpp
Help to debug a new feature in the compiler and test that it does not change the outputs of a given test.
Say you have a new feature you want to test: enable it under the `debugTestCompilerOpt ` guard:
```C++
#include "src/Compiler/CompilerOptions.hpp"
[...]
if (debugTestCompilerOpt) {
// New code
emitMinMaxReductionToScalar(rewriter, loc, op, X, XMin, XMax);
} else {
// Old code
Value none = create.onnx.none();
XMax = create.onnx.toMemref(
create.onnx.reduceMax(yScaleMemRefType, X, none, false));
XMin = create.onnx.toMemref(
create.onnx.reduceMin(yScaleMemRefType, X, none, false));
}
```
and compile onnx-mlir (Debug version). Then you may run a test like this:
```bash
CheckONNXModel.py -m model.mlir -r "-O3 -mcpu=z16 -maccel=NNPA" -a "-test-compiler-opt"
```
where the model will be first …
> Add onnx-mlir option to debug small optimizations

- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Dialect/Mlir/DialectBuilder.cpp
- src/Dialect/Mlir/DialectBuilder.hpp
The math dialect in MLIR supports operations on scalar or vector inputs, but not a mixture of the two.
When generating SIMD code, we would like to generate a single source of code that can then be used to generate both SIMD code for the innermost SIMD loop, as well as scalar code for the remaining few iterations, if any.
The code to generate SIMD will load `memrefs` either as scalar or vectors; but often there are operations that needs constants, such as "compare to zero", "max of zero"... the scalar are needed then as a scalar in scalar code, but as a splatted constant when generating SIMD code.
The most robust method to provide this functionality is to provide implicit "splat" for each of the MathBuilder operations.
This PR does this.
This code will later be put to good use in a …
> Implicit broadcast of scalar values to vector values in the MathBuilder constructor

- docs/BuildOnLinuxOSX.md
- docs/BuildOnWindows.md
- src/Accelerators/NNPA/Conversion/ZLowToLLVM/ZLowToLLVMCommon.cpp
- src/Conversion/KrnlToLLVM/KrnlPrint.cpp
- src/Dialect/Mlir/DialectBuilder.cpp
- src/Dialect/Mlir/DialectBuilder.hpp
- src/onnx-mlir.cpp
- test/mlir/accelerators/nnpa/conversion/lower-all-to-llvm-constant-shape.mlir
- test/mlir/accelerators/nnpa/conversion/lower-all-to-llvm-typed-pointer.mlir
- test/mlir/accelerators/nnpa/conversion/lower-all-to-llvm.mlir
- test/mlir/accelerators/nnpa/transform/zlow-stick-unstick-expansion.mlir
- test/mlir/conversion/krnl_to_llvm/input_verification.mlir
- test/mlir/conversion/krnl_to_llvm/krnl_math_function_lowering.mlir
- test/mlir/conversion/krnl_to_llvm/reshape.mlir
- utils/clone-mlir.sh
llvm-project : 60a7d33106d3cd645d3100a8a935a1e3837f885d 
stablehlo: 92203a9612dbdd6681ccd3e65bc61586c4290df1
> Update llvm-project to 60a7d33106d3cd645d3100a8a935a1e3837f885d 

- .buildbot/Jenkinsfile
Current Jenkins build typically takes less than 3 hours. Timeout a build after 6 hours to account for the case when the build died badly (typically due to segfault) and didn't get a chance to report failure.
> Timeout a build after 6 hours

- src/Accelerators/Accelerator.hpp
- src/Accelerators/NNPA/Runtime/zDNNExtension/zDNNExtension.c
- src/Accelerators/NNPA/Runtime/zDNNExtension/zDNNExtension.h
- src/Accelerators/NNPA/Support/Stickify/Stickify.cpp
- src/Runtime/OMSort.inc
- src/Runtime/OMTensor.inc
- src/Runtime/jni/jnilog.c
- src/Runtime/jni/jnilog.h
- src/Runtime/jni/jniwrapper.c
- src/Support/SmallFPConversion.c
- src/Tools/binary-decoder/BinaryDecoder.cpp
- test/compilerlib/CompilerLibTest.cpp
- test/perf/PerfHelper.hpp
Update code to add macro parameter names with parentheses to zDNNExtension and Stickify.
> Update macro parameter names with parentheses

- docker/Dockerfile.onnx-mlir
- docs/BuildOnLinuxOSX.md
- utils/install-onnx-mlir.sh
When we build LLVM in release mode, assertions are enabled by default. 
We should probably do the same for ONNX-MLIR.
> Added Release with enable assertion to default build of ONNX MLIR

- src/Conversion/ONNXToKrnl/Quantization/QuantizeLinear.cpp
- test/mlir/conversion/onnx_to_krnl/Quantization/QuantizeLinear_with_canonicalize.mlir
The lowering of ONNXQuantizeLinear itself supports i8, but there is an assert to check and discard the i8 case (Unfortunately, I don't know the reason for that assert).
This patch removes the assert to allow the i8 case and adds a lit test for that.
> Support i8 in lowering ONNXQuantizeLinear

- src/Builder/FrontendDialectTransformer.cpp
- test/mlir/onnx/parse/test_cast.onnxtext
ONNXCast opset >=19 introduces a new attribute `saturate` and onnx-mlir wrongly imported the attribute.
For example, onnx-mlir imported ONNXCast as follows:
```mlir
%755 = "onnx.Cast"(%746) {onnx_node_name = "/bert/Cast", saturate = f32, to = f32} : (tensor<?x?x?x?xi64>) -> tensor<?x?x?x?xf32>
```
where `saturate = f32` was wrong, it would be `saturate = 0 : si64` or `saturate = 1 : si64`.
This patch fixes the issue by fixing the importing code for Cast's attributes.
> Fix importing Cast opset >=19

- src/Compiler/CompilerUtils.cpp
This PR adds checks for the result from time() and localtime() calls.
> Check time and localtime during compile

- src/Accelerators/NNPA/Conversion/ZLowToLLVM/ZLowToLLVMCommon.cpp
- src/Accelerators/NNPA/Support/Stickify/Stickify.cpp
- src/Conversion/KrnlToLLVM/KrnlEntryPoint.cpp
- src/Conversion/KrnlToLLVM/KrnlToLLVMHelper.cpp
- src/Dialect/Mlir/IndexExprBuilder.cpp
This PR updates c style casts to c++ style.
> Change c style cast to c++ style cast

- CODING_PRACTICE.md
- CONTRIBUTING.md
This PR adds a coding practices documentation file to describe the coding practices to use when updating or adding code to onnx-mlir.
> Add coding practices for onnx-mlir

- src/Compiler/CompilerOptions.cpp
- src/Compiler/CompilerOptions.hpp
- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- test/mlir/conversion/onnx_to_krnl/onnx_lowering_reuse.mlir
Previous,  a new memref is always created when onnx is lowered to krnl.
However, an input buffer could be reused as output, if  the input has only only one use and the shape is the same as the output. The PR tried this idea on element-wise operations.
by default, the buffer reuse is turned off.
This feature is tested with Roberta-base-11.onnx. About 80% of malloc (in either numbers or memory size) can be avoided with buffer reuse. The buffer reuse code can generate correct result, but did not bring notable performance improvement, with either SIMD on or off.
> Reuse input buffer in lowering to krnl

- docs/SupportedONNXOps-cpu.md
- test/backend/inference_backend.py
ONNX now supports in4 and uint4 but we do not have the hardware to do so. Indicating that we do not support these data types for the latest Opset version.
Update to support int4 and uint4:
[Cast](https://onnx.ai/onnx/operators/onnx__Cast.html#cast-21), [CastLike](https://onnx.ai/onnx/operators/onnx__CastLike.html#CastLike-21), [Constant](https://onnx.ai/onnx/operators/onnx__Constant.html#Constant-21), [ConstantOfShape](https://onnx.ai/onnx/operators/onnx__ConstantOfShape.html#ConstantOfShape-21), [Identity](https://onnx.ai/onnx/operators/onnx__Identity.html#Identity-21), [If](https://onnx.ai/onnx/operators/onnx__If.html#If-21), [Loop](https://onnx.ai/onnx/operators/onnx__Loop.html#Loop-21), [Reshape](https://onnx.ai/onnx/operators/onnx__Reshape.html#Reshape-21), …
> Update Ops documentation for ONNX 1.16.2

- docs/Dialects/krnl.md
- src/Compiler/CompilerPasses.cpp
- src/Conversion/KrnlToAffine/ConvertKrnlToAffine.cpp
- src/Dialect/Krnl/DialectBuilder.cpp
- src/Dialect/Krnl/DialectBuilder.hpp
- src/Dialect/Krnl/Krnl.td
- src/Pass/Passes.hpp
- src/Tools/onnx-mlir-opt/RegisterPasses.cpp
- src/Transform/CMakeLists.txt
- src/Transform/ProcessKrnlParallelClause.cpp
- src/Transform/ProcessKrnlParallelClause.hpp
- src/Transform/ProcessScfParallelPrivate.cpp
- test/mlir/conversion/krnl_to_affine/krnl_to_affine_parallel_clause.mlir
- test/mlir/parallel/krnl_parallel_clause_to_omp.mlir
Added support to generate OpenMP parallel construct with `num_threads` and `proc_bind` clause.
First I added two optional parameters to the `krnl.parallel` operation:
```mlir
%loop_block, %loop_local = krnl.block %0 32 : (!krnl.loop) -> (!krnl.loop, !krnl.loop)
krnl.parallel(%loop_block), num_threads(%c8_i32) {proc_bind = "spread"} : !krnl.loop
krnl.iterate(%loop_block) with (%0 -> %arg1 = 0 to 16384){
%1 = krnl.get_induction_var_value(%loop_block) : (!krnl.loop) -> index
%2 = vector.load %reshape[%1] : memref<16384xf32>, vector<32xf32>
%3 = vector.load %reshape_2[%1] : memref<16384xf32>, vector<32xf32>
%4 = arith.addf %2, %3 : vector<32xf32>
vector.store %4, %reshape_4[%1] : memref<16384xf32>, vector<32xf32>
}
```
which allows the user to associate parallel loops with an optional …
> Added support to generate OpenMP parallel construct clauses, at this time for num_threads and proc_bind

- utils/mlir2FileCheck.py
The python script `mlir2FileCheck` does not handle multiple output arguments, for example, it prints out:
```
// CHECK:           [[VAR_Out_]], [[VAR_RecScale_]], [[VAR_Offset_:%.+]] = ....
```
where only the last output has `:%.+`. The correct one would be
```
// CHECK:           [[VAR_Out_:%.+]], [[VAR_RecScale_:%.+]], [[VAR_Offset_:%.+]] = "
```
This fixes the issue by defining a new regex that captures a repeated group that contains all output arguments, then parses them.
> [mlir2FileCheck tool] handle multiple output arguments

- src/Conversion/KrnlToLLVM/KrnlCall.cpp
- src/Dialect/Krnl/Krnl.td
- src/Dialect/Krnl/KrnlOps.cpp
- test/mlir/conversion/krnl_to_llvm/call_with_return.mlir
This PR allows KrnlCallOp to have a scalar return, AnyFloat or AnyInteger, and the lowering will use the return of func.call to implement the return. When there is no return, the previous usage does not need to change.
A lit test is added. The input is
```
%1 = "krnl.call"() {funcName = "get_omp_num_thread", numOfOutput = 0 : si64} : () -> (i32)
```
The output is 
```
%0 = llvm.call @get_omp_num_thread() : () -> i32
```
The krnl call can be generated with 
```
rewriter.create<KrnlCallOp>(loc, TypeRange(rewriter.getIntegerType(32)), "omp_get_num_thread", 0, ValueRange());
```
> Add support of return for KrnlCallOp

- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Conversion/ONNXToKrnl/Quantization/QuantizeLinear.cpp
- src/Dialect/Mlir/DialectBuilder.cpp
- src/Dialect/Mlir/DialectBuilder.hpp
- src/Dialect/Mlir/VectorMachineSupport.cpp
- src/Dialect/Mlir/VectorMachineSupport.hpp
- test/mlir/conversion/onnx_to_krnl/Quantization/DynamicQuantizeLinear_with_canonicalize.mlir
- test/mlir/conversion/onnx_to_krnl/Quantization/DynamicQuantizeLinear_with_simd_canonicalize.mlir
- test/mlir/conversion/onnx_to_krnl/Quantization/DynamicQuantizeLinear_with_simd_parallel_canonicalize.mlir
- test/mlir/conversion/onnx_to_krnl/Quantization/QuantizationWithoutZeroPoint.mlir
- test/mlir/conversion/onnx_to_krnl/Quantization/QuantizeLinear_with_canonicalize.mlir
When deciding the amount of unrolling of a simd loop, it is helpful to take into account the amount of register pressure. If unrolling a loop that use a lot of vector SIMD registers, this lead to spilling and thus lower performance.
Up to now, the register pressure was estimated as the number of SIMD ops / 2, roughly. That worked well for small loops. Linear Quantization, however, has a lot of operations that are very sequential, thus do not need many registers. But since it had a lot of operations, its estimated register pressure was high, and thus prevented loop unrolling.
I have added a new "metrics" in the map that describe the generic operations used in a loop. Before it was only "generic add" -> "3", meaning this kernel uses 3 generic adds.
I have now added a new enum value, …
> Added explicit register pressure estimate for SIMD and tuned [Dynamic]LinearQuantization operations

- src/Dialect/ONNX/ONNXOps/Canonicalize.cpp
- src/Dialect/ONNX/ONNXOps/Canonicalize.td
- test/mlir/onnx/onnx_canonicalization.mlir
Remove the rule that rewrites a quantize-dequantize pair to identity. It's because there is a rounding in the QuantizeLinear's formulas so that the pair is mathematically not the same as identity.
> Revert the rule that rewrites a quantize-dequantize pair to identity

- src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ZHighToONNX.td
Simplify some rules in `zhigh-to-onnx` pass and change the order of calling `zhigh-to-onnx` and `constprop-zhigh` in which `constprop-zhigh` is called after `zhigh-to-onnx` so that `zhigh-to-onnx` can recompose `stick->nnpa_op->unstick` back into an onnx op.
> [NNPA] Simplify rules in zhigh-to-onnx pass and change some pass order

- src/Compiler/CompilerOptions.cpp
- src/Compiler/CompilerOptions.hpp
- src/Compiler/CompilerUtils.cpp
Issue #2950 discovered the issue in passing options llvm. There are several problems:
1. The string of the options has to be split into vector of strings for the command format.
2. Conflict in options. So far, the optimization level is the only example.  The level specified with  particular step should have higher priority than that for the whole compiler. Thus, I can avoid multiple "-O#" error.
3. modify the comments for mllvm, xopt, and xllc to make it easy for user to pass multiple values to these options 
I tested with some examples.
> Handle the options passed to llvm opt and llvm llc

- src/Compiler/CompilerUtils.cpp
- print javaruntime.jar path when -v (verbose) is specified for debugging aid
- replace printf with llvm::outs() for consistency
- fix typo ouputNameWithExt
> Minor updates to CompilerUtils.cpp

- src/Compiler/CompilerOptions.cpp
Since NNPA uses less precise data, it is reasonable to enable aggressive optimization.
Add the flag only for O3, leaving O0 for debugging.
> Add --enable-unsafe-fp-math flag when -O3 and NNPA is used

- src/Accelerators/NNPA/Transform/ZLow/ZLowStickExpansion.cpp
- src/Dialect/Mlir/IndexExpr.hpp
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/gru.mlir
- test/mlir/accelerators/nnpa/transform/zlow-stick-unstick-expansion.mlir
I suspect that the code generation pattern for Unstick may have been too complicated for the specific constant sizes found in the java8 program failed.
This PR simplifies the pattern for predictive constant patterns.
> Java8 unstick issue

- src/Dialect/ONNX/DialectBuilder.cpp
- src/Dialect/ONNX/DialectBuilder.hpp
- src/Dialect/ONNX/ONNXOps/OpHelper.cpp
- src/Dialect/ONNX/ONNXOps/OpHelper.hpp
- src/Dialect/ONNX/ONNXOps/OpHelper.hpp.inc
- src/Dialect/ONNX/Transforms/CMakeLists.txt
- src/Dialect/ONNX/Transforms/ConstProp.cpp
- src/Dialect/ONNX/Transforms/Recompose.cpp
- test/mlir/onnx/onnx_recompose.mlir
This patch recomposes multiple operations into a single ONNXGelu operation.
> Recompose multiple ops into a single ONNXGelu

- src/Dialect/ONNX/Transforms/ConstProp.td
- test/mlir/onnx/onnx_constprop.mlir
This patch updates two associate rules in constant propagation for Add and Mul to avoid rewriting when both two inputs are scalar. In particular, these are two rules to update:
- `(x + (y + c))` to `(x + y) + c`: do not apply this when `y` and `c` are scalar
- `(x + c) + y)` to `(x + y) + c`: do not apply this when `x` and `c` are scalar
> Do not rewrite add/mul of scalar values in constprop

- utils/RunONNXLib.cpp
The interface of StringRef was changed in the new version of llvm_project.  The member function `equal` is removed. This PR uses `compare` to do the job.
> Update c++ driver for running onnx model

- src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
- src/Accelerators/NNPA/Conversion/ZLowToLLVM/ZLowToLLVM.cpp
- src/Conversion/KrnlToLLVM/KrnlRoundEven.cpp
This PR updates the SIMD assembler instructions for z/OS when lowering to LLVM.
> Update SIMD assembler instructions for z/OS

- docs/SupportedONNXOps-cpu.md
- test/backend/inference_backend.py
Since this PR was merged: https://github.com/onnx/onnx-mlir/pull/2744, we now have the support for `keepdims` and as a result a few of the backend test can be re-enabled.
> Re-enable ReduceMax/Min backend tests

- src/Accelerators/NNPA/Transform/ZLow/ZLowStickExpansion.cpp
- test/mlir/accelerators/nnpa/transform/zlow-stick-unstick-expansion.mlir
After lengthy proofing of the code, I realized that there was an innocuous `aligned alloca` of 8 bytes inside an inner loop of the compiler generated unstickify. Thus, according to the current rules, a new chunk of memory was generated for each inner loop, eventually running out of memory. This happens for large benchmarks for which there are data sizes of buffers to unstickify that were not multiple of 8 (like yolo, where the images reduces from 400+ all the way to 13).
This has been fixed by having a single `aligned alloc` (heap, not stack) inside of the outer loops (to support parallelism).
A few minor cleanup was also performed.
I will review all instances of `alloca` in a subsequent PR to ensure this issue may not generate other issues in related situations.
Since we don't have a …
> Yolo bug: run out of stack memory

- src/Accelerators/NNPA/Compiler/NNPACompilerOptions.cpp
- src/Compiler/CompilerOptions.cpp
fix spelling, punctuation in `onnx-mlir -h` generated text.
not perfect but better.
> [NON FUNCTIONAL CHANGE] Fix spelling, punctuation, and some end of line in onnx-mlir help

- utils/RunONNXModel.py
This patch improves RunONNXModel.py script with the following changes:
- Add two options `--print-input-signature` and `--print-output-signature` to print out signatures.
- Support big models that are compiled into two output files: `model.so` and `model.constants.bin`
> [RunONNXModel.py] Add options to print out input/output signatures and support big models

- utils/python/transformers/run_gpt2_from_huggingface.py
This patch:
- creates a folder `utils/python/transformers` to host python scripts to run end-to-end tests with HuggingFace models (ONNX or pytorch). We can discuss about whether this folder is good for such purpose or it should be another folder.
- creates a python script `run_gpt2_from_huggingface.py` to run GPT2. The script downloads the onnx models from HuggingFace and compile them and generate text for a given prompt.
> Add a python script for generating text using huggingface gpt2

- src/Dialect/ONNX/ElementsAttr/DisposablePool.cpp
- src/Dialect/ONNX/Transforms/ScrubDisposablePass.cpp
This PR removes a spike in memory usage. When checking memory usage in a LLM (Mistral-7b), ScrubDisposablePass consumes a lot of memory only for a moment(spike about 50GB). This is likely to due to the fact that having both denseElementsAttr and disposalElementsAttr are hold during conversion. 
In Mistral-7b model, the spike is about 23GB, and total memory usage including spike is about 50GB.  This PR removes the spike and total memory usage reduces to 27GB.
> Remove a spike of memory usage in ScrubDisposablePass.

- utils/RunONNXModel.py
Right now, we can save a model with `-save-model=x` and then reuse it with `-load-model=x`.
The current `-cache-model=x` option will save the model when the model does not exist, and reuse it when it exists.
Minor, but that way I can run a model using the same scripts many times in a row and benefit from caching,
> RunONNXModel.py: Add a `--cache-model=path` option

- docker/Dockerfile.onnx-mlir
- test/accelerators/NNPA/backend/CMakeLists.txt
Enable `make check-onnx-backend-numerical-nnpa` on Jenkins s390x for testing NNPA.
JNI tests for NNPA failed for convolutional models, so we temporarily disable these JNI tests.
> Enable check-onnx-backend-numerical-nnpa on Jenkins s390x

- utils/RunONNXModel.py
When using `--save-model=save_folder` or `--cache-model=save_folder`, a file `compile.log` is created inside `save_folder` that contains all the compilation log printed out by the compiler.
This is helpful to know how a model was compiled.
> RunONNXModel.py: save compilation info into a file when using --save-model or --cache-model

- src/Compiler/CompilerUtils.cpp
- src/Compiler/CompilerUtils.hpp
- src/onnx-mlir.cpp
- test/mlir/driver/compile_phases.mlir
> Fix wrong total number of phases for EmitObj and EmitJNI

- utils/python/transformers/run_gpt2_from_huggingface.py
This patch updates the python script `run_gpt2_from_huggingface.py` so that it does not download `.onnx_data` files if they exist.
> run_gpt2_from_huggingface.py: do not download the onnx data file if it exists

- src/Runtime/OMExternalConstant.inc
> Opening binary constants files fix on zOS

- src/Conversion/KrnlToLLVM/ConvertKrnlToLLVM.cpp
This is to fix a wrong function call that converts an ASIIC string to EBCDIC.
> Fix a wrong function call

- src/Accelerators/NNPA/Runtime/zDNNExtension/zDNNExtension.h
Compiling and linking runtime files on zOS using ibm-clang compiler will error. 
```
IEW2456E 9207 SYMBOL omUnreachable UNRESOLVED.  MEMBER COULD NOT BE INCLUDED
FROM THE DESIGNATED CALL LIBRARY.
```
Following suggestions "In C99 you need to provide an alternate (non-inline) definition of the function for when the compiler can't inline."
https://stackoverflow.com/questions/69384040/why-do-i-get-a-linking-error-with-clang-when-inlining-a-function-in-a-c-program
I am open to trying alternative methods to support clang compilers if there are other suggestions.
> Making runtime omunreachable static to support clang compiler

- src/Dialect/ONNX/Transforms/ConstProp.td
- test/mlir/onnx/onnx_constprop_locations.mlir
Without this PR, the location of the Add/Mul will be incorrectly fused with the location of the constant.
> Do not fuse locations when normalizing constants for Add and Mul

- src/Conversion/ONNXToKrnl/Math/Reduction.cpp
- test/mlir/conversion/onnx_to_krnl/Math/Reduction_with_canonicalize_O3.mlir
- test/mlir/conversion/onnx_to_krnl/Math/Reduction_with_parallel_canonicalize_O3.mlir
Parallel/SIMD reduction over all dimensions is currently used for supporting quantization only, but it's not applied to original ONNX reduction ops.
This patch is simply enabling the full reduction to the original ONNX reduction ops.
> Handle full reduction over all dimensions

- src/Dialect/ONNX/ONNXOps/Math/DFT.cpp
- src/Dialect/ONNX/ONNXOps/Math/MatMul.cpp
- src/Dialect/ONNX/ONNXOps/Math/Reduction.cpp
- src/Dialect/ONNX/ONNXOps/Math/TopK.cpp
- src/Dialect/ONNX/ONNXOps/NN/Conv.cpp
- src/Dialect/ONNX/ONNXOps/NN/NNHelper.cpp.inc
- src/Dialect/ONNX/ONNXOps/NN/Pooling.cpp
- src/Dialect/ONNX/ONNXOps/ShapeHelper.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Compress.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/DepthToSpace.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/NonZero.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/OneHot.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Pad.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Resize.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Shape.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/SpaceToDepth.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Split.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Squeeze.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Tile.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Transpose.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Unique.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/Unsqueeze.cpp
Some  `computeShape` functions assume/rely on the operands being ranked.
This PR adds a check to them, so that they return `failure` in case this assumption does not hold, instead of asserting. This allows callers of this function to handle this failure
> Return a failure instead of crashing if shape inference can not be run because of unraked operand types

- src/Dialect/ONNX/Transforms/Decompose.cpp
- test/mlir/onnx/onnx_decompose.mlir
Before this PR the `oneDimShape` assumed a spacial rank of two, which is only correct for rank==4.
> Fix biasScaleShape of GroupNormalizationV21 to support ranks > 4

- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXLegalityCheck.cpp
- src/Accelerators/NNPA/Conversion/ONNXToZHigh/ONNXToZHigh.td
- src/Accelerators/NNPA/Conversion/ZHighToZLow/ZHighToZLow.cpp
- src/Accelerators/NNPA/Conversion/ZLowToLLVM/ZLowToLLVM.cpp
- src/Accelerators/NNPA/Conversion/ZLowToLLVM/ZLowToLLVMCommon.cpp
- src/Accelerators/NNPA/Conversion/ZLowToLLVM/ZLowToLLVMCommon.hpp
- src/Accelerators/NNPA/Dialect/ZHigh/ZHigh.td
- src/Accelerators/NNPA/Dialect/ZHigh/ZHighOps/Reduction/Reduction.cpp
- src/Accelerators/NNPA/Dialect/ZLow/ZLow.td
- test/accelerators/NNPA/backend/CMakeLists.txt
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/reducemax.mlir
- test/mlir/accelerators/nnpa/conversion/onnx-to-zhigh/reducemin.mlir
- test/mlir/accelerators/nnpa/conversion/zhigh-to-zlow/reducemax.mlir
- test/mlir/accelerators/nnpa/conversion/zhigh-to-zlow/reducemin.mlir
Currently, ReduceMin/ReduceMax failed to run on NNPA. This patch is to make them work and produce correct results.
Test program:
```
module {
func.func @main_graph(%arg0: tensor<3x2x2xf32> {onnx.name = "x"}) -> (tensor<*xf32> {onnx.name = "y"}) {
%cst = "onnx.Constant"() {value = dense<[2]> : tensor<1xi64> } : () -> tensor<1xi64>
%0 ="onnx.ReduceMax"(%arg0, %cst) {keepdims = 1 : si64, noop_with_empty_axes = 0 : si64} : (tensor<3x2x2xf32>, tensor<1xi64>)-> tensor<*xf32>
"func.return"(%0) : (tensor<*xf32>) -> ()
}
"onnx.EntryPoint"() {func = @main_graph} : () -> ()
}
```
Output using this patch:
```
python ../utils/RunONNXModel.py -m reducemax.mlir -c "-O3 -march=arch15 -maccel=NNPA" --print-input --print-output
Temporary directory has been created at <TemporaryDirectory '/tmp/tmpxs_l058r'> …
```
> [NNPA] Fix some bugs for ReduceMin/Max

- src/Dialect/ONNX/ONNXOps/Math/Scatter.cpp
- src/Dialect/ONNX/ONNXOps/OpHelper.cpp
- src/Dialect/ONNX/ONNXOps/OpHelper.hpp
- src/Dialect/ONNX/ONNXOps/Sequence/SplitToSequence.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/ConstantOfShape.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/GatherElements.cpp
- src/Dialect/ONNX/ONNXOps/Tensor/GatherND.cpp
- test/mlir/onnx/invalid.mlir
Elided elements are uninitialized DenseResourceAttrs.
Without these changes MLIR containing elided DenseResourceAttrs can not be parsed, as the verifiers crash when encountering them.
> Skip over uninitialized DenseResourceAttrs in verifiers

- docs/AddCustomAccelerators.md
- src/Accelerators/CMakeLists.txt
- test/mlir/CMakeLists.txt
This PR updates `docs/AddCustomAccelerators.md` with instructions to build multiple accelerators.
> Update the instruction for building multiple accelerators

- docs/Quantization-NNPA.md
This PR adds a document file `docs/Quantization-NNPA.md` to explain how to use quantization on NNPA.
> Add a document for quantization on NNPA

- src/Dialect/ONNX/ONNXDimAnalysis.cpp
- test/mlir/onnx/onnx_dim_analysis.mlir
- Fixes a memory leak
- Fixes an integer overflow caused by a dynamic shape
- Fixes reshape to wrong type in LIT tests
> Fix ASAN/UBSAN issues in DimAnalysis

- requirements.txt
The onnx submodule is using version 1.17.0, so I think the version used in the requirements should be the same
> Update onnx requirement to 1.17.0

- .buildbot/jenkins_common.py
This updates the sha algorithm for the docker images from sha1 to sha3_256. I have avoided renaming the use of sha1 in various docker files for now with something as generic as hash, but if there is feedback to change those variable names from tied to an algorithm to being generic, I can do that as feedback.
> fix weak hash

- docs/Dialects/onnx.md
- docs/Dialects/zlow.md
- src/Accelerators/NNPA/Compiler/NNPACompilerUtils.cpp
- src/Compiler/CompilerOptions.cpp
- src/Compiler/CompilerOptions.hpp
- src/Compiler/CompilerPasses.cpp
- src/Compiler/CompilerPasses.hpp
- src/Conversion/ONNXToKrnl/Tensor/PrintSignature.cpp
- src/Dialect/ONNX/AdditionalONNXOps.td
- src/Dialect/ONNX/Transforms/InstrumentONNXSignaturePass.cpp
- src/Pass/Passes.hpp
- src/Tools/onnx-mlir-opt/RegisterPasses.cpp
Extend instrumentSignature to be a tool that can be used to print the data of a particular onnx op at runtime.
1. Change in the op selection. If the option instrumentSignature starts with "onnx_node_name:", only the rest of the string is used as regular expression pattern, and the attribute of "onnx_node_name", instead of op->getName(), is used to match. This change allows user to target a particular onnx op.
2. When the op is mapped with onnx_node_name, the data of the tensors will be printed. Therefore, one attribute is added to onnx.PrintSignature op.
3. Consequently, the lowering of PrintSignature op is modified.
4. Another change, which may not be needed, is that the instrumentSignature pass is moved from onnx to mlir group to onnx transformation group, right after the other onnx …
> Extend instrumentSignature to print data

- src/Runtime/python/onnxmlirdocker.py
Previous driver only works with python docker package. This PR adds the support for podman package.
The interface of the docker and podman package is the same for the features used in this driver so far.  
Another change in this PR is to pull the image if it does not exist locally. 
Three cases tested:
Inside onnx-mlir-dev container:
sess = onnxmlir.InferenceSession("gather-2.mlir", compiler_path="../build-2024/Debug/bin/onnx-mlir", compiler_image_name=None)
outside container:
1. sess = onnxmlir.InferenceSession("gather-2.mlir", compiler_container_engine="docker")
2. sess = onnxmlir.InferenceSession("gather-2.mlir", compiler_container_engine="podman")
> Use docker and podman package in python driver

- src/Runtime/OMTensor.inc
Fixing errors when creating `libcruntime.a` on z/OS when the model includes constants.bin file.
```
IEW2456E 9207 SYMBOL __errno_location UNRESOLVED.  MEMBER COULD NOT BE INCLUDED
FROM THE DESIGNATED CALL LIBRARY.
IEW2665S 40FF MODULE *NULL*  IS NON-EXECUTABLE AND WAS NOT SAVED BECAUSE
STORENX=NEVER.
```
> Including __errno_location call for MVS

- src/Runtime/OMTensor.inc
When creating libcruntim.a on z/OS compiling with the latest version of xlc leads to this warning. 
```
xlc -I ../.. -I ../../include -q64 -Wc,DLL,EXPORTALL -qlanglvl=extc99 -D_XOPEN_SOURCE=600 -c -o OMTensor.o OMTensor.c
WARNING CCN3943 ./OMTensor.inc:54    Attribute "__weak__" is not supported on the target platform and is ignored.
INFORMATIONAL CCN4108 ./OMTensor.inc:54    The use of keyword '__attribute__' is non-portable.
```
> removing weak attribute of errorno

- utils/build-run-onnx-lib.sh
This PR add the support of flexibility of input/output of c++ driver.
1. Input: Originally, the utils/build-run-onnx-lib.sh is required to be call from onnx-mlir/build. With this PR, user can specify the path of compiler with env ONNX_MLIR_HOME.
2. Output: originally, the binary is written to onnx-mlir/build/bin/run-onnx-lib. The PR allows user to specify the binary with the extra argument.
The old way of using build-run-onnx-lib.sh will not be affected by this PR.
> Improve the c++ driver build-run-onnx-lib.sh

- docs/mnist_example/requirements.txt
Fix the MNIST-example requirements.txt https://nvd.nist.gov/vuln/detail/CVE-2025-32434
> fix CVE-2025-32434

- docs/SupportedONNXOps-cpu.md
- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- test/backend/inference_backend.py
- test/mlir/conversion/onnx_to_krnl/Math/Elementwise_with_canonicalize.mlir
- test/mlir/conversion/onnx_to_krnl/Math/Elementwise_with_canonicalize_O3.mlir
Added support for Celu op in the ONNX to krnl and also added the test case in Elementwise_with_canonicalize.mlir and Elementwise_with_canonicalize_O3.mlir
closes https://github.com/onnx/onnx-mlir/issues/3137
> added support for Celu op

- src/Accelerators/NNPA/Support/Stickify/Stickify.cpp
This patch fixes the following warnings when building onnx-mlir for NNPA:
```shell
/workdir/onnx-mlir/src/Accelerators/NNPA/Support/Stickify/Stickify.cpp: In function 'const char* get_data_format_str(zdnn_data_formats)':
/workdir/onnx-mlir/src/Accelerators/NNPA/Support/Stickify/Stickify.cpp:229:10: warning: enumeration value 'ZDNN_FORMAT_4DWEIGHTS' not handled in switch [-Wswitch]
229 |   switch (format) {
|          ^
/workdir/onnx-mlir/src/Accelerators/NNPA/Support/Stickify/Stickify.cpp:229:10: warning: enumeration value 'ZDNN_FORMAT_4DGENERIC' not handled in switch [-Wswitch]
/workdir/onnx-mlir/src/Accelerators/NNPA/Support/Stickify/Stickify.cpp: In function 'short int get_data_type_size(zdnn_data_types)':
/workdir/onnx-mlir/src/Accelerators/NNPA/Support/Stickify/Stickify.cpp:244:10: …
```
> Fix some warnings related to stickification for NNPA

- src/Dialect/ONNX/ONNXOps/Canonicalize.td
- test/mlir/onnx/onnx_canonicalization_locations.mlir
As both operations still do their original functionality and did not get merged together, I think not fusing their locations is correct in this case.
I created a new test file for the location test, as `--mlir-print-debuginfo` makes it more difficult to write LIT tests and I do not want to impact the main canonicalization LIT test by enabling this option
> Do not fuse locations in Maxpool-Relu canonicalization

- src/Compiler/CompilerOptions.cpp
- src/Dialect/Mlir/VectorMachineSupport.cpp
The -march=native results in a `apple-m1` arch (or derivatives) on Macs, which is not recognized by the `onnx-mlir` simd code generator as well as `llc`.
Add here the code to handle this properly. Also added a print of the native machine being detected under the verbose flag `-v` so that we may discover what machine is actually compiled for.
> Support for arch native on mac

- docs/SupportedONNXOps-cpu.md
- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- test/backend/inference_backend.py
- test/mlir/conversion/onnx_to_krnl/Math/Elementwise_with_canonicalize.mlir
- test/mlir/conversion/onnx_to_krnl/Math/Elementwise_with_canonicalize_O3.mlir
Added support for the BitwiseNot operation in the ONNX to Krnl lowering path. Also included corresponding test cases in Elementwise_with_canonicalize.mlir and Elementwise_with_canonicalize_O3.mlir. This implementation addresses and 
closes https://github.com/onnx/onnx-mlir/issues/3155
> added support for bitwise_not op

- docs/SupportedONNXOps-cpu.md
- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- test/backend/inference_backend.py
- test/mlir/conversion/onnx_to_krnl/Math/Elementwise_with_canonicalize.mlir
- test/mlir/conversion/onnx_to_krnl/Math/Elementwise_with_canonicalize_O3.mlir
This pull request implements the lowering of the `ThresholdedRelu` op from the ONNX dialect to the Krnl dialect, and add tests to validate it, addressing Issue #3151.
This PR is ready for review. Please let me know if there are any additional improvements or adjustments needed.
Closes #3151.
> Add Lowering of ThresholdedRelu op from ONNX to Krnl Dialect

- src/Accelerators/NNPA/Support/Stickify/Stickify.cpp
- src/Dialect/ONNX/DialectBuilder.cpp
- src/Dialect/ONNX/DialectBuilder.hpp
I saw one warning where we return a stack object. It's in the `toTensors`, and I fixed this using Tong's suggestion of returning a `SmallVector<Types, 4>`.
Then there were also 2 warnings, associated with creating arrays on the stack with a runtime size:
```
int num = ...
char buff[num]
```
which is not supported by all compilers. Also, if `num` is large, we may run out of stack. Replaced both instance with dynamic allocation asserting if results of malloc are null.
> Remove most warnings (includes building for NNPA)

- docs/SupportedONNXOps-cpu.md
- src/Conversion/ONNXToKrnl/CMakeLists.txt
- src/Conversion/ONNXToKrnl/ConvertONNXToKrnl.cpp
- src/Conversion/ONNXToKrnl/Math/MeanVarianceNormalization.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- test/backend/inference_backend.py
- test/mlir/conversion/onnx_to_krnl/Math/Elementwise_with_canonicalize.mlir
- test/mlir/conversion/onnx_to_krnl/Math/Elementwise_with_canonicalize_O3.mlir
Added support for the MeanVarianceNormalization operation in the ONNX to Krnl lowering . Also included corresponding test cases in Elementwise_with_canonicalize.mlir and Elementwise_with_canonicalize_O3.mlir. 
This implementation addresses and
closes https://github.com/onnx/onnx-mlir/issues/3168
> Added lowering for MeanVarianceNorm From ONNX-To-Krnl

- src/Dialect/ONNX/ONNXOps/Canonicalize.cpp
- src/Dialect/ONNX/ONNXOps/Canonicalize.td
- test/mlir/onnx/onnx_canonicalization.mlir
This patch adds one optimization rule to Mul's canonicalization that fuses MatMul and Mul if one of the operands of Mul is a scalar constant.
This pattern is found in IBM granite models.
> Fuse MatMul and Mul if one of the operands of Mul is a scalar constant

- docs/BuildOnLinuxOSX.md
- docs/BuildOnWindows.md
- src/Compiler/CompilerUtils.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Conversion/ONNXToKrnl/Tensor/Size.cpp
- src/Dialect/Krnl/Krnl.td
- src/Dialect/Mlir/DialectBuilder.cpp
- src/Dialect/Mlir/IndexExprDetail.cpp
- src/Dialect/ONNX/AdditionalONNXOps.td
- utils/clone-mlir.sh
This PR updates llvm to commit: f8cb7987c64dcffb72414a40560055cb717dbf74
Stablehlo commit: 69d6dae46e1c7de36e6e6973654754f05353cba5
Changes:
1.  Fixed the build warning: llvm/include/llvm/ADT/ArrayRef.h:70:18: note: 'ArrayRef' has been explicitly marked deprecated here
70 |     /*implicit*/ LLVM_DEPRECATED("Use {} or ArrayRef<T>() instead", "{}")
2.   Fixed the Build failure: Switch type and value ordering for arith Constant[XX]Op
> update llvm and stablehlo

- src/Conversion/KrnlToLLVM/ConvertKrnlToLLVM.cpp
- test/mlir/driver/remove_onnx_arg_attrs.mlir
When compiling a model with the verbose mode (-v), there are many warnings as the following:
```
Unhandled parameter attribute 'onnx.dim_params'
Unhandled parameter attribute 'onnx.name'
Unhandled parameter attribute 'onnx.dim_params'
Unhandled parameter attribute 'onnx.name'
```
These attributes are from `func.func` operations and they are unhandled when translating LLVMIR to LLVM bitcode.
This patch removes these attributes before lowering to LLVMIR so that they do not appear in LLVMIR, which avoids the warnings.
> Remove unused function argument attributes to avoid llvm warnings

- src/Accelerators/NNPA/Conversion/ZHighToZLow/ProcessStickData.cpp
- src/Accelerators/NNPA/Conversion/ZHighToZLow/ProcessStickData.hpp.inc
- src/Accelerators/NNPA/Conversion/ZHighToZLow/ZHighToZLow.cpp
- src/Accelerators/NNPA/Transform/ZLow/ZLowStickExpansion.cpp
- src/Conversion/ONNXToKrnl/Additional/LayoutTransform.cpp
- src/Conversion/ONNXToKrnl/Math/Elementwise.cpp
- src/Conversion/ONNXToKrnl/Math/Gemm.cpp
- src/Conversion/ONNXToKrnl/Math/MatMul.cpp
- src/Conversion/ONNXToKrnl/Math/Reduction.cpp
- src/Conversion/ONNXToKrnl/Math/Softmax.cpp
- src/Conversion/ONNXToKrnl/NN/Conv.cpp
- src/Conversion/ONNXToKrnl/NN/Normalization.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp
- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.hpp
- src/Conversion/ONNXToKrnl/Tensor/Concat.cpp
- src/Conversion/ONNXToKrnl/Tensor/Expand.cpp
- src/Conversion/ONNXToKrnl/Tensor/Gather.cpp
- src/Conversion/ONNXToKrnl/Tensor/Slice.cpp
- src/Conversion/ONNXToKrnl/Tensor/Transpose.cpp
This patch refactors the code for emitting `krnl.parallel` by creating a common function `tryCreateKrnlParallel`. There is is no function change in this patch.
> [NFC] Create a common helper function for emitting krnl.parallel

- src/Conversion/ONNXToKrnl/Additional/LayoutTransform.cpp
- test/mlir/accelerators/nnpa/conversion/onnx-to-krnl/onnx-on-ztensor.mlir
In the new LLVM, dimensional operand cannot be used as a symbol. We had to change many symbols to dimensions when updating LLVM, but still missing one in LayoutTransform.
> Fix dimensional operand cannot be used as a symbol in LayoutTransform

- src/Runtime/OMExternalConstant.inc
Edit an error message when opening the .constants.bin file by adding an instruction of how to fix.
> Edit an error message when opening the .constants.bin file

- src/Dialect/ONNX/ONNXOps/Canonicalize.cpp
- src/Dialect/ONNX/ONNXOps/Canonicalize.td
- test/mlir/onnx/onnx_canonicalization.mlir
This patch adds one optimization rule to Div's canonicalization that fuses MatMul and Div if the 2nd operand of Div is a scalar constant
This pattern is found in IBM granite models.
(This patch is similar to #3214 which is for MatMul and Mul)
> Fuse MatMul and Div if the 2nd operand of Div is a scalar constant

- src/Dialect/ONNX/ONNXOps/Tensor/Range.cpp
- test/mlir/onnx/onnx_shape_inference.mlir
There is a case in IBM granite models (or perhaps decoding models) where the output shape of Range operation can be computed at compile, that is `limit = start + constant_value`, in this case the output dim is `constant_value / delta` despite `start` being a constant or not.
This patch adds such a special case for Range's shape inference.
> Special case for shape inference for onnx.Range operator

- src/Conversion/ONNXToKrnl/ONNXToKrnlCommon.cpp
Issue with Index Expr used out of scope, this fixes the issue reported in a benchmark.
> Fixed index expr in safe-code-gen mode

- src/Dialect/ONNX/ONNXOps/Canonicalize.cpp
- test/mlir/onnx/onnx_canonicalization.mlir
This patch adds a canonicalize rule for ConcatOp which removes operands whose dimension size at the concatenating axis is zero.
> A rule to remove operands in ConcatOp whose dimension size at axis is zero

- src/Runtime/omp/CMakeLists.txt
- utils/make-report.py
Added and implemented this option
```
--reporting <name>:  quartile: average excluding outlier experiments (default).
all: average including every experiments.
sum: sum of every experiments.
```
useful for a case like Tong where he wants to sum all the times from 100 experiments.
> Add sum and total option to report time in make-report.py

- src/Accelerators/NNPA/CMakeLists.txt
- src/CMakeLists.txt
- src/Runtime/omp/CMakeLists.txt
Following #3290, there is another place where you need a change so that zdnnx can find omp in llvm.
> Fix two issues to make omp work again with --parallel and zdnnx
